 function sm=makePhonCorrectSoundManager(speechparams,noiseparams)
% this is a manager for auditory intensity discrimination
% where we want tight control over sounds

sm=soundManager({setAmp(soundClip('correctSound','phonemeWavGlobal',speechparams),speechparams.amp), ...
            soundClip('keepGoingSound','empty'), ...
            soundClip('trySomethingElseSound','empty'), ...
            soundClip('wrongSound','pulseAndNoise',noiseparams),... 
            soundClip('earlywrongSound','pulseAndNoise',noiseparams),...
            soundClip('trialStartSound','empty')});
        