function cells=cells_list_somatostatin

% list of cellss recorded in somatostatin arch and chr2 mice

% **mode should be one of: 'lca', 'mua', 'lfp'
% **genotype indicates transgenic line of mouse
% **'NAN' indicates an unknown value
%You can leave CF as nan if you don't know it, or haven't looked at the
%tuning curve yet
%there are some recordings of SPN stimuli

% THIS CELL LIST IS NOT BY RECORDINGS BUT BY INDIVIDUAL CELL
y='yes';
n='no';
m='maybe';
CB='channel blockers';
N='normal internal solution';
ut='untuned';
nr='not responsive';

%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~%
i=0;

% i=i:1;
% cells(i).sorter='MClust';
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).genotype=''; %arch or chr2
% cells(i).mouse_number=[];
% cells(i).laser_intensity=[]; %mWT measured at the tip of the optic fiber
% cells(i).expdate='';
% cells(i).session='';
% cells(i).OE_filename='';
% cells(i).tetrode=[];
% cells(i).cluster=[];
% cells(i).CF=[];
% cells(i).depth=.40; %total number of turns
% cells(i).mode='';
% cells(i).note='';
% cells(i).filenum(1,:)='';
% cells(i).quality(1)=[]; %quality of the cluster
% cells(i).description{1}='';
% cells(i).effect{1}='';
% cells(i).notes{1}='';
% cells(i).cells_number='';
% cells(i).extra2='';

i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=8;
cells(i).cluster=4;
cells(i).CF=7.4;
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note='';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='poor tuning, some increase in tone evoked';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='y';
cells(i).notes{2}='gap responses at 1 ms silenced, others looks like off responses.';
cells(i).cells_number='4';
cells(i).extra2='';

i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=8;
cells(i).cluster=3;
cells(i).CF=13.6;
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note='';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='suppression of tone evoked?';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='y';
cells(i).notes{2}='interesting late responses, some small decrease';
cells(i).cells_number='4';
cells(i).extra2='';

i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=8;
cells(i).cluster=3;
cells(i).CF='ut';
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note='';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='n';
cells(i).notes{1}='no effect';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='n';
cells(i).notes{2}='look like silenced gap responses';
cells(i).cells_number='4';
cells(i).extra2='';


i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=8;
cells(i).cluster=2;
cells(i).CF='ut';
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note='';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='n';
cells(i).notes{1}='no effect';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='n';
cells(i).notes{2}='look like silenced gap responses';
cells(i).cells_number='4';
cells(i).extra2='';

i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=8;
cells(i).cluster=1;
cells(i).CF=11;
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note='';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in FR';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='n';
cells(i).notes{2}='no gap responses,no effect';
cells(i).cells_number='4';
cells(i).extra2='';

i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=7;
cells(i).cluster=3;
cells(i).CF='ut';
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note='';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='n';
cells(i).notes{1}='no effect, soem tone evoked responses, some suppression';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='n';
cells(i).notes{2}='no gap responses,no effect';
cells(i).cells_number='3';
cells(i).extra2='';

i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=7;
cells(i).cluster=3;
cells(i).CF='ut';
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note='';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='n';
cells(i).notes{1}='no effect, soem tone evoked responses, some suppression';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='n';
cells(i).notes{2}='no gap responses,no effect';
cells(i).cells_number='3';
cells(i).extra2='';

i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=7;
cells(i).cluster=2;
cells(i).CF='ut';
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note='';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='n';
cells(i).notes{1}='no effect';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='n';
cells(i).notes{2}='has gap responses,no effect';
cells(i).cells_number='3';
cells(i).extra2='';

i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=7;
cells(i).cluster=1;
cells(i).CF='ut';
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note='wn responses and some tone evoked responses';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='n';
cells(i).notes{1}='no effect';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='y';
cells(i).notes{2}='has gap responses, small effect';
cells(i).cells_number='3';
cells(i).extra2='';

i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=6;
cells(i).cluster=2;
cells(i).CF='ut';
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note='wn responses';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='n';
cells(i).notes{1}='no effect';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='n';
cells(i).notes{2}='no gap responses';
cells(i).cells_number='2';
cells(i).extra2='';

i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=6;
cells(i).cluster=1;
cells(i).CF='ut';
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note='no wn responses';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='n';
cells(i).notes{1}='no effect';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='y';
cells(i).notes{2}='small increase in gap responses';
cells(i).cells_number='2';
cells(i).extra2='';

i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=5;
cells(i).cluster=2;
cells(i).CF=13.6;
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note=' all cells were untuned but well isolated';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=2; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='some increase in FR';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=3; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='y';
cells(i).notes{2}='small increase in gap responses';
cells(i).cells_number='3';
cells(i).extra2='';

i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=5;
cells(i).cluster=2;
cells(i).CF=13.6;
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note=' all cells were untuned but well isolated';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=2; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='some increase in FR';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=3; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='y';
cells(i).notes{2}='small increase in gap responses';
cells(i).cells_number='3';
cells(i).extra2='';

i=i:1;
cells(i).sorter='MClust';
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=33;
cells(i).laser_intensity=26; %mWT measured at the tip of the optic fiber
cells(i).expdate='041515';
cells(i).session='001';
cells(i).tetrode=5;
cells(i).cluster=1;
cells(i).CF='ut';
cells(i).depth=0; %total number of turns
cells(i).mode='SU';
cells(i).note=' all cells were untuned but well isolated';
cells(i).filenum(1,:)='001';
cells(i).OE_filename='13-34-18';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='n';
cells(i).notes{1}='untuned clustered with energy';
cells(i).filenum(2,:)='002';
cells(i).OE_filename='14-39-47';
cells(i).quality(2)=3; %quality of the cluster
cells(i).description{2}='ILGAP'; %aldis's stimulus, 100 ms laser
cells(i).effect{2}='y';
cells(i).notes{2}='small increase in gap responses';
cells(i).cells_number='3';
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=27;
cells(i).laser_intensity=68; %mWT measured at the tip of the optic fiber
cells(i).expdate='012315';
cells(i).session='001';
cells(i).tetrode=8;
cells(i).cluster=1;
cells(i).CF=20.5;
cells(i).depth=.40; %total number of turns
cells(i).mode='SU';
cells(i).note='mostly off responses, weak on responses, WN+';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='12-58-24';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILWNClick';
cells(i).effect{1}='y';
cells(i).notes{1}='suppressed by long tones, some increase in click responses';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='14-44-12';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='ILTC';
cells(i).effect{2}='y';
cells(i).notes{2}='decrease in off responses';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='15-16-06';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='Gap';
cells(i).effect{3}='n';
cells(i).notes{3}='no gap responses, some off responses during longer gaps';
cells(i).filenum(4,:)='005';
cells(i).OE_filename{4}='15-30-15';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='ILGap';
cells(i).effect{4}='n';
cells(i).notes{4}='no gap responses, no effect';
cells(i).cells_number=4;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=27;
cells(i).laser_intensity=68; %mWT measured at the tip of the optic fiber
cells(i).expdate='012315';
cells(i).session='001';
cells(i).tetrode=8;
cells(i).cluster=2;
cells(i).CF='ut';
cells(i).depth=.40; %total number of turns
cells(i).mode='SU';
cells(i).note='mostly off responses,sound responsive but not tuned';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='12-58-24';
cells(i).quality(1)=3; %quality of the cluster
cells(i).description{1}='ILWNClick';
cells(i).effect{1}='y';
cells(i).notes{1}='suppressed by long tones, increase in click responses';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='14-44-12';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='ILTC';
cells(i).effect{2}='y';
cells(i).notes{2}='decrease in off responses';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='15-16-06';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='Gap';
cells(i).effect{3}='n';
cells(i).notes{3}='no gap responses, some off responses during longer gaps';
cells(i).filenum(4,:)='005';
cells(i).OE_filename{4}='15-30-15';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='ILGap';
cells(i).effect{4}='n';
cells(i).notes{4}='no gap responses, no effect';
cells(i).cells_number=3;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=27;
cells(i).laser_intensity=68; %mWT measured at the tip of the optic fiber
cells(i).expdate='012315';
cells(i).session='001';
cells(i).tetrode=8;
cells(i).cluster=3;
cells(i).CF='ut';
cells(i).depth=.40; %total number of turns
cells(i).mode='SU';
cells(i).note='mostly off responses,sound responsive but not tuned';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='12-58-24';
cells(i).quality(1)=3; %quality of the cluster
cells(i).description{1}='ILWNClick';
cells(i).effect{1}='y';
cells(i).notes{1}='suppressed by long tones, increase in click responses';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='14-44-12';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='ILTC';
cells(i).effect{2}='y';
cells(i).notes{2}='decrease in off responses';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='15-16-06';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='Gap';
cells(i).effect{3}='n';
cells(i).notes{3}='no gap responses, some off responses during longer gaps';
cells(i).filenum(4,:)='005';
cells(i).OE_filename{4}='15-30-15';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='ILGap';
cells(i).effect{4}='n';
cells(i).notes{4}='no gap responses, no effect';
cells(i).cells_number=2;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='ChR2'; %arch or chr2
cells(i).mouse_number=23;
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='012215';
cells(i).session='001';
cells(i).tetrode=5;
cells(i).cluster=1;
cells(i).CF=32.7;
cells(i).depth=.40; %total number of turns
cells(i).mode='SU';
cells(i).note='this is the same cells that was recorded on 01.20.15, 01.14.15, 01.15.15';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-02-24';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILWNClick';
cells(i).effect{1}='y';
cells(i).notes{1}='Som cells, some responses to click trains, low firing rate';
cells(i).cells_number=1;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='ChR2'; %arch or chr2
cells(i).mouse_number=23;
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='012015';
cells(i).session='001';
cells(i).tetrode=5;
cells(i).cluster=1;
cells(i).CF=32.7;
cells(i).depth=.40; %total number of turns
cells(i).mode='SU';
cells(i).note='this is the same cells that was recorded on 01.23.15, 01.14.15, 01.15.15';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='12-23-45';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILWNClick';
cells(i).effect{1}='y';
cells(i).notes{1}='Som cells, some responses to click trains, low firing rate';
cells(i).cells_number=1;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='ChR2'; %arch or chr2
cells(i).mouse_number=23;
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='011615';
cells(i).session='001';
cells(i).tetrode=4;
cells(i).cluster=2;
cells(i).CF=32.7;
cells(i).depth=.40; %total number of turns
cells(i).mode='SU';
cells(i).note='this is the same cells that was recorded, 01.14.15, 01.15.15';
cells(i).filenum(1,:)='002';
cells(i).OE_filename{1}='13-39-48';
cells(i).quality(1)=3; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='y';
cells(i).notes{1}='Som cells, very thin tuning curve, poor clustering because of noise';
cells(i).filenum(2,:)='004';
cells(i).OE_filename{2}='16-55-36';
cells(i).quality(2)=3; %quality of the cluster
cells(i).description{2}='ILGap';
cells(i).effect{2}='y';
cells(i).notes{2}='no gap responses';
cells(i).filenum(3,:)='007';
cells(i).OE_filename{3}='17-41-41';
cells(i).quality(3)=3; %quality of the cluster
cells(i).description{3}='ILTC';
cells(i).effect{3}='y';
cells(i).notes{3}='long tones';
cells(i).filenum(4,:)='008';
cells(i).OE_filename{4}='18-03-20';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='ILTC';
cells(i).effect{4}='y';
cells(i).notes{4}='long tones, after .25 of KMA, reduction in firinh rate';
cells(i).cells_number=5;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='ChR2'; %arch or chr2
cells(i).mouse_number=23;
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='011615';
cells(i).session='001';
cells(i).tetrode=5;
cells(i).cluster=1;
cells(i).CF=32.7;
cells(i).depth=.40; %total number of turns
cells(i).mode='SU';
cells(i).note='this is the same cells that was recorded, 01.14.15, 01.15.15';
cells(i).filenum(1,:)='002';
cells(i).OE_filename{1}='13-39-48';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='y';
cells(i).notes{1}='Som cells, poor tuning, WN+';
cells(i).filenum(2,:)='004';
cells(i).OE_filename{2}='16-55-36';
cells(i).quality(2)=3; %quality of the cluster
cells(i).description{2}='ILGap';
cells(i).effect{2}='y';
cells(i).notes{2}='no gap responses';
cells(i).filenum(3,:)='007';
cells(i).OE_filename{3}='17-41-41';
cells(i).quality(3)=3; %quality of the cluster
cells(i).description{3}='ILTC';
cells(i).effect{3}='y';
cells(i).notes{3}='long tones, mostly off responses';
cells(i).filenum(4,:)='008';
cells(i).OE_filename{4}='18-03-20';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='ILTC';
cells(i).effect{4}='y';
cells(i).notes{4}='long tones, after .25 of KMA, reduction in firing rate, loss of sustained responses';
cells(i).cells_number=5;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='011415';
cells(i).session='001';
cells(i).tetrode=1;
cells(i).cluster=2;
cells(i).CF=20.5;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='only 1 tuned cells on this tetrode, 2 more without tuning did not show any interesting effect, clust3 showed increase in spont. FR';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='13-03-49';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='Tuning goes away with laser';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-33-20';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='ILGap';
cells(i).effect{2}='n';
cells(i).notes{2}='no gap responses, some supression of OFF responses';
cells(i).filenum(3,:)='005';
cells(i).OE_filename{3}='17-26-03';
cells(i).quality(3)=4; %quality of the cluster
cells(i).description{3}='ILTC';
cells(i).effect{3}='y';
cells(i).notes{3}='increase in FR, some changed in ON and OFF responses';
cells(i).cells_number=6;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='011415';
cells(i).session='001';
cells(i).tetrode=2;
cells(i).cluster=1;
cells(i).CF=20.5;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='noisy tuning curve';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='13-03-49';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in FR, small effect';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-33-20';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='ILGap';
cells(i).effect{2}='y';
cells(i).notes{2}='no gap responses, increase in OFF responses';
cells(i).filenum(3,:)='005';
cells(i).OE_filename{3}='17-26-03';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='ILTC';
cells(i).effect{3}='y';
cells(i).notes{3}='increase in FR, some changed in ON and OFF responses';
cells(i).cells_number=7;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='011415';
cells(i).session='001';
cells(i).tetrode=3;
cells(i).cluster=1;
cells(i).CF=20.5;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='very small tuning curve, low FR';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='13-03-49';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in FR, small effect, increase in TC';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-33-20';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='ILGap';
cells(i).effect{2}='y';
cells(i).notes{2}='no gap responses, increase in OFF responses';
cells(i).filenum(3,:)='005';
cells(i).OE_filename{3}='17-26-03';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='ILTC';
cells(i).effect{3}='y';
cells(i).notes{3}='increase in FR, some changed in ON and OFF responses, looks like level-dependence goes away';
cells(i).cells_number=8;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='011415';
cells(i).session='001';
cells(i).tetrode=7;
cells(i).cluster=1;
cells(i).CF=4.9;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='very small tuning curve, long responses';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='13-03-49';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in tone-evoked FR, decrease in spont activity';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-33-20';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='ILGap';
cells(i).effect{2}='y';
cells(i).notes{2}='no gap responses, OFF responses go away';
cells(i).filenum(3,:)='002';
cells(i).OE_filename{3}='14-52-42';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='ILTC';
cells(i).effect{3}='y';
cells(i).notes{3}='obvious decrease in firing rate, sound evoked and spont.';
cells(i).cells_number=9;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='011415';
cells(i).session='001';
cells(i).tetrode=7;
cells(i).cluster=2;
cells(i).CF=4.9;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='very small tuning curve, sharp responses';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='13-03-49';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='decrease in tone-evoked FR, decrease in spont activity';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-33-20';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='ILGap';
cells(i).effect{2}='y';
cells(i).notes{2}='no gap responses, decrease in OFF responses';
cells(i).filenum(3,:)='002';
cells(i).OE_filename{3}='14-52-42';
cells(i).quality(3)=4; %quality of the cluster
cells(i).description{3}='ILTC';
cells(i).effect{3}='y';
cells(i).notes{3}='obvious decrease in firing rate, sound evoked and spont.';
cells(i).cells_number=10;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='011015';
cells(i).session='001';
cells(i).tetrode=7;
cells(i).cluster=1;
cells(i).CF=4.9;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='the same as  cells 2 01.14.15';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-26-24';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='decrease in tone-evoked FR and spont activity';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='18-57-40';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='ILNBN';
cells(i).effect{2}='y';
cells(i).notes{2}='increase in OFF responses to NBN';
cells(i).cells_number=10;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='011015';
cells(i).session='001';
cells(i).tetrode=6;
cells(i).cluster=3;
cells(i).CF=4.9;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='two other cellss that do not show an effect';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-26-24';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in tone-evoked FR and spont activity';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='18-57-40';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='ILNBN';
cells(i).effect{2}='y';
cells(i).notes{2}='different responses to NBN, some supression';
cells(i).cells_number=11;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='010915';
cells(i).session='002';
cells(i).tetrode=7;
cells(i).cluster=1;
cells(i).CF=4.9;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='';
cells(i).filenum(1,:)='007';
cells(i).OE_filename{1}='00-22-27';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='silenced by the laser, potential SOM cells';
cells(i).filenum(2,:)='004';
cells(i).OE_filename{2}='21-33-13';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='ILTC';
cells(i).effect{2}='y';
cells(i).notes{2}='long tones, mostly transient responses';
cells(i).filenum(3,:)='005';
cells(i).OE_filename{3}='21-59-30';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='ILGap';
cells(i).effect{3}='n';
cells(i).notes{3}='no gap responses';
cells(i).cells_number=12;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='010915';
cells(i).session='002';
cells(i).tetrode=1;
cells(i).cluster=1;
cells(i).CF=20.5;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='';
cells(i).filenum(1,:)='007';
cells(i).OE_filename{1}='00-22-27';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in firing rate';
cells(i).filenum(2,:)='004';
cells(i).OE_filename{2}='21-33-13';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='ILTC';
cells(i).effect{2}='y';
cells(i).notes{2}='increase in responses to WN';
cells(i).filenum(3,:)='005';
cells(i).OE_filename{3}='21-59-30';
cells(i).quality(3)=4; %quality of the cluster
cells(i).description{3}='ILGap';
cells(i).effect{3}='n';
cells(i).notes{3}='no gap responses';
cells(i).cells_number=13;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='010915';
cells(i).session='002';
cells(i).tetrode=6;
cells(i).cluster=1;
cells(i).CF=6;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='very strong effect';
cells(i).filenum(1,:)='007';
cells(i).OE_filename{1}='00-22-27';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in firing rate expecially to tone evoked';
cells(i).filenum(2,:)='004';
cells(i).OE_filename{2}='21-33-13';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='ILTC';
cells(i).effect{2}='y';
cells(i).notes{2}='transient responses turn into sustained responses';
cells(i).filenum(3,:)='005';
cells(i).OE_filename{3}='21-59-30';
cells(i).quality(3)=4; %quality of the cluster
cells(i).description{3}='ILGap';
cells(i).effect{3}='n';
cells(i).notes{3}='no gap responses, increase in OFF response';
cells(i).cells_number=14;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='010915';
cells(i).session='002';
cells(i).tetrode=6;
cells(i).cluster=3;
cells(i).CF=4.9;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note=' effect, clust 2 untuned';
cells(i).filenum(1,:)='007';
cells(i).OE_filename{1}='00-22-27';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in firing rate, some changes in tone evoked responses';
cells(i).filenum(2,:)='004';
cells(i).OE_filename{2}='21-33-13';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='ILTC';
cells(i).effect{2}='y';
cells(i).notes{2}='looks like on responses go away';
cells(i).filenum(3,:)='005';
cells(i).OE_filename{3}='21-59-30';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='ILGap';
cells(i).effect{3}='n';
cells(i).notes{3}='no gap responses, increase in OFF response';
cells(i).cells_number=15;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='010615';
cells(i).session='001';
cells(i).tetrode=4;
cells(i).cluster=1;
cells(i).CF=16.7;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='very sharp tuning';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-24-44';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='very small changes in responses, tuning stays the same';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='no gap responses, plot func needs fixing';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='20-24-45';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='NS';
cells(i).effect{3}='n';
cells(i).notes{3}='great responses';
cells(i).cells_number=16;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='010615';
cells(i).session='001';
cells(i).tetrode=5;
cells(i).cluster=1;
cells(i).CF=4.9;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='very sharp tuning';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-24-44';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='very small changes in responses, tuning stays the same';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='difficult to see any gap responses, strong on responses';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='20-24-45';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='NS';
cells(i).effect{3}='n';
cells(i).notes{3}='very responsive, off CF';
cells(i).filenum(4,:)='003';
cells(i).OE_filename{4}='19-21-15';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='NS';
cells(i).effect{4}='n';
cells(i).notes{4}='very responsive, on CF';
cells(i).cells_number=17;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='010615';
cells(i).session='001';
cells(i).tetrode=6;
cells(i).cluster=1;
cells(i).CF=6;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='long responses';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-24-44';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='tone evoked responses are less sharp';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='no gap responses, very active';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='20-24-45';
cells(i).quality(3)=4; %quality of the cluster
cells(i).description{3}='NS';
cells(i).effect{3}='n';
cells(i).notes{3}='very responsive, off CF';
cells(i).filenum(4,:)='003';
cells(i).OE_filename{4}='19-21-15';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='NS';
cells(i).effect{4}='n';
cells(i).notes{4}='very responsive, on CF, low pattern';
cells(i).cells_number=18;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='010615';
cells(i).session='001';
cells(i).tetrode=6;
cells(i).cluster=2;
cells(i).CF=6;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='sharp tuning curve';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-24-44';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in firing rate';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='no gap responses, very active';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='20-24-45';
cells(i).quality(3)=4; %quality of the cluster
cells(i).description{3}='NS';
cells(i).effect{3}='n';
cells(i).notes{3}='very responsive, off CF';
cells(i).filenum(4,:)='003';
cells(i).OE_filename{4}='19-21-15';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='NS';
cells(i).effect{4}='n';
cells(i).notes{4}='very responsive, on CF, pattern';
cells(i).cells_number=18;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=26;
cells(i).laser_intensity=22; %mWT measured at the tip of the optic fiber
cells(i).expdate='010615';
cells(i).session='001';
cells(i).tetrode=6;
cells(i).cluster=3;
cells(i).CF=6;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='sharp tuning curve';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-24-44';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in firing rate';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='no gap responses, very active';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='20-24-45';
cells(i).quality(3)=4; %quality of the cluster
cells(i).description{3}='NS';
cells(i).effect{3}='n';
cells(i).notes{3}='very responsive';
cells(i).filenum(4,:)='003';
cells(i).OE_filename{4}='19-21-15';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='NS';
cells(i).effect{4}='n';
cells(i).notes{4}='very responsive, on CF, low pattern';
cells(i).cells_number=18;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=25;
cells(i).laser_intensity=60; %mWT measured at the tip of the optic fiber
cells(i).expdate='122914';
cells(i).session='002';
cells(i).tetrode=1;
cells(i).cluster=1;
cells(i).CF=11.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-06-58';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='improvements in tuning curve with laser';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='no gap responses, low fr';
cells(i).cells_number=19;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=25;
cells(i).laser_intensity=60; %mWT measured at the tip of the optic fiber
cells(i).expdate='122914';
cells(i).session='002';
cells(i).tetrode=2;
cells(i).cluster=4;
cells(i).CF=20.5;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-06-58';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in FR';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='no gap responses';
cells(i).cells_number=20;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=25;
cells(i).laser_intensity=60; %mWT measured at the tip of the optic fiber
cells(i).expdate='122914';
cells(i).session='002';
cells(i).tetrode=2;
cells(i).cluster=5;
cells(i).CF=20.5;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='poor tuning';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-06-58';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in FR';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='no gap responses';
cells(i).cells_number=21;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=25;
cells(i).laser_intensity=60; %mWT measured at the tip of the optic fiber
cells(i).expdate='122914';
cells(i).session='002';
cells(i).tetrode=4;
cells(i).cluster=1;
cells(i).CF='ut';
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='no tuning';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-06-58';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in FR';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='looks like possible gap responses, increase in spont activity';
cells(i).cells_number=22;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=25;
cells(i).laser_intensity=60; %mWT measured at the tip of the optic fiber
cells(i).expdate='122914';
cells(i).session='002';
cells(i).tetrode=5;
cells(i).cluster=2;
cells(i).CF=46.5;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='low fr';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-06-58';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in FR';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='';
cells(i).cells_number=23;
cells(i).extra2='';


i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=25;
cells(i).laser_intensity=60; %mWT measured at the tip of the optic fiber
cells(i).expdate='122914';
cells(i).session='002';
cells(i).tetrode=5;
cells(i).cluster=3;
cells(i).CF=57.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='high tuning';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-06-58';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in FR';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='';
cells(i).cells_number=24;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=25;
cells(i).laser_intensity=60; %mWT measured at the tip of the optic fiber
cells(i).expdate='122914';
cells(i).session='002';
cells(i).tetrode=5;
cells(i).cluster=4;
cells(i).CF=57.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='high fr';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-06-58';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='increase in FR';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='';
cells(i).cells_number=25;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=25;
cells(i).laser_intensity=60; %mWT measured at the tip of the optic fiber
cells(i).expdate='122914';
cells(i).session='002';
cells(i).tetrode=7;
cells(i).cluster=2;
cells(i).CF=11.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='poor tuning';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-06-58';
cells(i).quality(1)=4; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='y';
cells(i).notes{1}='looks like responses are relayed with laser';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=4; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='';
cells(i).cells_number=26;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='Arch'; %arch or chr2
cells(i).mouse_number=25;
cells(i).laser_intensity=60; %mWT measured at the tip of the optic fiber
cells(i).expdate='122914';
cells(i).session='002';
cells(i).tetrode=8;
cells(i).cluster=1;
cells(i).CF=9.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='15-06-58';
cells(i).quality(1)=3; %quality of the cluster
cells(i).description{1}='ILTC';
cells(i).effect{1}='n';
cells(i).notes{1}='nothing';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='16-41-34';
cells(i).quality(2)=3; %quality of the cluster
cells(i).description{2}='GapIL';
cells(i).effect{2}='n';
cells(i).notes{2}='';
cells(i).cells_number=27;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='WT'; %arch or chr2
cells(i).mouse_number=19;
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='122714';
cells(i).session='001';
cells(i).tetrode=2;
cells(i).cluster=1;
cells(i).CF=11.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='SPN project, recorded TC after KMA but OE had an error';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='17-24-58';
cells(i).quality(1)=3; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='poorly tuned cell';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='18-07-19';
cells(i).quality(2)=3; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='seems like strong On and Off responses';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='18-50-08';
cells(i).quality(3)=3; %quality of the cluster
cells(i).description{3}='SPN';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, responses went away';
cells(i).cells_number=28;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='WT'; %arch or chr2
cells(i).mouse_number=19;
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='122714';
cells(i).session='001';
cells(i).tetrode=2;
cells(i).cluster=2;
cells(i).CF=11.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='SPN project';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='17-24-58';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='well tuned cell';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='18-07-19';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='responsive';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='18-50-08';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='SPN';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, still responsive, but reduced firing rate';
cells(i).cells_number=29;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='WT'; %arch or chr2
cells(i).mouse_number=19;
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='122714';
cells(i).session='001';
cells(i).tetrode=2;
cells(i).cluster=3;
cells(i).CF='ut';
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='SPN project';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='17-24-58';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='sound responsive, WN+';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='18-07-19';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='responsive';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='18-50-08';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='SPN';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, still responsive, but reduced firing rate';
cells(i).cells_number=30;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='WT'; %arch or chr2
cells(i).mouse_number=19;
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='122714';
cells(i).session='001';
cells(i).tetrode=4;
cells(i).cluster=1;
cells(i).CF=11.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='SPN project';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='17-24-58';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='sound responsive, tuned, WN+';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='18-07-19';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='strong Off responses';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='18-50-08';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='SPN';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, still responsive, but reduced firing rate, lost pattern';
cells(i).cells_number=31;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='WT'; %arch or chr2
cells(i).mouse_number=19;
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='122714';
cells(i).session='001';
cells(i).tetrode=4;
cells(i).cluster=3;
cells(i).CF=11.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='SPN project';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='17-24-58';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='sound responsive, tuned, WN+';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='18-07-19';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='strong Off responses';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='18-50-08';
cells(i).quality(3)=4; %quality of the cluster
cells(i).description{3}='SPN';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, still responsive, but reduced firing rate';
cells(i).cells_number=32;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='WT'; %arch or chr2
cells(i).mouse_number=19;
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='122714';
cells(i).session='001';
cells(i).tetrode=8;
cells(i).cluster=1;
cells(i).CF=11.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='SPN project';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='17-24-58';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='sound responsive, tuned, WN+';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='18-07-19';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='strong Off responses';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='18-50-08';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='SPN';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, still responsive, but reduced firing rate';
cells(i).cells_number=33;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='WT'; %arch or chr2
cells(i).mouse_number=19;
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='122714';
cells(i).session='001';
cells(i).tetrode=8;
cells(i).cluster=4;
cells(i).CF=11.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='SPN project';
cells(i).filenum(1,:)='001';
cells(i).OE_filename{1}='17-24-58';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='sound responsive, tuned, WN+';
cells(i).filenum(2,:)='002';
cells(i).OE_filename{2}='18-07-19';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='strong Off responses';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='18-50-08';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='SPN';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, still responsive, but reduced firing rate';
cells(i).cells_number=34;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='CHR2'; %arch or chr2
cells(i).mouse_number=22; 
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='122214';
cells(i).session='002';
cells(i).tetrode=1;
cells(i).cluster=3;
cells(i).CF=30.9;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='no pimped cells, well isolated principal cells, SPN project';
cells(i).filenum(1,:)='002';
cells(i).OE_filename{1}='10-35-46';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='sound responsive, tuned, WN+, three more untuned cells on the same tetrode';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='11-15-09';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='responsive';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='12-20-01';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='TC';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, still responsive, but reduced firing rate';
cells(i).filenum(4,:)='005';
cells(i).OE_filename{4}='12-29-19';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='SPN';
cells(i).effect{4}='y'; %after KMA administration
cells(i).notes{4}='after .20 KMA, still responsive, but reduced firing rate';
cells(i).cells_number=35;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='CHR2'; %arch or chr2
cells(i).mouse_number=22; 
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='122214';
cells(i).session='002';
cells(i).tetrode=2;
cells(i).cluster=1;
cells(i).CF='ut';
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='no pimped cells, well isolated principal cells, SPN project';
cells(i).filenum(1,:)='002';
cells(i).OE_filename{1}='10-35-46';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='sound responsive, WN+';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='11-15-09';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='responsive, some pattern';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='12-20-01';
cells(i).quality(3)=4; %quality of the cluster
cells(i).description{3}='TC';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, still responsive, but reduced firing rate';
cells(i).filenum(4,:)='005';
cells(i).OE_filename{4}='12-29-19';
cells(i).quality(4)=4; %quality of the cluster
cells(i).description{4}='SPN';
cells(i).effect{4}='y'; %after KMA administration
cells(i).notes{4}='after .20 KMA, still responsive, but reduced firing rate';
cells(i).cells_number=35;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='CHR2'; %arch or chr2
cells(i).mouse_number=22; 
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='122214';
cells(i).session='002';
cells(i).tetrode=2;
cells(i).cluster=2;
cells(i).CF=57.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='no pimped cells, well isolated principal cells, SPN project';
cells(i).filenum(1,:)='002';
cells(i).OE_filename{1}='10-35-46';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='sound responsive, WN+, small tuning curve, long responses';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='11-15-09';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='responsive, good pattern';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='12-20-01';
cells(i).quality(3)=4; %quality of the cluster
cells(i).description{3}='TC';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, still responsive, responses become transient';
cells(i).filenum(4,:)='005';
cells(i).OE_filename{4}='12-29-19';
cells(i).quality(4)=4; %quality of the cluster
cells(i).description{4}='SPN';
cells(i).effect{4}='y'; %after KMA administration
cells(i).notes{4}='after .20 KMA, still responsive, but reduced firing rate';
cells(i).cells_number=36;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='CHR2'; %arch or chr2
cells(i).mouse_number=22; 
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='122214';
cells(i).session='002';
cells(i).tetrode=2;
cells(i).cluster=3;
cells(i).CF=57.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='no pimped cells, well isolated principal cells, SPN project';
cells(i).filenum(1,:)='002';
cells(i).OE_filename{1}='10-35-46';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='sound responsive, WN-, small tuning curve, high spont act.';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='11-15-09';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='responsive, good pattern';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='12-20-01';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='TC';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, still responsive, responses become transient, spont act goes down';
cells(i).filenum(4,:)='005';
cells(i).OE_filename{4}='12-29-19';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='SPN';
cells(i).effect{4}='y'; %after KMA administration
cells(i).notes{4}='after .20 KMA, awesome pattern';
cells(i).cells_number=37;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='CHR2'; %arch or chr2
cells(i).mouse_number=22; 
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='122214';
cells(i).session='002';
cells(i).tetrode=2;
cells(i).cluster=4;
cells(i).CF=57.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='no pimped cells, well isolated principal cells, SPN project';
cells(i).filenum(1,:)='002';
cells(i).OE_filename{1}='10-35-46';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='sound responsive, poor tuning';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='11-15-09';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='responsive, good pattern';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='12-20-01';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='TC';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, still responsive, responses become transient, spont act goes down';
cells(i).filenum(4,:)='005';
cells(i).OE_filename{4}='12-29-19';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='SPN';
cells(i).effect{4}='y'; %after KMA administration
cells(i).notes{4}='after .20 KMA, awesome pattern';
cells(i).cells_number=38;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='CHR2'; %arch or chr2
cells(i).mouse_number=22; 
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='122214';
cells(i).session='002';
cells(i).tetrode=2;
cells(i).cluster=5;
cells(i).CF='ut';
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='no pimped cells, well isolated principal cells, SPN project';
cells(i).filenum(1,:)='002';
cells(i).OE_filename{1}='10-35-46';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='untuned';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='11-15-09';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='responsive, good pattern';
cells(i).filenum(3,:)='004';
cells(i).OE_filename{3}='12-20-01';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='TC';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, great pattern';
cells(i).filenum(4,:)='005';
cells(i).OE_filename{4}='12-29-19';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='SPN';
cells(i).effect{4}='y'; %after KMA administration
cells(i).notes{4}='after .20 KMA, awesome pattern';
cells(i).cells_number=39;
cells(i).extra2='';

% there are more cells on tetrode 4, 5, 6 (12-22-14) that are poorly tuned. they can
% be added to the cell list

% there are some cells with poor tuning from 12-20-14, did not include them
% since not much can be said about frequency information

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='WT'; %arch or chr2
cells(i).mouse_number=19; 
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='110614';
cells(i).session='002';
cells(i).tetrode=3;
cells(i).cluster=1;
cells(i).CF=11.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='SPN project';
cells(i).filenum(1,:)='002';
cells(i).OE_filename{1}='18-14-54';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='sound responsive, difficult to define CF';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='18-48-??';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='responsive, good pattern';
cells(i).filenum(3,:)='005';
cells(i).OE_filename{3}='19-59-42';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='SPN';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, great pattern, decrease in FR';
cells(i).filenum(4,:)='006';
cells(i).OE_filename{4}='20-26-15';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='TC';
cells(i).effect{4}='y'; %after KMA administration
cells(i).notes{4}='after .20 KMA, tuning preserved but very low FR';
cells(i).cells_number=40;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='WT'; %arch or chr2
cells(i).mouse_number=19; 
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='110614';
cells(i).session='002';
cells(i).tetrode=3;
cells(i).cluster=2;
cells(i).CF=11.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note='SPN project';
cells(i).filenum(1,:)='002';
cells(i).OE_filename{1}='18-14-54';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='sound responsive, difficult to define CF';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='18-48-??';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='responsive, good pattern';
cells(i).filenum(3,:)='005';
cells(i).OE_filename{3}='19-59-42';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='SPN';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, great pattern, decrease in FR';
cells(i).filenum(4,:)='006';
cells(i).OE_filename{4}='20-26-15';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='TC';
cells(i).effect{4}='y'; %after KMA administration
cells(i).notes{4}='after .20 KMA, tuning preserved but very low FR';
cells(i).cells_number=41;
cells(i).extra2='';

i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='WT'; %arch or chr2
cells(i).mouse_number=19; 
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='110614';
cells(i).session='002';
cells(i).tetrode=3;
cells(i).cluster=2;
cells(i).CF=11.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note= 'SPN project';
cells(i).filenum(1,:)='002';
cells(i).OE_filename{1}='18-14-54';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='sound responsive, difficult to define CF';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='18-48-??';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='responsive, good pattern';
cells(i).filenum(3,:)='005';
cells(i).OE_filename{3}='19-59-42';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='SPN';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, great pattern, decrease in FR';
cells(i).filenum(4,:)='006';
cells(i).OE_filename{4}='20-26-15';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='TC';
cells(i).effect{4}='y'; %after KMA administration
cells(i).notes{4}='after .20 KMA, tuning preserved but very low FR';
cells(i).cells_number=42;
cells(i).extra2='';


i=i+1;
cells(i).user='ira';
cells(i).sorter='MClust';
cells(i).rig='rig1';
cells(i).genotype='WT'; %arch or chr2
cells(i).mouse_number=19; 
cells(i).laser_intensity=NaN; %mWT measured at the tip of the optic fiber
cells(i).expdate='110614';
cells(i).session='002';
cells(i).tetrode=4;
cells(i).cluster=1;
cells(i).CF=8.1;
cells(i).depth=NaN; %total number of turns
cells(i).mode='SU';
cells(i).note= 'SPN project';
cells(i).filenum(1,:)='002';
cells(i).OE_filename{1}='18-14-54';
cells(i).quality(1)=5; %quality of the cluster
cells(i).description{1}='TC';
cells(i).effect{1}='n';
cells(i).notes{1}='beautiful tuning curve';
cells(i).filenum(2,:)='003';
cells(i).OE_filename{2}='18-48-??';
cells(i).quality(2)=5; %quality of the cluster
cells(i).description{2}='SPN';
cells(i).effect{2}='n';
cells(i).notes{2}='responsive,ok pattern';
cells(i).filenum(3,:)='005';
cells(i).OE_filename{3}='19-59-42';
cells(i).quality(3)=5; %quality of the cluster
cells(i).description{3}='SPN';
cells(i).effect{3}='y'; %after KMA administration
cells(i).notes{3}='after .20 KMA, great pattern, decrease in FR';
cells(i).filenum(4,:)='006';
cells(i).OE_filename{4}='20-26-15';
cells(i).quality(4)=5; %quality of the cluster
cells(i).description{4}='TC';
cells(i).effect{4}='y'; %after KMA administration
cells(i).notes{4}='after .20 KMA, huge decrease in firing rate';
cells(i).cells_number=43;
cells(i).extra2='';

end