function cells=cell_list_NIHL_xiang
%cell list for xiang's NIHL project
%'mua/lfp' indicates filter is 1.0-5K
%'mua' indicates filter is 300-5K
%'lca' indicates loose-cell-attached patch recording
%'description' indicates start time of datafile relative to trauma and
%whether spontaneous activity was taken
%be careful with {} and ()
% 05/07/09
% some cells have been "inactivated" due to unclear TCs. Also
% note the ones where the electrode was moved in the middle of experiment.
% Last update 06/11/10
% last three cells are recordings from animals that underwent behavioral
% trials with Maddie. Last two were conducted under isoflurane anesthesia. 
% Animals' IDs correspond to the date when behavioral trials began. 
%test mw 020911
i=0;

i=i+1; %spikecount tuning curves look much nicer than psths
cells(i).mode='mua';
cells(i).expdate='070108';
cells(i).session='001';
cells(i).depth=583; %micrometers
cells(i).CF=19100; %Hz
cells(i).trauma_freq=13000; %Hz
cells(i).trauma_level=-1; %dB 2.9V on voltmeter
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='beyma'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='016';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='017';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='018';
cells(i).description{3}='post 9 min';
cells(i).filenum(4,:)='019';
cells(i).description{4}='post 19 min';
cells(i).filenum(5,:)='020';
cells(i).description{5}='post 29 min';
cells(i).filenum(6,:)='021';
cells(i).description{6}='post 38 min';
cells(i).filenum(7,:)='022';
cells(i).description{7}='post 48 min';
cells(i).filenum(8,:)='023';
cells(i).description{8}='post 59 min';
cells(i).filenum(9,:)='024';
cells(i).description{9}='post 68 min';
cells(i).filenum(10,:)='025';
cells(i).description{10}='post 78 min';
cells(i).filenum(11,:)='026';
cells(i).description{11}='post 87 min';

% i=i+1; %animal is gaspy, might account for decreased activity in data.
% cells(i).mode='mua/lfp';
% cells(i).expdate='070208';
% cells(i).session='001';
% cells(i).depth=413; %micrometers
% cells(i).CF=7200; %Hz
% cells(i).trauma_freq=10000; %Hz
% cells(i).trauma_level=-1; %dB 2.9V on voltmeter
% cells(i).trauma_dur=1; %minutes
% cells(i).trauma_speaker='beyma'; %'PO-55T' or 'beyma'
% cells(i).filenum(1,:)='008';
% cells(i).description{1}='pre';
% cells(i).filenum(2,:)='011';
% cells(i).description{2}='pre';
% cells(i).filenum(3,:)='012';
% cells(i).description{3}='post 1 min';
% cells(i).filenum(4,:)='015';
% cells(i).description{4}='post 23 min';
% cells(i).filenum(5,:)='016';
% cells(i).description{5}='post 34 min';
% cells(i).filenum(6,:)='017';
% cells(i).description{6}='post 44 min';
% cells(i).filenum(7,:)='019';
% cells(i).description{7}='post 59 min';
% cells(i).filenum(8,:)='020';
% cells(i).description{8}='post 70 min';
% cells(i).filenum(9,:)='021';
% cells(i).description{9}='post 85 min';
% cells(i).filenum(10,:)='022';
% cells(i).description{10}='post 100 min';
% cells(i).filenum(11,:)='023';
% cells(i).description{11}='post 115 min';
% cells(i).filenum(12,:)='024';
% cells(i).description{12}='post 130 min';
% cells(i).filenum(13,:)='025';
% cells(i).description{13}='post 160 min';
% cells(i).filenum(14,:)='028';
% cells(i).description{14}='post 180 min';

% i=i+1;% no change in TCs- trauma might not have been played
% cells(i).mode='mua/lfp';
% cells(i).expdate='070308';
% cells(i).session='001';
% cells(i).depth=527; %micrometers
% cells(i).CF=7200; %Hz
% cells(i).trauma_freq=10000; %Hz
% cells(i).trauma_level=-1; %dB 3.1V on voltmeter
% cells(i).trauma_dur=1; %minutes
% cells(i).trauma_speaker='beyma'; %'PO-55T' or 'beyma'
% cells(i).filenum(1,:)='013';
% cells(i).description{1}='pre';
% cells(i).filenum(2,:)='014';
% cells(i).description{2}='pre';
% cells(i).filenum(3,:)='016';
% cells(i).description{3}='post 1 min';
% cells(i).filenum(4,:)='017';
% cells(i).description{4}='post 9 min';
% cells(i).filenum(5,:)='018';
% cells(i).description{5}='post 17 min';
% cells(i).filenum(6,:)='019';
% cells(i).description{6}='post 25 min';
% cells(i).filenum(7,:)='020';
% cells(i).trauma_freq=10000; %Hz
% cells(i).trauma_dur=1; %minutes
% cells(i).description{7}='post 1 min';
% cells(i).filenum(8,:)='021';
% cells(i).description{8}='post 10 min';
% cells(i).filenum(9,:)='022';
% cells(i).description{9}='post 21 min';
% cells(i).filenum(10,:)='023';
% cells(i).description{10}='post 31 min';
% cells(i).filenum(11,:)='024';
% cells(i).description{11}='post 43 min';
% cells(i).filenum(12,:)='025';
% cells(i).description{12}='post 53 min';
% cells(i).filenum(13,:)='026';
% cells(i).description{13}='post 62 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='071408';
cells(i).session='001';
cells(i).depth=360; %micrometers
cells(i).CF=7200; %Hz
cells(i).trauma_freq=10000; %Hz
cells(i).trauma_level=-1; %dB 3.1V on voltmeter
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='beyma'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='012';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='013';
cells(i).description{2}='pre';
cells(i).filenum(3,:)='017';
cells(i).description{3}='post 29 min';
cells(i).filenum(4,:)='018';
cells(i).description{4}='post 38 min';
cells(i).filenum(5,:)='019';
cells(i).description{5}='post 47 min';
cells(i).filenum(6,:)='020';
cells(i).description{6}='post 57 min';
cells(i).filenum(7,:)='021';
cells(i).description{7}='post 79 min';
cells(i).filenum(8,:)='022';
cells(i).description{8}='post 100 min';
cells(i).filenum(9,:)='023';
cells(i).description{9}='post 120 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='071508';
cells(i).session='001';
cells(i).depth=431; %micrometers
cells(i).CF=7200; %Hz
cells(i).trauma_freq=10000; %Hz
cells(i).trauma_level=-1; %dB 2.5V on voltmeter
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='beyma'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='019';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='020';
cells(i).description{2}='pre';
cells(i).filenum(3,:)='021';
cells(i).description{3}='post 1 min';
cells(i).filenum(4,:)='022';
cells(i).description{4}='post 10 min';
cells(i).filenum(5,:)='023';
cells(i).description{5}='post 18 min';
cells(i).filenum(6,:)='024';
cells(i).description{6}='post 28 min';
cells(i).filenum(7,:)='025';
cells(i).description{7}='post 45 min';
cells(i).filenum(8,:)='026';
cells(i).description{8}='post 60 min';
cells(i).filenum(9,:)='027';
cells(i).description{9}='post 75 min';
cells(i).filenum(10,:)='028';
cells(i).description{10}='post 105 min';
cells(i).filenum(11,:)='029';
cells(i).description{11}='post 121 min';

% i=i+1; %gaspy animal. Signal peters out occasionally. 
% cells(i).mode='mua/lfp';
% cells(i).expdate='092408';
% cells(i).session='002';
% cells(i).depth=377; %micrometers
% cells(i).CF=16600; %Hz
% cells(i).trauma_freq=11740; %Hz
% cells(i).trauma_level=109; %dB
% cells(i).trauma_dur=.5; %minutes
% cells(i).trauma_speaker='beyma'; %'PO-55T' or 'beyma'
% cells(i).filenum(1,:)='004';
% cells(i).description{1}='pre';
% cells(i).filenum(2,:)='005';
% cells(i).description{2}='post 1 min';
% cells(i).filenum(3,:)='006';
% cells(i).description{3}='post 10 min';
% cells(i).filenum(4,:)='007';
% cells(i).description{4}='post 18 min';
% cells(i).filenum(5,:)='008';
% cells(i).description{5}='post 26 min';
% cells(i).filenum(6,:)='009';
% cells(i).description{6}='post 38 min';
% cells(i).filenum(7,:)='010';
% cells(i).description{7}='post 46 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='092608';
cells(i).session='001';
cells(i).depth=439; %micrometers
cells(i).CF=19800; %Hz
cells(i).trauma_freq=14000; %Hz
cells(i).trauma_level=113; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='beyma'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='023';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='024';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='025';
cells(i).description{3}='post 10 min';
cells(i).filenum(4,:)='026';
cells(i).description{4}='post 18 min';
cells(i).filenum(5,:)='027';
cells(i).description{5}='post 27 min';
cells(i).filenum(6,:)='028';
cells(i).description{6}='post 39 min';
cells(i).filenum(7,:)='029';
cells(i).description{7}='post 53 min';
cells(i).filenum(8,:)='030';
cells(i).description{8}='post 73 min';
cells(i).filenum(9,:)='031';
cells(i).description{9}='post 88 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='092708';
cells(i).session='001';
cells(i).depth=380; %micrometers
cells(i).CF=16600; %Hz
cells(i).trauma_freq=11738; %Hz
cells(i).trauma_level=112; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='beyma'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='011';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='012';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='013';
cells(i).description{3}='post 10 min';
cells(i).filenum(4,:)='016';
cells(i).description{4}='post 19 min';
cells(i).filenum(5,:)='017';
cells(i).description{5}='post 30 min';
cells(i).filenum(6,:)='018';
cells(i).description{6}='post 38 min';
cells(i).filenum(7,:)='019';
cells(i).description{7}='post 51 min';
cells(i).filenum(8,:)='020';
cells(i).description{8}='post 68 min';
cells(i).filenum(9,:)='021';
cells(i).description{9}='post 79 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='100108';
cells(i).session='001';
cells(i).depth=477; %micrometers
cells(i).CF=23600; %Hz
cells(i).trauma_freq=16688; %Hz
cells(i).trauma_level=112; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='beyma'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='020';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='021';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='022';
cells(i).description{3}='post 09 min';
cells(i).filenum(4,:)='023';
cells(i).description{4}='post 19 min';
cells(i).filenum(5,:)='024';
cells(i).description{5}='post 28 min';
cells(i).filenum(6,:)='025';
cells(i).description{6}='post 38 min';
cells(i).filenum(7,:)='026';
cells(i).description{7}='post 51 min';
cells(i).filenum(8,:)='027';
cells(i).description{8}='post 67 min';
cells(i).filenum(9,:)='028';
cells(i).description{9}='post 88 min';
cells(i).filenum(10,:)='029';
cells(i).description{10}='post 110 min';
cells(i).filenum(11,:)='030';
cells(i).description{11}='post 146 min';
cells(i).filenum(12,:)='031';
cells(i).description{12}='post 156 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='100208';
cells(i).session='001';
cells(i).depth=382; %micrometers
cells(i).CF=23600; %Hz
cells(i).trauma_freq=16688; %Hz
cells(i).trauma_level=112; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='beyma'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='006';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='007';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='008';
cells(i).description{3}='post 10 min';
cells(i).filenum(4,:)='009';
cells(i).description{4}='post 21 min';
cells(i).filenum(5,:)='010';
cells(i).description{5}='post 29 min';
cells(i).filenum(6,:)='011';
cells(i).description{6}='post 47 min';
cells(i).filenum(7,:)='012';
cells(i).description{7}='post 60 min';
cells(i).filenum(8,:)='013';
cells(i).description{8}='post 80 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='100308';
cells(i).session='001';
cells(i).depth=595; %micrometers
cells(i).CF=19800; %Hz
cells(i).trauma_freq=14000; %Hz
cells(i).trauma_level=113; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='beyma'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='009';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='010';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='011';
cells(i).description{3}='post 10 min';
cells(i).filenum(4,:)='012';
cells(i).description{4}='post 20 min';
cells(i).filenum(5,:)='013';
cells(i).description{5}='post 33 min';
cells(i).filenum(6,:)='014';
cells(i).description{6}='post 47 min';
cells(i).filenum(7,:)='015';
cells(i).description{7}='post 65 min';
cells(i).filenum(8,:)='016';
cells(i).description{8}='post 78 min';
cells(i).filenum(9,:)='017';
cells(i).description{9}='post 90 min';

% i=i+1; %Crappy TC
% cells(i).mode='mua/lfp';
% cells(i).expdate='100808';
% cells(i).session='001';
% cells(i).depth=430; %micrometers
% cells(i).CF=23600; %Hz
% cells(i).trauma_freq=16688; %Hz
% cells(i).trauma_level=-1; %dB  1.7V from voltmeter
% cells(i).trauma_dur=.5; %minutes
% cells(i).trauma_speaker='beyma'; %'PO-55T' or 'beyma'
% cells(i).filenum(1,:)='016';
% cells(i).description{1}='pre';
% cells(i).filenum(2,:)='017';
% cells(i).description{2}='post 1 min';
% cells(i).filenum(3,:)='018';
% cells(i).description{3}='post 9 min';
% cells(i).filenum(4,:)='019';
% cells(i).description{4}='post 18 min';
% cells(i).filenum(5,:)='020';
% cells(i).description{5}='post 30 min';
% cells(i).filenum(6,:)='021';
% cells(i).description{6}='post 41 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='100908';
cells(i).session='001';
cells(i).depth=317; %micrometers
cells(i).CF=11700; %Hz
cells(i).trauma_freq=8273; %Hz
cells(i).trauma_level=-1; %dB  1.18 from voltmeter
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='beyma'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='013';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='014';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='015';
cells(i).description{3}='post 14 min';
cells(i).filenum(4,:)='016';
cells(i).description{4}='post 22 min';
cells(i).filenum(5,:)='017';
cells(i).description{5}='post 30 min';
cells(i).filenum(6,:)='018';
cells(i).description{6}='post 50 min';
cells(i).filenum(7,:)='019';
cells(i).description{7}='post 75 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='101008';
cells(i).session='001';
cells(i).depth=510; %micrometers
cells(i).CF=23600; %Hz
cells(i).trauma_freq=16668; %Hz
cells(i).trauma_level=100; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='007';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='008';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='009';
cells(i).description{3}='post 04 min';
cells(i).filenum(4,:)='010';
cells(i).description{4}='post 12 min';
cells(i).filenum(5,:)='011';
cells(i).description{5}='post 21 min';
cells(i).filenum(6,:)='012';
cells(i).description{6}='post 29 min';
cells(i).filenum(7,:)='013';
cells(i).description{7}='post 39 min';
cells(i).filenum(8,:)='014';
cells(i).description{8}='post 64 min';
cells(i).filenum(9,:)='015';
cells(i).description{9}='post 86 min';
cells(i).filenum(10,:)='016';
cells(i).description{10}='post 113 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='101508';
cells(i).session='002';
cells(i).depth=-1; %micrometers  estimate 300
cells(i).CF=19800; %Hz
cells(i).trauma_freq=14000; %Hz
cells(i).trauma_level=110; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='001';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='002';
cells(i).description{2}='post 1 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='101608';
cells(i).session='002';
cells(i).depth=416; %micrometers
cells(i).CF=23600; %Hz
cells(i).trauma_freq=16668; %Hz
cells(i).trauma_level=110; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='000';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='001';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='002';
cells(i).description{3}='post 09 min';
cells(i).filenum(4,:)='003';
cells(i).description{4}='post 17 min';
cells(i).filenum(5,:)='004';
cells(i).description{5}='post 26 min';
cells(i).filenum(6,:)='005';
cells(i).description{6}='post 46 min';
cells(i).filenum(7,:)='006';
cells(i).description{7}='post 61 min';
cells(i).filenum(8,:)='007';
cells(i).description{8}='post 81 min';
cells(i).filenum(9,:)='008';
cells(i).description{9}='post 106 min';
cells(i).filenum(10,:)='009';
cells(i).description{10}='post 120 min';
cells(i).filenum(11,:)='010';
cells(i).description{11}='post 153 min';
cells(i).filenum(12,:)='011';
cells(i).description{12}='post 181 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='102908';
cells(i).session='001';
cells(i).depth=436; %micrometers
cells(i).CF=24500; %Hz
cells(i).trauma_freq=17324; %Hz
cells(i).trauma_level=101; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='007';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='009';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='010';
cells(i).description{3}='post 13 min';
cells(i).filenum(4,:)='011';
cells(i).description{4}='post 29 min';
cells(i).filenum(5,:)='012';
cells(i).description{5}='post 40 min';
cells(i).filenum(6,:)='013';
cells(i).description{6}='post 60 min';
cells(i).filenum(7,:)='014';
cells(i).description{7}='post 90 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='103008';
cells(i).session='001';
cells(i).depth=247; %micrometers might be ~347 difficult to zero at cortex
cells(i).CF=20700; %Hz
cells(i).trauma_freq=14637; %Hz
cells(i).trauma_level=107; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='011';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='012';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='013';
cells(i).description{3}='post 13 min';
cells(i).filenum(4,:)='014';
cells(i).description{4}='post 25 min';
cells(i).filenum(5,:)='015';
cells(i).description{5}='post 38 min';
cells(i).filenum(6,:)='016';
cells(i).description{6}='post 60 min';
cells(i).filenum(7,:)='017';
cells(i).description{7}='post 75 min';
cells(i).filenum(8,:)='018';
cells(i).description{8}='post 106 min';
cells(i).filenum(9,:)='019';
cells(i).description{9}='post 150 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='121508';
cells(i).session='001';
cells(i).depth=395; %micrometers
cells(i).CF=20700; %Hz
cells(i).trauma_freq=14637; %Hz
cells(i).trauma_level=110; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='014';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='015';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='016';
cells(i).description{3}='post 12 min';
cells(i).filenum(4,:)='017';
cells(i).description{4}='post 24 min';
cells(i).filenum(5,:)='018';
cells(i).description{5}='post 36 min';
cells(i).filenum(6,:)='019';
cells(i).description{6}='post 62 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='121608';
cells(i).session='001';
cells(i).depth=247; %micrometers
cells(i).CF=24500; %Hz
cells(i).trauma_freq=17324; %Hz
cells(i).trauma_level=111; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='008';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='009';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='010';
cells(i).description{3}='post 14 min';
cells(i).filenum(4,:)='011';
cells(i).description{4}='post 31 min';
cells(i).filenum(5,:)='012';
cells(i).description{5}='post 61 min';
cells(i).filenum(6,:)='013';
cells(i).description{6}='post 92 min';
cells(i).filenum(7,:)='014';
cells(i).description{7}='post 121 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='121808';
cells(i).session='001';
cells(i).depth=592; %micrometers
cells(i).CF=24500; %Hz
cells(i).trauma_freq=17324; %Hz
cells(i).trauma_level=113; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='010';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='011';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='012';
cells(i).description{3}='post 12 min';
cells(i).filenum(4,:)='013';
cells(i).description{4}='post 25 min';
cells(i).filenum(5,:)='014';
cells(i).description{5}='post 61 min';
cells(i).filenum(6,:)='015';
cells(i).description{6}='post 91 min';
cells(i).filenum(7,:)='016';
cells(i).description{7}='post 122 min';
cells(i).filenum(8,:)='017';
cells(i).description{8}='post 151 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='121908';
cells(i).session='001';
cells(i).depth=400; %micrometers
cells(i).CF=24500; %Hz
cells(i).trauma_freq=17324; %Hz
cells(i).trauma_level=111; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='006';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='007';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='008';
cells(i).description{3}='post 12 min';
cells(i).filenum(4,:)='009';
cells(i).description{4}='post 24 min';
cells(i).filenum(5,:)='010';
cells(i).description{5}='post 62 min';
cells(i).filenum(6,:)='011';
cells(i).description{6}='post 95 min';
cells(i).filenum(7,:)='012';
cells(i).description{7}='post 121 min';
cells(i).filenum(8,:)='013';
cells(i).description{8}='post 151 min';
cells(i).filenum(9,:)='014';
cells(i).description{9}='post 196 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='010609';
cells(i).session='001';
cells(i).depth=348; %micrometers
cells(i).CF=5300; %Hz
cells(i).trauma_freq=7495; %Hz
cells(i).trauma_level=110; %dB
cells(i).trauma_dur=.5; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='014';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='015';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='016';
cells(i).description{3}='post 13 min';
cells(i).filenum(4,:)='017';
cells(i).description{4}='post 25 min';
cells(i).filenum(5,:)='018';
cells(i).description{5}='post 60 min';
cells(i).filenum(6,:)='019';
cells(i).description{6}='post 90 min';
cells(i).filenum(7,:)='020';
cells(i).description{7}='post 112 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='010809';
cells(i).session='001';
cells(i).depth=384; %micrometers
cells(i).CF=7500; %Hz
cells(i).trauma_freq=10606; %Hz
cells(i).trauma_level=110; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='003';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='004';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='005';
cells(i).description{3}='post 14 min';
cells(i).filenum(4,:)='006';
cells(i).description{4}='post 26 min';
cells(i).filenum(5,:)='007';
cells(i).description{5}='post 61 min';
cells(i).filenum(6,:)='008';
cells(i).description{6}='post 92 min';
cells(i).filenum(7,:)='009';
cells(i).description{7}='post 122 min';
cells(i).filenum(7,:)='010';
cells(i).description{7}='post 151 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='011309';
cells(i).session='001';
cells(i).depth=459; %micrometers
cells(i).CF=7500; %Hz
cells(i).trauma_freq=10607; %Hz
cells(i).trauma_level=110; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='007';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='008';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='009';
cells(i).description{3}='post 12 min';
cells(i).filenum(4,:)='010';
cells(i).description{4}='post 24 min';
cells(i).filenum(5,:)='011';
cells(i).description{5}='post 60 min';
cells(i).filenum(6,:)='012';
cells(i).description{6}='post 92 min';
cells(i).filenum(7,:)='013';
cells(i).description{7}='post 122 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='011509';
cells(i).session='001';
cells(i).depth=459; %micrometers
cells(i).CF=5300; %Hz
cells(i).trauma_freq=7495; %Hz
cells(i).trauma_level=111; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='005';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='006';
cells(i).description{2}='post 2 min';
cells(i).filenum(3,:)='007';
cells(i).description{3}='post 13 min';
cells(i).filenum(4,:)='008';
cells(i).description{4}='post 25 min';
cells(i).filenum(5,:)='010';
cells(i).description{5}='post 60 min';
cells(i).filenum(6,:)='011';
cells(i).description{6}='post 92 min';
cells(i).filenum(7,:)='012';
cells(i).description{7}='post 120 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='011609';
cells(i).session='001';
cells(i).depth=384; %micrometers
cells(i).CF=7500; %Hz
cells(i).trauma_freq=10607; %Hz
cells(i).trauma_level=110; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='005';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='006';
cells(i).description{2}='post 1 min';
cells(i).filenum(3,:)='007';
cells(i).description{3}='post 14 min';
cells(i).filenum(4,:)='008';
cells(i).description{4}='post 33 min';
cells(i).filenum(5,:)='009';
cells(i).description{5}='post 60 min';
cells(i).filenum(6,:)='010';
cells(i).description{6}='post 90 min';
cells(i).filenum(7,:)='011';
cells(i).description{7}='post 120 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='012309';
cells(i).session='001';
cells(i).depth=410; %micrometers
cells(i).CF=4900; %Hz
cells(i).trauma_freq=17000; %Hz
cells(i).trauma_level=106; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='012';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='013';
cells(i).description{2}='pre';
cells(i).filenum(3,:)='014';
cells(i).description{3}='post 5 min';
cells(i).filenum(4,:)='015';
cells(i).description{4}='post 15 min';
cells(i).filenum(5,:)='016';
cells(i).description{5}='post 23 min';
cells(i).filenum(6,:)='017';
cells(i).description{6}='post 63 min';
cells(i).filenum(7,:)='018';
cells(i).description{7}='post 90 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='012709';
cells(i).session='001';
cells(i).depth=371; %micrometers
cells(i).CF=2900; %Hz
cells(i).trauma_freq=17000; %Hz
cells(i).trauma_level=110; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='006';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='007';
cells(i).description{2}='pre';
cells(i).filenum(3,:)='008';
cells(i).description{3}='post 2 min';
cells(i).filenum(4,:)='009';
cells(i).description{4}='post 11 min';
cells(i).filenum(5,:)='010';
cells(i).description{5}='post 21 min';
cells(i).filenum(6,:)='012';
cells(i).description{6}='post 60 min';
cells(i).filenum(7,:)='013';
cells(i).description{7}='post 92 min';
cells(i).filenum(8,:)='014';
cells(i).description{8}='post 122 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='012909';
cells(i).session='001';
cells(i).depth=348; %micrometers
cells(i).CF=6900; %Hz
cells(i).trauma_freq=17000; %Hz
cells(i).trauma_level=113; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='004';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='005';
cells(i).description{2}='pre';
cells(i).filenum(3,:)='006';
cells(i).description{3}='post 1 min';
cells(i).filenum(4,:)='007';
cells(i).description{4}='post 12 min';
cells(i).filenum(5,:)='008';
cells(i).description{5}='post 21 min';
cells(i).filenum(6,:)='010';
cells(i).description{6}='post 68 min';
cells(i).filenum(7,:)='011';
cells(i).description{7}='post 92 min';
cells(i).filenum(8,:)='012';
cells(i).description{8}='post 129 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='020709';
cells(i).session='001';
cells(i).depth=416; %micrometers
cells(i).CF=8200; %Hz
cells(i).trauma_freq=17000; %Hz
cells(i).trauma_level=111; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='004';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='005';
cells(i).description{2}='pre';
cells(i).filenum(3,:)='006';
cells(i).description{3}='post 1 min';
cells(i).filenum(4,:)='007';
cells(i).description{4}='post 9 min';
cells(i).filenum(5,:)='008';
cells(i).description{5}='post 19 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='021109';
cells(i).session='001';
cells(i).depth=398; %micrometers
cells(i).CF=19800; %Hz
cells(i).trauma_freq=17000; %Hz
cells(i).trauma_level=111; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='010';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='011';
cells(i).description{2}='pre';
cells(i).filenum(3,:)='012';
cells(i).description{3}='post 1 min';
cells(i).filenum(4,:)='013';
cells(i).description{4}='post 11 min';
cells(i).filenum(5,:)='014';
cells(i).description{5}='post 20 min';
cells(i).filenum(6,:)='015';
cells(i).description{6}='post 61 min';
cells(i).filenum(7,:)='016';
cells(i).description{7}='post 91 min';
cells(i).filenum(8,:)='017';
cells(i).description{8}='post 121 min';
cells(i).filenum(9,:)='018';
cells(i).description{9}='post 150 min';
cells(i).filenum(10,:)='019';
cells(i).description{10}='post 184 min';
cells(i).filenum(11,:)='020';
cells(i).description{11}='post 240 min';
cells(i).filenum(12,:)='021';
cells(i).description{12}='post 300 min';
cells(i).filenum(13,:)='022';
cells(i).description{13}='post 360 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='021309';
cells(i).session='001';
cells(i).depth=354; %micrometers
cells(i).CF=6900; %Hz
cells(i).trauma_freq=17000; %Hz
cells(i).trauma_level=111; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='002';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='003';
cells(i).description{2}='pre';
cells(i).filenum(3,:)='004';
cells(i).description{3}='post 2 min';
cells(i).filenum(4,:)='005';
cells(i).description{4}='post 11 min';
cells(i).filenum(5,:)='006';
cells(i).description{5}='post 20 min';
cells(i).filenum(6,:)='007';
cells(i).description{6}='post 66 min';
cells(i).filenum(7,:)='008';
cells(i).description{7}='post 93 min';
cells(i).filenum(8,:)='009';
cells(i).description{8}='post 120 min';
cells(i).filenum(9,:)='010';
cells(i).description{9}='post 150 min';
cells(i).filenum(10,:)='011';
cells(i).description{10}='post 181 min';
cells(i).filenum(11,:)='012';
cells(i).description{11}='post 212 min';
cells(i).filenum(12,:)='013';
cells(i).description{12}='post 270 min';
cells(i).filenum(13,:)='016';
cells(i).description{13}='post 342 min';
cells(i).filenum(14,:)='018';
cells(i).description{14}='post 395 min';
cells(i).filenum(15,:)='019';
cells(i).description{15}='post 450 min';
cells(i).filenum(16,:)='020';
cells(i).description{16}='post 480 min';
cells(i).filenum(17,:)='021';
cells(i).description{17}='post 491 min';
cells(i).filenum(18,:)='022';
cells(i).description{18}='post 510 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='021809';
cells(i).session='001';
cells(i).depth=432; %micrometers
cells(i).CF=5000; %Hz
cells(i).trauma_freq=17000; %Hz
cells(i).trauma_level=111; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='003';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='004';
cells(i).description{2}='pre';
cells(i).filenum(3,:)='005';
cells(i).description{3}='pre';
cells(i).filenum(4,:)='006';
cells(i).description{4}='post 2 min';
cells(i).filenum(5,:)='007';
cells(i).description{5}='post 12 min';
cells(i).filenum(6,:)='008';
cells(i).description{6}='post 23 min';
cells(i).filenum(7,:)='009';
cells(i).description{7}='post 60 min';
cells(i).filenum(8,:)='010';
cells(i).description{8}='post 90 min';
cells(i).filenum(9,:)='011';
cells(i).description{9}='post 124 min';
%cells(i).filenum(10,:)='012'; %%%missed soundcard trigger on event 374, TC
%looks crappy as a result
%cells(i).description{10}='post 150 min';
cells(i).filenum(10,:)='013';
cells(i).description{10}='post 161 min'; % electrode was re-placed prior to this file
cells(i).filenum(11,:)='015';
cells(i).description{11}='post 167 min';
cells(i).filenum(12,:)='016';
cells(i).description{12}='post 181 min';
cells(i).filenum(13,:)='017';
cells(i).description{13}='post 240 min';
cells(i).filenum(14,:)='018';
cells(i).description{14}='post 300 min';
cells(i).filenum(15,:)='019';
cells(i).description{15}='post 360 min';
cells(i).filenum(16,:)='020';
cells(i).description{16}='post 410 min';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='022509';
cells(i).session='001';
cells(i).depth=375; %micrometers
cells(i).CF=6900; %Hz
cells(i).trauma_freq=17000; %Hz
cells(i).trauma_level=112; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='011';
cells(i).description{1}='pre+spont'; %spontaneous activity taken for at least 1 minute prior or post tone train
cells(i).filenum(2,:)='012';
cells(i).description{2}='pre+spont';
cells(i).filenum(3,:)='013';
cells(i).description{3}='post 2 min+spont';
cells(i).filenum(4,:)='014';
cells(i).description{4}='post 11 min+spont';
cells(i).filenum(5,:)='015';
cells(i).description{5}='post 68 min+spont';
cells(i).filenum(6,:)='016';
cells(i).description{6}='post 90 min+spont';
cells(i).filenum(7,:)='017';
cells(i).description{7}='post 120 min+spont';
cells(i).filenum(8,:)='018';
cells(i).description{8}='post 156 min+spont';
cells(i).filenum(9,:)='019';
cells(i).description{9}='post 180 min+spont';
cells(i).filenum(10,:)='020';
cells(i).description{10}='post 240 min+spont';
cells(i).filenum(11,:)='021';
cells(i).description{11}='post 300 min+spont';
cells(i).filenum(12,:)='022';
cells(i).description{12}='post 360 min+spont';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='022709';
cells(i).session='001';
cells(i).depth=411; %micrometers
cells(i).CF=5800; %Hz
cells(i).trauma_freq=17000; %Hz
cells(i).trauma_level=110; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='018';
cells(i).description{1}='pre+spont'; %spontaneous activity taken for at least 1 minute prior or post tone train
cells(i).filenum(2,:)='019';
cells(i).description{2}='pre+spont';
cells(i).filenum(3,:)='020';
cells(i).description{3}='post 2 min+spont';
cells(i).filenum(4,:)='021';
cells(i).description{4}='post 11 min+spont';
cells(i).filenum(5,:)='022';
cells(i).description{5}='post 21 min+spont';
cells(i).filenum(6,:)='023';
cells(i).description{6}='post 60 min+spont';
cells(i).filenum(7,:)='024';
cells(i).description{7}='post 90 min+spont';
cells(i).filenum(8,:)='025';
cells(i).description{8}='post 123 min+spont';
cells(i).filenum(9,:)='026';
cells(i).description{9}='post 151 min+spont';
% cells(i).filenum(10,:)='027';                  %%%missed soundcard trigger on event 374, TC looks crappy as a result
% cells(i).description{10}='post 187 min+spont';
cells(i).filenum(10,:)='028';
cells(i).description{10}='post 239 min+spont';

i=i+1;
cells(i).mode='mua/lfp';
cells(i).expdate='040209';
cells(i).session='001';
cells(i).depth=394; %micrometers
cells(i).CF=11700; %Hz
cells(i).trauma_freq=17000; %Hz
cells(i).trauma_level=110; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='007';
cells(i).description{1}='pre+spont'; %spontaneous activity taken for at least 1 minute prior or post tone train
cells(i).filenum(2,:)='008';
cells(i).description{2}='pre+spont';
cells(i).filenum(3,:)='009';
cells(i).description{3}='post 2 min+spont';
cells(i).filenum(4,:)='010';
cells(i).description{4}='post 12 min+spont';
cells(i).filenum(5,:)='011';
cells(i).description{5}='post 22 min+spont';
cells(i).filenum(6,:)='012';
cells(i).description{6}='post 60 min+spont';
cells(i).filenum(7,:)='013';
cells(i).description{7}='post 90 min+spont';
cells(i).filenum(8,:)='014';
cells(i).description{8}='post 120 min+spont';
cells(i).filenum(9,:)='015';
cells(i).description{9}='post 150 min+spont';
cells(i).filenum(10,:)='016';
cells(i).description{10}='post 180 min+spont';
cells(i).filenum(11,:)='017';
cells(i).description{11}='post 242 min+spont';
cells(i).filenum(12,:)='018'; % electrode was re-placed prior to this file
cells(i).description{12}='post 300 min+spont';
cells(i).filenum(13,:)='019';
cells(i).description{13}='post 361 min+spont';
cells(i).filenum(14,:)='020';
cells(i).description{14}='post 392 min+spont';

i=i+1;
cells(i).mode='mua/lfp'; %BEHAVORIAL ID:040910 no tinnitus
cells(i).expdate='041910';
cells(i).session='001';
cells(i).depth=363; %micrometers
cells(i).CF=16600; %Hz
cells(i).trauma_freq=11700; %Hz
cells(i).trauma_level=110; %dB
cells(i).trauma_dur=1; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='014';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='015';
cells(i).description{2}='pre';
cells(i).filenum(3,:)='017';
cells(i).description{3}='post 1 min';
cells(i).filenum(4,:)='018';
cells(i).description{4}='post 10 min';
cells(i).filenum(5,:)='019';
cells(i).description{5}='post 21 min';
cells(i).filenum(6,:)='020';
cells(i).description{6}='post 30 min';
cells(i).filenum(7,:)='021';
cells(i).description{7}='post 41 min';
cells(i).filenum(8,:)='022';
cells(i).description{8}='post 51 min';
cells(i).filenum(9,:)='023';
cells(i).description{9}='post 60 min';
cells(i).filenum(10,:)='024';
cells(i).description{10}='post 70 min';
cells(i).filenum(11,:)='025';
cells(i).description{11}='post 90 min';
cells(i).filenum(12,:)='026'; 
cells(i).description{12}='post 120 min';
cells(i).filenum(13,:)='027';
cells(i).description{13}='post 151 min';
cells(i).filenum(14,:)='028';
cells(i).description{14}='post 180 min';
cells(i).filenum(15,:)='029';
cells(i).description{15}='post 210 min';

i=i+1;
cells(i).mode='mua/lfp'; %ISO ANESTHESIA, BEHAVORIAL ID:043010 no tinnitus
cells(i).expdate='051410';
cells(i).session='002';
cells(i).depth=366; %micrometers
cells(i).CF=13900; %Hz
cells(i).trauma_freq=9829; %Hz
cells(i).trauma_level=113; %dB
cells(i).trauma_dur=2; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='001';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='002';
cells(i).description{2}='pre';
cells(i).filenum(3,:)='003';
cells(i).description{3}='spont act';
cells(i).filenum(4,:)='005';
cells(i).description{4}='post 3 min';
cells(i).filenum(5,:)='006';
cells(i).description{5}='spont act';
cells(i).filenum(6,:)='007';
cells(i).description{6}='post 14 min';
cells(i).filenum(7,:)='080';
cells(i).description{7}='spont act';
cells(i).filenum(8,:)='009';
cells(i).description{8}='post 25 min';
cells(i).filenum(9,:)='010';
cells(i).description{9}='spont act';
cells(i).filenum(10,:)='011';
cells(i).description{10}='post 35 min';
cells(i).filenum(11,:)='012';
cells(i).description{11}='spont act';
cells(i).filenum(12,:)='013'; 
cells(i).description{12}='post 46 min';
cells(i).filenum(13,:)='014';
cells(i).description{13}='spont act';
cells(i).filenum(14,:)='015';
cells(i).description{14}='post 60 min';
cells(i).filenum(15,:)='016';
cells(i).description{15}='spont act'; %animal died unexpectedly. Overdose on anesthesia? May
%explain decreased MU activity in files 013 and 015.

i=i+1;
cells(i).mode='mua/lfp'; %ISO ANESTHEIA, BEHAVORIAL ID:051910 no tinnitus
cells(i).expdate='052810';
cells(i).session='001';
cells(i).depth=309; %micrometers
cells(i).CF=19800; %Hz
cells(i).trauma_freq=14000; %Hz
cells(i).trauma_level=110; %dB
cells(i).trauma_dur=2; %minutes
cells(i).trauma_speaker='PO-55T'; %'PO-55T' or 'beyma'
cells(i).filenum(1,:)='020';
cells(i).description{1}='pre';
cells(i).filenum(2,:)='021';
cells(i).description{2}='pre';
cells(i).filenum(3,:)='022';
cells(i).description{3}='post 3 min';
cells(i).filenum(4,:)='023';
cells(i).description{4}='post 12 min';
cells(i).filenum(5,:)='024';
cells(i).description{5}='post 24 min';
cells(i).filenum(6,:)='025';
cells(i).description{6}='post 35 min';
cells(i).filenum(7,:)='026';
cells(i).description{7}='post 60 min';
cells(i).filenum(8,:)='027';
cells(i).description{8}='post 91 min';
cells(i).filenum(9,:)='029';
cells(i).description{9}='post 120 min'; %may have lost MU at this point, although TC looks similar.
cells(i).filenum(10,:)='030';
cells(i).description{10}='post 150 min';
cells(i).filenum(11,:)='031';
cells(i).description{11}='post 180 min';
cells(i).filenum(12,:)='032'; 
cells(i).description{12}='post 221 min';