function recordings=cell_list_ira_som_OE
% cell list for ira's SOM cell recordings with OpenEphys
% tonotopic gradient and tuning curve. y= yes, n= no, m= maybe
% **mode should be one of: 'lca', 'mua', 'lfp'
% **genotype indicates transgenic line of mouse
% **'NAN' indicates an unknown value
%You can leave CF as nan if you don't know it, or haven't looked at the
%tuning curve yet
%Format: each session represents a recording from one site or cell;
%no exceptions. 
%last update: 09-16-2013
%

%test
y='yes';
n='no';
m='maybe';
CB='channel blockers';
N='normal internal solution';
ut='untuned';
nr='not responsive';

%%
i=0;
i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='ChR'; %ChR2 or Arch
recordings(i).mouse_number=9; 
recordings(i).laser_intesity=25; %in mWT
recordings(i).expdate='062714';
recordings(i).session='002';
recordings(i).filenum='001';
recordings(i).OE_filename='18-42-46'
recordings(i).channels_rec=['4','8','27','31']; 
recordings(i).tetrodes_rec=['2','3'];
recordings(i).description='ILTC';
recordings(i).notes='issues with nonsequential stimids'; %
recordings(i).depth=3; %total number of turns
recordings(i).sound_evoked=1; % wrong low pass paramaters
recordings(i).tetrode(1,:).number='3';
recordings(i).tetrode(1,:).channel_ON='12'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number=1;
recordings(i).tetrode(1,:).cluster(1,:).quality=3;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=25.2;
recordings(i).tetrode(1,:).cluster(1,:).notes='poorly tuned, spiked a lot, completely silenced by blue laser';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='MClust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;


i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='ChR'; %ChR2 or Arch
recordings(i).mouse_number=8; 
recordings(i).laser_intesity=25; %in mWT
recordings(i).expdate='062714';
recordings(i).session='001';
recordings(i).filenum='001';
recordings(i).OE_filename='12-40-24'
recordings(i).channels_rec=['4','8','27','31']; 
recordings(i).tetrodes_rec=['1','2']; %2 is untuned
recordings(i).description='ILTC';
recordings(i).notes='possibly the same cell'; %
recordings(i).depth=3.25; %total number of turns
recordings(i).sound_evoked='y'; % 
recordings(i).tetrode(1,:).number='1';
recordings(i).tetrode(1,:).channel_ON='4'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number=1;
recordings(i).tetrode(1,:).cluster(1,:).quality=5;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(1,:).notes='well tuned, silenced by blue laser';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number=2;
recordings(i).tetrode(1,:).cluster(2,:).quality=5;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF=NaN;
recordings(i).tetrode(1,:).cluster(2,:).notes='well silenced';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='MClust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

% i=i+1;
% recordings(i).user='ira';
% recordings(i).rig='rig1';
% recordings(i).genotype='ChR'; %ChR2 or Arch
% recordings(i).mouse_number=8; 
% recordings(i).laser_intesity=NaN; %in mWT
% recordings(i).expdate='062614';
% recordings(i).session='001';
% recordings(i).filenum='002';
% recordings(i).OE_filename='16-00-35'
% recordings(i).channels_rec=['4','8','12','16','20','24','28','32']; 
% recordings(i).tetrodes_rec=['1','2'];
% recordings(i).description='ILTC';
% recordings(i).notes=''; %
% recordings(i).depth=NaN; %total number of turns
% recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
% recordings(i).tetrode(1,:).number='1';
% recordings(i).tetrode(1,:).channel_ON='4'; %which channel from the tetrode was recording LFPs?
% recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
% recordings(i).tetrode(1,:).cluster(1,:).number='2';
% recordings(i).tetrode(1,:).cluster(1,:).quality=4;
% recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
% recordings(i).tetrode(1,:).cluster(1,:).CF=13.6;
% recordings(i).tetrode(1,:).cluster(1,:).notes='';
% recordings(i).tetrode(1,:).cluster(1,:).extra='';
% recordings(i).tetrode(1,:).extra='';
% recordings(i).sorter='MClust';
% recordings(i).extra2=NaN;
% recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='ChR2'; %ChR2 or Arch
recordings(i).mouse_number=8; 
recordings(i).laser_intesity=25; %in mWT
recordings(i).expdate='062614';
recordings(i).session='001';
recordings(i).filenum='002';
recordings(i).OE_filename='16-00-35'
recordings(i).channels_rec=['4','8','12','16','20','24','28','32'];  
recordings(i).tetrodes_rec=['1','2']; %number 2 does not ahve cells on it
recordings(i).description='ILTC';
recordings(i).notes='great LFPs'; %
recordings(i).depth=2.75; %total number of turns
recordings(i).sound_evoked='y'; % 
recordings(i).tetrode(1,:).number='1';
recordings(i).tetrode(1,:).channel_ON='4'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number=2;
recordings(i).tetrode(1,:).cluster(1,:).quality=5;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(1,:).notes='not silenced by blue laser';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

% i=i+1;
% recordings(i).user='ira';
% recordings(i).rig='rig1';
% recordings(i).genotype='Arch'; %ChR2 or Arch
% recordings(i).mouse_number=7; 
% recordings(i).laser_intesity=NaN; %in mWT
% recordings(i).expdate='';
% recordings(i).session='';
% recordings(i).filenum='';
% recordings(i).OE_filename=''
% recordings(i).channels_rec=['','']; 
% recordings(i).tetrodes_rec=['',''];
% recordings(i).description='TC';
% recordings(i).notes=''; %
% recordings(i).depth=NaN; %total number of turns
% recordings(i).sound_evoked=NaN; %are there sound evoked responses in LFPs?
% recordings(i).tetrode(1,:).number='';
% recordings(i).tetrode(1,:).channel_ON=''; %which channel from the tetrode was recording LFPs?
% recordings(i).tetrode(1,:).num_tuned_cells=NaN; %how many total tuned cells are there?
% recordings(i).tetrode(1,:).cluster(1,:).number=;
% recordings(i).tetrode(1,:).cluster(1,:).quality=;
% recordings(i).tetrode(1,:).cluster(1,:).mode=; %single cell isolation or MUA?
% recordings(i).tetrode(1,:).cluster(1,:).CF=;
% recordings(i).tetrode(1,:).cluster(1,:).notes='';
% recordings(i).tetrode(1,:).cluster(1,:).extra='';
% recordings(i).tetrode(1,:).extra='';
% recordings(i).tetrode(2,:).number='';
% recordings(i).tetrode(2,:).num_tuned_cells=NaN; %how many total tuned cells are there?
% recordings(i).tetrode(2,:).cluster(1,:).number=;
% recordings(i).tetrode(2,:).cluster(1,:).quality=;
% recordings(i).tetrode(2,:).cluster(1,:).mode=; %single cell isolation or MUA?
% recordings(i).tetrode(2,:).cluster(1,:).CF=;
% recordings(i).tetrode(2,:).cluster(1,:).notes='';
% recordings(i).tetrode(2,:).cluster(1,:).extra='';
% recordings(i).tetrode(2,:).extra='';
% recordings(i).sorter=;
% recordings(i).extra2=NaN;
% recordings(i).extra3=NaN;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=7; 
recordings(i).laser_intesity=50; %in mWT
recordings(i).expdate='041014';
recordings(i).session='001';
recordings(i).filenum='003';
recordings(i).OE_filename='15-00-45'
recordings(i).channels_rec=['4','8','27','32']; 
recordings(i).tetrodes_rec=['1','2','7','8'];
recordings(i).description='ILTC';
recordings(i).notes='increase in FR'; %
recordings(i).depth=NaN; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='2';
recordings(i).tetrode(1,:).channel_ON='4'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=4;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(1,:).notes='increase in FR';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).tetrode(2,:).number='1';
recordings(i).tetrode(2,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(2,:).cluster(1,:).number='2';
recordings(i).tetrode(2,:).cluster(1,:).quality=4;
recordings(i).tetrode(2,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(2,:).cluster(1,:).CF='ut';
recordings(i).tetrode(2,:).cluster(1,:).notes='looks like sound responsive and increases FR';
recordings(i).tetrode(2,:).cluster(1,:).extra='';
recordings(i).tetrode(2,:).cluster(2,:).number='3';
recordings(i).tetrode(2,:).cluster(2,:).quality=4;
recordings(i).tetrode(2,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(2,:).cluster(2,:).CF=16.7;
recordings(i).tetrode(2,:).cluster(2,:).notes='responses decrease with laser';
recordings(i).tetrode(2,:).cluster(2,:).extra='';
recordings(i).tetrode(2,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='ChR2'; %ChR2 or Arch
recordings(i).mouse_number=5; 
recordings(i).laser_intesity=NaN; %in mWT
recordings(i).expdate='042814';
recordings(i).session='001';
recordings(i).filenum='003';
recordings(i).OE_filename='14-41-02'
recordings(i).channels_rec=['4','8','28','32']; 
recordings(i).tetrodes_rec=['7','8'];
recordings(i).description='ILNBN';
recordings(i).notes='great recording'; %
recordings(i).depth=NaN; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='8';
recordings(i).tetrode(1,:).channel_ON='32'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=4;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(1,:).notes='great sound evoked responses, no clear laser effect';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='ChR2'; %ChR2 or Arch
recordings(i).mouse_number=5; 
recordings(i).laser_intesity=NaN; %in mWT
recordings(i).expdate='042814';
recordings(i).session='001';
recordings(i).filenum='002';
recordings(i).OE_filename='14-10-55'
recordings(i).channels_rec=['4','8','28','32']; 
recordings(i).tetrodes_rec=['7','8'];
recordings(i).description='ILTC';
recordings(i).notes='SCT fixed'; %
recordings(i).depth=NaN; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='8';
recordings(i).tetrode(1,:).channel_ON='32'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=4;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(1,:).notes='great tuning';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='3';
recordings(i).tetrode(1,:).cluster(2,:).quality=3;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF='ut';
recordings(i).tetrode(1,:).cluster(2,:).notes='not an interesting cluster';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='ChR2'; %ChR2 or Arch
recordings(i).mouse_number=5; 
recordings(i).laser_intesity=47; %in mWT
recordings(i).expdate='051314';
recordings(i).session='001';
recordings(i).filenum='005';
recordings(i).OE_filename='12-44-45'
recordings(i).channels_rec=['3','8','28','32']; 
recordings(i).tetrodes_rec=['7','8'];
recordings(i).description='ILNBN';
recordings(i).notes='only null cluster had tuning'; %
recordings(i).depth=NaN; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='8';
recordings(i).tetrode(1,:).channel_ON='32'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='1';
recordings(i).tetrode(1,:).cluster(1,:).quality=3;
recordings(i).tetrode(1,:).cluster(1,:).mode='MUA'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(1,:).notes='just noise, does not correspond to null cluster';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='2';
recordings(i).tetrode(1,:).cluster(2,:).quality=3;
recordings(i).tetrode(1,:).cluster(2,:).mode='MUA'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF='ut';
recordings(i).tetrode(1,:).cluster(2,:).notes='some reduction in FR';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).cluster(3,:).number='3';
recordings(i).tetrode(1,:).cluster(3,:).quality=3;
recordings(i).tetrode(1,:).cluster(3,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(3,:).CF='ut';
recordings(i).tetrode(1,:).cluster(3,:).notes='some reduction in responsed to pure tone. probably does not correcpond to cell 3 in 003 file';
recordings(i).tetrode(1,:).cluster(3,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='ChR2'; %ChR2 or Arch
recordings(i).mouse_number=5; 
recordings(i).laser_intesity=47; %in mWT
recordings(i).expdate='051314';
recordings(i).session='001';
recordings(i).filenum='003';
recordings(i).OE_filename='12-02-31'
recordings(i).channels_rec=['3','8','28','32']; 
recordings(i).tetrodes_rec=['7','8'];
recordings(i).description='ILTC';
recordings(i).notes='none of the cells are tuned, only the null cluster'; %
recordings(i).depth=NaN; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='8';
recordings(i).tetrode(1,:).channel_ON='32'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='1';
recordings(i).tetrode(1,:).cluster(1,:).quality=3;
recordings(i).tetrode(1,:).cluster(1,:).mode='MUA'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(1,:).notes='blue laser did not silence responses, possible not a positive mouse';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='2';
recordings(i).tetrode(1,:).cluster(2,:).quality=3;
recordings(i).tetrode(1,:).cluster(2,:).mode='MUA'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF='ut';
recordings(i).tetrode(1,:).cluster(2,:).notes='blue laser did not silence responses, possible not a positive mouse';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).cluster(3,:).number='3';
recordings(i).tetrode(1,:).cluster(3,:).quality=3;
recordings(i).tetrode(1,:).cluster(3,:).mode='MUA'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(3,:).CF='ut';
recordings(i).tetrode(1,:).cluster(3,:).notes='blue laser did not silence responses, possible not a positive mouse';
recordings(i).tetrode(1,:).cluster(3,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=3; 
recordings(i).laser_intesity=55; %in mWT
recordings(i).expdate='051414';
recordings(i).session='001';
recordings(i).filenum='005';
recordings(i).OE_filename='13-54-41'
recordings(i).channels_rec=['4','8','12','16','20','24','28','32']; 
recordings(i).tetrodes_rec=['3','5'];
recordings(i).description='ILNBN';
recordings(i).notes='cluster 2 is a well tuned cell'; %
recordings(i).depth=NaN; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='3';
recordings(i).tetrode(1,:).channel_ON='12'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=4;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=11.1;
recordings(i).tetrode(1,:).cluster(1,:).notes='looks like increase response to WN';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=3; 
recordings(i).laser_intesity=55; %in mWT
recordings(i).expdate='051414';
recordings(i).session='001';
recordings(i).filenum='006';
recordings(i).OE_filename='18-27-29'
recordings(i).channels_rec=['4','8','12','16','20','24','28','32']; 
recordings(i).tetrodes_rec=['3','5'];
recordings(i).description='ILTC';
recordings(i).notes='cluster 2 is a well tuned cell'; %
recordings(i).depth=NaN; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='3';
recordings(i).tetrode(1,:).channel_ON='12'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=4;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=11.1;
recordings(i).tetrode(1,:).cluster(1,:).notes='high FR, well tuned';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='3';
recordings(i).tetrode(1,:).cluster(2,:).quality=3;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF='ut';
recordings(i).tetrode(1,:).cluster(2,:).notes='high FR, well tuned';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=6; 
recordings(i).laser_intesity=55; %in mWT
recordings(i).expdate='051514';
recordings(i).session='002';
recordings(i).filenum='004';
recordings(i).OE_filename='14-25-06'
recordings(i).channels_rec=['4','8','28','32']; 
recordings(i).tetrodes_rec=['2','7'];
recordings(i).description='ILNBN';
recordings(i).notes='no laser effect'; %
recordings(i).depth=1; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='2';
recordings(i).tetrode(1,:).channel_ON='8'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=2; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='1';
recordings(i).tetrode(1,:).cluster(1,:).quality=3;
recordings(i).tetrode(1,:).cluster(1,:).mode='MUA'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=20.5;
recordings(i).tetrode(1,:).cluster(1,:).notes='shows slight increase in FR';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='2';
recordings(i).tetrode(1,:).cluster(2,:).quality=4;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF='ut';
recordings(i).tetrode(1,:).cluster(2,:).notes='some responses to tones';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).cluster(3,:).number='3';
recordings(i).tetrode(1,:).cluster(3,:).quality=4;
recordings(i).tetrode(1,:).cluster(3,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(3,:).CF='ut';
recordings(i).tetrode(1,:).cluster(3,:).notes='some responses to tones';
recordings(i).tetrode(1,:).cluster(3,:).extra='';
recordings(i).tetrode(1,:).cluster(4,:).number='4';
recordings(i).tetrode(1,:).cluster(4,:).quality=4;
recordings(i).tetrode(1,:).cluster(4,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(4,:).CF='20.5';
recordings(i).tetrode(1,:).cluster(4,:).notes='no laser effects';
recordings(i).tetrode(1,:).cluster(4,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=6; 
recordings(i).laser_intesity=55; %in mWT
recordings(i).expdate='051514';
recordings(i).session='002';
recordings(i).filenum='001';
recordings(i).OE_filename='11-25-14'
recordings(i).channels_rec=['4','8','28','32']; 
recordings(i).tetrodes_rec=['2','7'];
recordings(i).description='ILTC';
recordings(i).notes='tuned null cluster, unusual waveforms, not sure if some of the clusters are noise'; %
recordings(i).depth=1; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='2';
recordings(i).tetrode(1,:).channel_ON='8'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=2; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='1';
recordings(i).tetrode(1,:).cluster(1,:).quality=3;
recordings(i).tetrode(1,:).cluster(1,:).mode='MUA'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=20.5;
recordings(i).tetrode(1,:).cluster(1,:).notes='this is a null cluster that is really well tuned';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='2';
recordings(i).tetrode(1,:).cluster(2,:).quality=3;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF='ut';
recordings(i).tetrode(1,:).cluster(2,:).notes='shows a little bit of tuning, could be from other clusters fired a lot';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).cluster(3,:).number='3';
recordings(i).tetrode(1,:).cluster(3,:).quality=4;
recordings(i).tetrode(1,:).cluster(3,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(3,:).CF='ut';
recordings(i).tetrode(1,:).cluster(3,:).notes='shows a little bit of tuning, could be from other clusters fired a lot';
recordings(i).tetrode(1,:).cluster(3,:).extra='';
recordings(i).tetrode(1,:).cluster(3,:).number='4';
recordings(i).tetrode(1,:).cluster(3,:).quality=5;
recordings(i).tetrode(1,:).cluster(3,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(3,:).CF='20.5';
recordings(i).tetrode(1,:).cluster(3,:).notes='well tuned, effects of laser are unclear';
recordings(i).tetrode(1,:).cluster(3,:).extra='';
recordings(i).tetrode(1,:).cluster(3,:).number='4';
recordings(i).tetrode(1,:).cluster(3,:).quality=3;
recordings(i).tetrode(1,:).cluster(3,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(3,:).CF='ut';
recordings(i).tetrode(1,:).cluster(3,:).notes='looks like noise, strong WN response';
recordings(i).tetrode(1,:).cluster(3,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=7; 
recordings(i).laser_intesity=55; %in mWT
recordings(i).expdate='051914';
recordings(i).session='001';
recordings(i).filenum='003';
recordings(i).OE_filename='13-06-53';
recordings(i).channels_rec=['4','8','27','31']; 
recordings(i).tetrodes_rec=['1','7','8'];
recordings(i).description='ILNBN';
recordings(i).notes='null cluster has robust responses to WN'; %
recordings(i).depth=1; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='1';
recordings(i).tetrode(1,:).channel_ON='4'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=5;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=11.1;
recordings(i).tetrode(1,:).cluster(1,:).notes='does not respond well to pure tone,';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(1,:).number='3';
recordings(i).tetrode(1,:).cluster(1,:).quality=4;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=9.1;
recordings(i).tetrode(1,:).cluster(1,:).notes='short response to tones, unclear laser effects';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=7; 
recordings(i).laser_intesity=55; %in mWT
recordings(i).expdate='051914';
recordings(i).session='001';
recordings(i).filenum='001';
recordings(i).OE_filename='11-45-48'
recordings(i).channels_rec=['4','8','12','16','20','24','28','32']; 
recordings(i).tetrodes_rec=['1','2','7','8'];
recordings(i).description='TC';
recordings(i).notes='no laser, mouse7, lots of spontaneous activity'; %
recordings(i).depth=1; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='1';
recordings(i).tetrode(1,:).channel_ON='4'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=2; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=2;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=9.1;
recordings(i).tetrode(1,:).cluster(1,:).notes='robust responses only to one tone and WN';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='3';
recordings(i).tetrode(1,:).cluster(2,:).quality=5;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF=11.1;
recordings(i).tetrode(1,:).cluster(2,:).notes='left-sided TC';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=6; 
recordings(i).laser_intesity=55; %in mWT
recordings(i).expdate='051914';
recordings(i).session='001';
recordings(i).filenum='008';
recordings(i).OE_filename='17-27-33';
recordings(i).channels_rec=['4','8','27','31']; 
recordings(i).tetrodes_rec=['1','2','7','8'];
recordings(i).description='ILNBN';
recordings(i).notes='strong response to tones but not to WN'; %
recordings(i).depth=NaN; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='7';
recordings(i).tetrode(1,:).channel_ON='27'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=4;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=11.1;
recordings(i).tetrode(1,:).cluster(1,:).notes='silenced by green laser, responds to tones more';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=6; 
recordings(i).laser_intesity=55; %in mWT
recordings(i).expdate='051914';
recordings(i).session='001';
recordings(i).filenum='007';
recordings(i).OE_filename='16-44-27';
recordings(i).channels_rec=['4','8','27','31']; 
recordings(i).tetrodes_rec=['1','2','7','8'];
recordings(i).description='ILTC';
recordings(i).notes='mouse 6 some arch, interesting effects'; %
recordings(i).depth=NaN; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='7';
recordings(i).tetrode(1,:).channel_ON='27'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=2; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=4;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=11.1;
recordings(i).tetrode(1,:).cluster(1,:).notes='high spontaneous firing, silenced by laser, might be a SOM cell ';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='3';
recordings(i).tetrode(1,:).cluster(2,:).quality=4;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF=9.1;
recordings(i).tetrode(1,:).cluster(2,:).notes='no effect of laser, sparse firing';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=6; 
recordings(i).laser_intesity=NaN; %in mWT
recordings(i).expdate='052214';
recordings(i).session='002';
recordings(i).filenum='001';
recordings(i).OE_filename='14-48-03'
recordings(i).channels_rec=['4','8','28','32']; 
recordings(i).tetrodes_rec=['2','7'];
recordings(i).description='ILTC';
recordings(i).notes='recorded tetrode 1 but could not process, SCT fixed'; %
recordings(i).depth=NaN; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='2';
recordings(i).tetrode(1,:).channel_ON='8'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='1';
recordings(i).tetrode(1,:).cluster(1,:).quality=3;
recordings(i).tetrode(1,:).cluster(1,:).mode='MUA'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=20.5;
recordings(i).tetrode(1,:).cluster(1,:).notes='null cluster has clear tuning, used a channel for reference, some effects of green laser';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='2';
recordings(i).tetrode(1,:).cluster(2,:).quality=3;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF='ut';
recordings(i).tetrode(1,:).cluster(2,:).notes='no effect';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).cluster(3,:).number='3';
recordings(i).tetrode(1,:).cluster(3,:).quality=5;
recordings(i).tetrode(1,:).cluster(3,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(3,:).CF='ut';
recordings(i).tetrode(1,:).cluster(3,:).notes='unclear tuning, no effect';
recordings(i).tetrode(1,:).cluster(3,:).extra='';
recordings(i).tetrode(1,:).cluster(4,:).number='4';
recordings(i).tetrode(1,:).cluster(4,:).quality=3;
recordings(i).tetrode(1,:).cluster(4,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(4,:).CF='ut';
recordings(i).tetrode(1,:).cluster(4,:).notes='unclear tuning, no effect';
recordings(i).tetrode(1,:).cluster(4,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).tetrode(2,:).number='7';
recordings(i).tetrode(2,:).num_tuned_cells=0; %how many total tuned cells are there?
recordings(i).tetrode(2,:).cluster(1,:).number='2';
recordings(i).tetrode(2,:).cluster(1,:).quality=4;
recordings(i).tetrode(2,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(2,:).cluster(1,:).CF='ut';
recordings(i).tetrode(2,:).cluster(1,:).notes='silenced by green laser only, looks like might be a SOM cell';
recordings(i).tetrode(2,:).cluster(1,:).extra='';
recordings(i).tetrode(2,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=7; 
recordings(i).laser_intesity=66; %in mWT
recordings(i).expdate='052714';
recordings(i).session='001';
recordings(i).filenum='003';
recordings(i).OE_filename='18-53-33'
recordings(i).channels_rec=['4','8','27','31']; 
recordings(i).tetrodes_rec=['1','2','7','8'];
recordings(i).description='ILNBN';
recordings(i).notes='not a srong response to tone but very robust response to WN. could not see cell 3 anymore, 4,5.7, and 8 kHz'; %
recordings(i).depth=2; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='1';
recordings(i).tetrode(1,:).channel_ON='4'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='1';
recordings(i).tetrode(1,:).cluster(1,:).quality=5;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=7.4;
recordings(i).tetrode(1,:).cluster(1,:).notes='not traditional TC, strong responses to WN';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).tetrode(2,:).number='2';
recordings(i).tetrode(2,:).num_tuned_cells=0; %how many total tuned cells are there?
recordings(i).tetrode(2,:).cluster(1,:).number='2';
recordings(i).tetrode(2,:).cluster(1,:).quality=4;
recordings(i).tetrode(2,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(2,:).cluster(1,:).CF='ut';
recordings(i).tetrode(2,:).cluster(1,:).notes='weak responses to tone';
recordings(i).tetrode(2,:).cluster(1,:).extra='';
recordings(i).tetrode(2,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;


i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=7; 
recordings(i).laser_intesity=66; %in mWT
recordings(i).expdate='052714';
recordings(i).session='001';
recordings(i).filenum='002';
recordings(i).OE_filename='14-54-19'
recordings(i).channels_rec=['4','8','27','31']; 
recordings(i).tetrodes_rec=['1','2','7','8'];
recordings(i).description='ILTC';
recordings(i).notes='only tetrode 1 shows some tuning'; %
recordings(i).depth=2; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='1';
recordings(i).tetrode(1,:).channel_ON='4'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=5;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=7.4;
recordings(i).tetrode(1,:).cluster(1,:).notes='not a clear tuning';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).tetrode(2,:).number='2';
recordings(i).tetrode(2,:).num_tuned_cells=0; %how many total tuned cells are there?
recordings(i).tetrode(2,:).cluster(1,:).number='2';
recordings(i).tetrode(2,:).cluster(1,:).quality=5;
recordings(i).tetrode(2,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(2,:).cluster(1,:).CF='ut';
recordings(i).tetrode(2,:).cluster(1,:).notes='untuned, sparse firing, some reduction in FR';
recordings(i).tetrode(2,:).cluster(1,:).extra='';
recordings(i).tetrode(2,:).cluster(2,:).number='3';
recordings(i).tetrode(2,:).cluster(2,:).quality=2;
recordings(i).tetrode(2,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(2,:).cluster(2,:).CF='ut';
recordings(i).tetrode(2,:).cluster(2,:).notes='untuned, sparse firing, some reduction in FR';
recordings(i).tetrode(2,:).cluster(2,:).extra='';
recordings(i).tetrode(2,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='ChR2'; %ChR2 or Arch
recordings(i).mouse_number=8; 
recordings(i).laser_intesity=40; %in mWT
recordings(i).expdate='061614';
recordings(i).session='001';
recordings(i).filenum='002';
recordings(i).OE_filename='22-28-14';
recordings(i).channels_rec=['4','8','27','31'];
recordings(i).tetrodes_rec=['1','2'];
recordings(i).description='ILNBN';
recordings(i).notes='mostly silenced by blue laser, 16.7'; %
recordings(i).depth=2; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='2';
recordings(i).tetrode(1,:).channel_ON=''; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=NaN; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=3;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(1,:).notes='';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='3';
recordings(i).tetrode(1,:).cluster(2,:).quality=2;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF='ut';
recordings(i).tetrode(1,:).cluster(2,:).notes='responsed to sound';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).cluster(3,:).number='4';
recordings(i).tetrode(1,:).cluster(3,:).quality=2;
recordings(i).tetrode(1,:).cluster(3,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(3,:).CF=16.7;
recordings(i).tetrode(1,:).cluster(3,:).notes='well silenced by laser';
recordings(i).tetrode(1,:).cluster(3,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='ChR2'; %ChR2 or Arch
recordings(i).mouse_number=8; 
recordings(i).laser_intesity=40; %in mWT
recordings(i).expdate='061614';
recordings(i).session='001';
recordings(i).filenum='001';
recordings(i).OE_filename='19-55-16';
recordings(i).channels_rec=['4','8','27','31']; 
recordings(i).tetrodes_rec=['1','2'];
recordings(i).description='ILTC';
recordings(i).notes='cells overlap, 2 and 3 could be the same cell'; %
recordings(i).depth=2; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='2';
recordings(i).tetrode(1,:).channel_ON='8'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=2; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=3;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(1,:).notes='not silenced but visible reduction in spontaneous activity';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='3';
recordings(i).tetrode(1,:).cluster(2,:).quality=2;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF='ut';
recordings(i).tetrode(1,:).cluster(2,:).notes='visible reduction in spontaneous activity, looks like tuned cell with laser';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).cluster(3,:).number='4';
recordings(i).tetrode(1,:).cluster(3,:).quality=2;
recordings(i).tetrode(1,:).cluster(3,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(3,:).CF=16.7;
recordings(i).tetrode(1,:).cluster(3,:).notes='visible reduction in spontaneous activity';
recordings(i).tetrode(1,:).cluster(3,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=5; 
recordings(i).laser_intesity=20; %in mWT
recordings(i).expdate='061714';
recordings(i).session='001';
recordings(i).filenum='002';
recordings(i).OE_filename='17-17-19'
recordings(i).channels_rec=['4','8','27','31']; 
recordings(i).tetrodes_rec=['2'];
recordings(i).description='ILTC';
recordings(i).notes='RLF, did not look at tuning'; %
recordings(i).depth=2.5; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='2';
recordings(i).tetrode(1,:).channel_ON='8'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=NaN; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=3;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=NaN;
recordings(i).tetrode(1,:).cluster(1,:).notes='did not measure tuning, no clear laser effect on WN';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=7; 
recordings(i).laser_intesity=50; %in mWT
recordings(i).expdate='061714';
recordings(i).session='002';
recordings(i).filenum='001';
recordings(i).OE_filename='18-59-13'
recordings(i).channels_rec=['4','8','27','31']; 
recordings(i).tetrodes_rec=['1','2','7','8'];
recordings(i).description='ILTC';
recordings(i).notes='shallow lfp tuning curves, untuned cells, not sure if still in Auditory area'; %
recordings(i).depth=3; %total number of turns
recordings(i).sound_evoked='y'; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='1';
recordings(i).tetrode(1,:).channel_ON='4'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=0; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=2;
recordings(i).tetrode(1,:).cluster(1,:).mode='MUA'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF='ut';
recordings(i).tetrode(1,:).cluster(1,:).notes='untuned, no effect';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='3';
recordings(i).tetrode(1,:).cluster(2,:).quality=2;
recordings(i).tetrode(1,:).cluster(2,:).mode='MUA'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF='ut';
recordings(i).tetrode(1,:).cluster(2,:).notes='no effect';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).cluster(3,:).number='4';
recordings(i).tetrode(1,:).cluster(3,:).quality=2;
recordings(i).tetrode(1,:).cluster(3,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(3,:).CF='ut';
recordings(i).tetrode(1,:).cluster(3,:).notes='no affect';
recordings(i).tetrode(1,:).cluster(3,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).tetrode(2,:).number='7';
recordings(i).tetrode(2,:).channel_ON='27'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(2,:).num_tuned_cells=0; %how many total tuned cells are there?
recordings(i).tetrode(2,:).cluster(1,:).number='2';
recordings(i).tetrode(2,:).cluster(1,:).quality=2;
recordings(i).tetrode(2,:).cluster(1,:).mode='MUA'; %single cell isolation or MUA?
recordings(i).tetrode(2,:).cluster(1,:).CF='ut';
recordings(i).tetrode(2,:).cluster(1,:).notes='untuned, about 30% reduction in FR';
recordings(i).tetrode(2,:).cluster(1,:).extra='';
recordings(i).tetrode(2,:).cluster(2,:).number='3';
recordings(i).tetrode(2,:).cluster(2,:).quality=2;
recordings(i).tetrode(2,:).cluster(2,:).mode='MUA'; %single cell isolation or MUA?
recordings(i).tetrode(2,:).cluster(2,:).CF='ut';
recordings(i).tetrode(2,:).cluster(2,:).notes='no effect';
recordings(i).tetrode(2,:).cluster(2,:).extra='';
recordings(i).tetrode(2,:).cluster(3,:).number='4';
recordings(i).tetrode(2,:).cluster(3,:).quality=2;
recordings(i).tetrode(2,:).cluster(3,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(2,:).cluster(3,:).CF='ut';
recordings(i).tetrode(2,:).cluster(3,:).notes='stops firing during laser and sound';
recordings(i).tetrode(2,:).cluster(3,:).extra='';
recordings(i).tetrode(2,:).extra='';
recordings(i).tetrode(3,:).number='8';
recordings(i).tetrode(3,:).channel_ON='32'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(3,:).num_tuned_cells=0; %how many total tuned cells are there?
recordings(i).tetrode(3,:).cluster(1,:).number='2';
recordings(i).tetrode(3,:).cluster(1,:).quality=3;
recordings(i).tetrode(3,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(3,:).cluster(1,:).CF='ut';
recordings(i).tetrode(3,:).cluster(1,:).notes='no effect';
recordings(i).tetrode(3,:).cluster(1,:).extra='';
recordings(i).tetrode(3,:).cluster(2,:).number='3';
recordings(i).tetrode(3,:).cluster(2,:).quality=3;
recordings(i).tetrode(3,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(3,:).cluster(2,:).CF='ut';
recordings(i).tetrode(3,:).cluster(2,:).notes='stops firing during laser and sound';
recordings(i).tetrode(3,:).cluster(2,:).extra='';
recordings(i).tetrode(3,:).cluster(3,:).number='4';
recordings(i).tetrode(3,:).cluster(3,:).quality=2;
recordings(i).tetrode(3,:).cluster(3,:).mode='MUA'; %single cell isolation or MUA?
recordings(i).tetrode(3,:).cluster(3,:).CF='ut';
recordings(i).tetrode(3,:).cluster(3,:).notes='stops firing during laser and sound'
recordings(i).tetrode(3,:).cluster(3,:).extra='';
recordings(i).tetrode(3,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=6; 
recordings(i).laser_intesity=50; %in mWT
recordings(i).expdate='061814';
recordings(i).session='001';
recordings(i).filenum='004';
recordings(i).OE_filename='17-28-51'
recordings(i).channels_rec=['4','8','12','16','20','24','28','32'];  
recordings(i).tetrodes_rec=['1','2'];
recordings(i).description='ILNBN';
recordings(i).notes='stimulus repeated from 002 unclear effects, 13.6 tone'; %
recordings(i).depth=3; %total number of turns
recordings(i).sound_evoked='y'; %LFPs have laser artifects in them
recordings(i).tetrode(1,:).number='2';
recordings(i).tetrode(1,:).channel_ON='8'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=2; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=3;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=11.1;
recordings(i).tetrode(1,:).cluster(1,:).notes='well tuned';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='3';
recordings(i).tetrode(1,:).cluster(2,:).quality=3;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(2,:).notes='well tuned';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=6; 
recordings(i).laser_intesity=50; %in mWT
recordings(i).expdate='061814';
recordings(i).session='001';
recordings(i).filenum='003';
recordings(i).OE_filename='17-09-17'
recordings(i).channels_rec=['4','8','12','16','20','24','28','32'];  
recordings(i).tetrodes_rec=['1','2'];
recordings(i).description='ILNBN';
recordings(i).notes='stimulus repeated from 002 unclear effects, 13.6 tone'; %
recordings(i).depth=3; %total number of turns
recordings(i).sound_evoked='y'; %LFPs have laser artifects in them
recordings(i).tetrode(1,:).number='2';
recordings(i).tetrode(1,:).channel_ON='8'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=2; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=3;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=11.1;
recordings(i).tetrode(1,:).cluster(1,:).notes='well tuned';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='3';
recordings(i).tetrode(1,:).cluster(2,:).quality=3;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(2,:).notes='well tuned';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=6; 
recordings(i).laser_intesity=50; %in mWT
recordings(i).expdate='061814';
recordings(i).session='001';
recordings(i).filenum='002';
recordings(i).OE_filename='16-49-03'
recordings(i).channels_rec=['4','8','12','16','20','24','28','32'];  
recordings(i).tetrodes_rec=['1','2'];
recordings(i).description='ILNBN';
recordings(i).notes='unclear effects, 13.6 tone'; %
recordings(i).depth=3; %total number of turns
recordings(i).sound_evoked='y'; %LFPs have laser artifects in them
recordings(i).tetrode(1,:).number='2';
recordings(i).tetrode(1,:).channel_ON='8'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=2; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=3;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=11.1;
recordings(i).tetrode(1,:).cluster(1,:).notes='well tuned';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='3';
recordings(i).tetrode(1,:).cluster(2,:).quality=3;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(2,:).notes='well tuned';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=6; 
recordings(i).laser_intesity=50; %in mWT
recordings(i).expdate='061814';
recordings(i).session='001';
recordings(i).filenum='001';
recordings(i).OE_filename='16-11-11'
recordings(i).channels_rec=['4','8','12','16','20','24','28','32'];  
recordings(i).tetrodes_rec=['1','2'];
recordings(i).description='ILTC';
recordings(i).notes='well tuned cells, minimal effect of grean laser'; %
recordings(i).depth=3; %total number of turns
recordings(i).sound_evoked='y'; %LFPs have laser artifects in them
recordings(i).tetrode(1,:).number='2';
recordings(i).tetrode(1,:).channel_ON='8'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=2; %how many total tuned cells are there?
recordings(i).tetrode(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=3;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=11.1;
recordings(i).tetrode(1,:).cluster(1,:).notes='well tuned';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(2,:).number='3';
recordings(i).tetrode(1,:).cluster(2,:).quality=3;
recordings(i).tetrode(1,:).cluster(2,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(2,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(2,:).notes='well tuned';
recordings(i).tetrode(1,:).cluster(2,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='ChR2'; %ChR2 or Arch
recordings(i).mouse_number=10; 
recordings(i).laser_intesity=25; %in mWT
recordings(i).expdate='062614';
recordings(i).session='001';
recordings(i).filenum='001';
recordings(i).OE_filename='13-20-24'
recordings(i).channels_rec=['4','8','12','16','20','24','28','32'];
recordings(i).tetrodes_rec=['2','3'];
recordings(i).description='ILTC';
recordings(i).notes='cells are poorly tuned but well silenced by laser'; %
recordings(i).depth=.75; %total number of turns
recordings(i).sound_evoked=NaN; %LFPs are not filtered
recordings(i).tetrode(1,:).number='3';
recordings(i).tetrode(1,:).channel_ON='12'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=0; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=5;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=20; %poorly tuned
recordings(i).tetrode(1,:).cluster(1,:).notes='pooorly tuned';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).cluster(1,:).number='3';
recordings(i).tetrode(1,:).cluster(1,:).quality=2;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=NaN; %
recordings(i).tetrode(1,:).cluster(1,:).notes='untuned, silenced';
recordings(i).tetrode(1,:).cluster(1,:).extra='';
recordings(i).tetrode(1,:).extra='';
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=7; 
recordings(i).laser_intesity=NaN; %in mWT
recordings(i).expdate='052614';
recordings(i).session='002';
recordings(i).filenum='001';
recordings(i).OE_filename='16-07-10'
recordings(i).channels_rec=['4','8','27','31','37']; 
recordings(i).tetrodes_rec=['1','2','7','8'];%7 and 8 are untuned
recordings(i).description='TC'; % no laser
recordings(i).notes='calibrated speaker, warning stim turned on and off at the ame time, check stimIds';
recordings(i).depth=2; %total number of turns
recordings(i).sound_evoked=y; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='1';
recordings(i).tetrode(1,:).channel_ON='4'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='2';
recordings(i).tetrode(1,:).cluster(1,:).quality=5;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=13.6;
recordings(i).tetrode(1,:).cluster(1,:).notes='could be broken into 2 cells, but tuning was similar so i combined';
recordings(i).tetrode(1,:).cluster(1,:).extra=NaN;
recordings(i).tetrode(1,:).extra(1,:)=NaN;
recordings(i).tetrode(2,:).number='2';
recordings(i).tetrode(2,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(2,:).cluster(1,:).number='2';
recordings(i).tetrode(2,:).cluster(1,:).quality=4;
recordings(i).tetrode(2,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(2,:).cluster(1,:).CF=4.9;
recordings(i).tetrode(2,:).cluster(1,:).notes='left-lobed tuning curve';
recordings(i).tetrode(2,:).cluster(1,:).extra=NaN;
recordings(i).tetrode(2,:).extra(2,:)=NaN;
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=7; 
recordings(i).laser_intesity=66.7; %in mWT
recordings(i).expdate='052714';
recordings(i).session='001';
recordings(i).filenum='002';
recordings(i).OE_filename=''
recordings(i).channels_rec=['4','8','27','31','37']; 
recordings(i).tetrodes_rec=['1','2','7','8'];% 2, 7, 8 are untuned
recordings(i).description='ILTC'; % laser
recordings(i).notes='';
recordings(i).depth=2; %total number of turns
recordings(i).sound_evoked=y; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='1';
recordings(i).tetrode(1,:).channel_ON='4'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number=2;
recordings(i).tetrode(1,:).cluster(1,:).quality=5;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=7.5;
recordings(i).tetrode(1,:).cluster(1,:).notes='strange tuning, stong WN responses';
recordings(i).tetrode(1,:).cluster(1,:).extra=NaN;
recordings(i).tetrode(1,:).extra(1,:)=NaN;
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='Arch'; %ChR2 or Arch
recordings(i).mouse_number=7; 
recordings(i).laser_intesity=66.7; %in mWT
recordings(i).expdate='052714';
recordings(i).session='001';
recordings(i).filenum='003';
recordings(i).OE_filename=''
recordings(i).channels_rec=['4','8','27','31','37']; 
recordings(i).tetrodes_rec=['1','2','7','8'];% 2, 7, 8 are untuned
recordings(i).description='ILNBN'; % laser, 4 and 8 kHz
recordings(i).notes='since TC was strage, playing 4 and 8 kHz';
recordings(i).depth=2; %total number of turns
recordings(i).sound_evoked=y; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='1';
recordings(i).tetrode(1,:).channel_ON='4'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number=1;
recordings(i).tetrode(1,:).cluster(1,:).quality=5;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=7.5;
recordings(i).tetrode(1,:).cluster(1,:).notes='strange tuning, stong WN responses';
recordings(i).tetrode(1,:).cluster(1,:).extra=NaN;
recordings(i).tetrode(1,:).extra(1,:)=NaN;
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;

i=i+1;
recordings(i).user='ira';
recordings(i).rig='rig1';
recordings(i).genotype='ChR2'; %ChR2 or Arch
recordings(i).mouse_number=7; 
recordings(i).laser_intesity=47; %in mWT
recordings(i).expdate='042814';
recordings(i).session='001';
recordings(i).filenum='002';
recordings(i).OE_filename=''
recordings(i).channels_rec=['4','8','28','32']; 
recordings(i).tetrodes_rec=['7','8'];% 
recordings(i).description='ILTC'; % 
recordings(i).notes='looks like i referenced, so all spikes are neural';
recordings(i).depth=1.5; %total number of turns
recordings(i).sound_evoked=y; %are there sound evoked responses in LFPs?
recordings(i).tetrode(1,:).number='7';
recordings(i).tetrode(1,:).channel_ON='28'; %which channel from the tetrode was recording LFPs?
recordings(i).tetrode(1,:).num_tuned_cells=1; %how many total tuned cells are there?
recordings(i).tetrode(1,:).cluster(1,:).number='1';
recordings(i).tetrode(1,:).cluster(1,:).quality=5;
recordings(i).tetrode(1,:).cluster(1,:).mode='SU'; %single cell isolation or MUA?
recordings(i).tetrode(1,:).cluster(1,:).CF=7.5;
recordings(i).tetrode(1,:).cluster(1,:).notes='strange tuning, stong WN responses';
recordings(i).tetrode(1,:).cluster(1,:).extra=NaN;
recordings(i).tetrode(1,:).extra(1,:)=NaN;
recordings(i).sorter='simpleclust';
recordings(i).extra2=NaN;
recordings(i).extra3=NaN;




