function cells=cell_list_ira
% cell list for ira's speech noise project.
% **"A1" refers to whether recording was taken from A1, as estabilished by
% tonotopic gradient and tuning curve. y= yes, n= no, m= maybe
% **mode should be one of: 'i=0', 'vclamp', 'iclamp', 'lca', 'mua', 'lfp'
% **iext indicates the current injected in 'iclamp' mode. If iext line does
% not exist for a data file, assume iext=0
% ** USE field indicates whether the file was used for analysis or not. All
% i=0 and vc files are either y or n, mua files are m.
% **'NAN' indicates an unknown value
%You can leave CF as nan if you don't know it, or haven't looked at the
%tuning curve yet
%Format: each session represents a recording from one site or cell;
%exceptions are sessions "001" that contain different mapping sites. 
%
%last update: 02.18.14
%

y='yes';
n='no';
m='maybe';
K='normal internal solution';

i=0;

% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='120812';
% cells(i).session='004';
% cells(i).depth=nan; %micrometers
% cells(i).internalSolution='K';
% cells(i).A1=y;
% cells(i).CF=nan; %Hz
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV
% cells(i).filenum(1,:)='001';%spiking a lot, couldnt hold VC, N
% cells(i).description{1}='1-64';
% cells(i).mode{1}='vclamp';
% cells(i).use{1}='n';
% cells(i).filenum(2,:)='003';
% cells(i).description{2}='1-64'; %spiking a lot, lost at this point, N
% cells(i).mode{2}='i=0';
% cells(i).use{2}='n';
% cells(i).filenum(3,:)='002'; %spiking a lot, bad quality, N
% cells(i).description{3}='4-8;8-16;16-32'; %
% cells(i).mode{3}='vclamp';
% cells(i).use{3}='n';



% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='121412';
% cells(i).session='004';
% cells(i).depth=272; %micrometers
% cells(i).internalSolution='Cs/QX';
% cells(i).A1=y;
% cells(i).CF=nan; %Hz
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; 
% cells(i).filenum(1,:)='001'; %CB, outward currents deteriorated, part of the data might be usedful
% cells(i).description{1}='1-64';
% cells(i).mode{1}='vclamp';
% cells(i).use{1}='n';

% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='121412';
% cells(i).session='006';
% cells(i).depth=208; %micrometers
% cells(i).internalSolution='Cs/QX';
% cells(i).A1=y;
% cells(i).CF=27000; %Hz
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV 
% cells(i).filenum(1,:)='001'; %CB, bad recording!!!
% cells(i).description{1}='1-64';
% cells(i).mode{1}='vclamp';
% cells(i).use{1}='n';
% cells(i).filenum(2,:)='002';
% cells(i).description{2}='TC'; %CB, 27000
% cells(i).mode{2}='i=0';
% cells(i).use{2}='n';

% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='121812';
% cells(i).session='001';
% cells(i).depth=371; %micrometers
% cells(i).internalSolution='nan';
% cells(i).A1=y;
% cells(i).CF=16800; %Hz
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV 
% cells(i).filenum(1,:)='001'; % broadly tuned, consistent responses
% cells(i).description{1}='TC';
% cells(i).mode{1}='mua';
% cells(i).use{1}='m';

% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='121812';
% cells(i).session='001';
% cells(i).depth=371; %micrometers
% cells(i).internalSolution='nan';
% cells(i).A1=y;
% cells(i).CF=19900; %Hz
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV 
% cells(i).filenum(1,:)='002'; % broadly tuned, consistent responses
% cells(i).description{1}='TC';
% cells(i).mode{1}='mua';
% cells(i).use{1}='m';

% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='121812';
% cells(i).session='001';
% cells(i).depth=412; %micrometers
% cells(i).internalSolution='nan';
% cells(i).A1=y;
% cells(i).CF=19900; %Hz
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV 
% cells(i).filenum(1,:)='003'; % broadly tuned, consistent responses, spontaneous activity 
% cells(i).description{1}='TC';
% cells(i).mode{1}='mua'& 'lca';
% cells(i).use{1}='m';



% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='121812';
% cells(i).session='005';
% cells(i).depth=135; %micrometers
% cells(i).internalSolution='Cs/QX';
% cells(i).A1=y;
% cells(i).CF=14300; %Hz
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=22; %mV
% cells(i).filenum(1,:)='002';%CB, bad quality, no pattern
% cells(i).description{1}='1-64';
% cells(i).mode{1}='i=0';
% cells(i).use{1}='n';
% cells(i).filenum(2,:)='003';
% cells(i).description{2}='TC'; %CB, well tuned
% cells(i).mode{2}='i=0';
% cells(i).use{2}='n';
% cells(i).filenum(3,:)='004'; %
% cells(i).description{3}='4-8;8-16;16-32'; %CB, On responses, has Cs spikes, not useful
% cells(i).mode{3}='i=0';
% cells(i).use{3}='n';
% cells(i).filenum(4,:)='005'; %
% cells(i).description{4}='4-8;8-16;16-32'; %CB, -100 60, poor currents, bad quality
% cells(i).mode{4}='vclamp';
% cells(i).use{4}='n';





% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='012213';
% cells(i).session='005';
% cells(i).depth=179; %micrometers
% cells(i).internalSolution='K';
% cells(i).A1=m;
% cells(i).CF=nan; %Hz
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV
% cells(i).filenum(1,:)='001';%N, shows pattern, but protocol is not completed, bad quality
% cells(i).description{1}='20-25;26-28;29-39'; 
% cells(i).mode{1}='i=0';
% cells(i).use{1}='n';

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='012213';
cells(i).session='007';
cells(i).depth=281; %micrometers
cells(i).internalSolution='K';
cells(i).A1=m;
cells(i).CF=23500; %Hz
cells(i).L=28.2;
cells(i).D=65.5;
cells(i).SD1=.2429;
cells(i).SD2=.0151;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='002';%N some bad traces, but shows patterns and sound responsive, use?
cells(i).description{1}='20-25;26-28;29-39'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=.184;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=8;
cells(i).tau2(1)=232;
cells(i).u1(1)=9.8;
cells(i).u2(1)=63.5;
cells(i).filenum(2,:)='003'; %
cells(i).description{2}='TC';  
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='012613';
% cells(i).session='002';
% cells(i).depth=nan; %micrometers
% cells(i).A1=m;
% cells(i).tauF=nan; %Hz
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV
% cells(i).filenum(1,:)='001';
% cells(i).description{1}='20-25;26-28;29-39'; %-90 70, amp=60, bad quality, some epochs can be used for analysis
% cells(i).mode{1}='vclamp';
% cells(i).use{1}='n';
% cells(i).filenum(2,:)='002';
% cells(i).description{2}='20-25;26-28;29-39'; %lost the cell in the middle, bad quality
% cells(i).mode{2}='i=0';
% cells(i).use{2}='n';

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='022313';
cells(i).session='005';
cells(i).depth=94; %micrometers
cells(i).internalSolution='K';
cells(i).A1=m;
cells(i).CF=16800; %Hz
cells(i).L=38.8;
cells(i).D=101.5;
cells(i).SD1=.4007;
cells(i).SD2=0.0330;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='002';
cells(i).description{1}='16-16.5;17-19; 19.5-22'; %-90 100, amp=60, visible currents, high Rs, is not stimulus locked
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=.219;
cells(i).E(1)=.248;
cells(i).I(1)=.144;
cells(i).tauE1(1)=515;
cells(i).tauE2(1)=865;
cells(i).uE1(1)=1.7;
cells(i).uE2(1)=16;
cells(i).tauI1(1)=100;
cells(i).tauI2(1)=827;
cells(i).uI1(1)=0.3;
cells(i).uI2(1)=13.3;
% cells(i).filenum(2,:)='003';
% cells(i).description{2}='16-16.5;17-19; 19.5-22'; %very rhythmic trace, artifact
% cells(i).mode{2}='i=0';
% cells(i).use{2}='y';
% cells(i).R(2)=.26; %value from DAB-LN
% cells(i).E(2)=nan;
% cells(i).I(2)=nan;
% cells(i).tau1(2)=nan;
% cells(i).tau2(2)=nan;
% cells(i).u1(2)=nan;
% cells(i).u2(2)=nan;
cells(i).filenum(3,:)='004'; % tuned and sound responsive
cells(i).description{3}='TC'; 
cells(i).mode{3}='i=0';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;


i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='022313';
cells(i).session='008';
cells(i).depth=180; %micrometers
cells(i).internalSolution='nan';
cells(i).A1=m;
cells(i).CF=nan; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='16-16.5;17-19; 19.5-22'; %didnt finish protocol
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=.347;
cells(i).E(1)=.361;
cells(i).I(1)=.300;
cells(i).tauE1(1)=77;
cells(i).tauE2(1)=366;
cells(i).tauE1(1)=11.2;
cells(i).tauE2(1)=20.0;
cells(i).tauI1(1)=691;
cells(i).tauI2(1)=694;
cells(i).uI1(1)=1.5;
cells(i).uI2(1)=24.4;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='031113';
cells(i).session='002';
cells(i).depth=163; %micrometers
cells(i).internalSolution='K';
cells(i).A1=m;
cells(i).CF=14300; %Hz, TC is very unreliable
cells(i).L=64;
cells(i).D=50.3;
cells(i).SD1=.3107;
cells(i).SD2=0.0132;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='14-19'; %-90 100, amp=60, N, no visible currents, bad quality
cells(i).mode{1}='vclamp';
cells(i).use{1}='n';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau(1)=nan;
cells(i).filenum(2,:)='002';
cells(i).description{2}='14-19'; %pattern, protocol not finished, but part of the data can be useful?
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=.363;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau1(2)=10;
cells(i).tau2(2)=667;
cells(i).u1(2)=12.3;
cells(i).u2(2)=32.2;
cells(i).filenum(3,:)='003'; 
cells(i).description{3}='TC'; %very poor quality, unclear
cells(i).mode{3}='i=0';
cells(i).use{3}='m';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='040213';
cells(i).session='003';
cells(i).depth=108; %micrometers
cells(i).internalSolution='K';
cells(i).A1=m;
cells(i).CF=16800; %Hz, well tuned
cells(i).L=29.4;
cells(i).D=27.6;
cells(i).SD1=.3649;
cells(i).SD2=.0319;
cells(i).Vout=6.9; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='8-32'; %-90 70, amp=60, N, no clear conductances, bad guality
cells(i).mode{1}='vclamp';
cells(i).use{1}='n';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).filenum(2,:)='002';
cells(i).description{2}='8-32'; %great consistant responses, good quality
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=.579;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau1(2)=519;
cells(i).tau2(2)=167;
cells(i).u1(2)=0.4;
cells(i).u2(2)=89;
cells(i).filenum(3,:)='004';
cells(i).description{3}='TC'; % 16.8
cells(i).mode{3}='i=0';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;
cells(i).filenum(4,:)='003';
cells(i).description{4}='14-19'; %-90 70, amp=60, N, no clear negative current, bad quality
cells(i).mode{4}='vclamp';
cells(i).use{4}='n';
cells(i).R(4)=nan;
cells(i).E(4)=nan;
cells(i).I(4)=nan;
cells(i).tau(4)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='040213';
cells(i).session='004';
cells(i).depth=72; %micrometers
cells(i).A1=m;
cells(i).CF=nan; %Hz, untuned
cells(i).L=29.7;
cells(i).D=20.7;
cells(i).SD1=.39;
cells(i).SD2=0.01;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='14-19'; % amp=60, N, very responsive, shows pattern, useful?
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=.431;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=367;
cells(i).tau2(1)=125;
cells(i).u1(1)=7.9;
cells(i).u2(1)=11.3;
cells(i).filenum(2,:)='002';
cells(i).description{2}='TC'; %untuned, or spiked a lot because of high Vm -50
cells(i).mode{2}='i=0';
cells(i).use{2}='m';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='051113';
cells(i).session='003';
cells(i).depth=122; %micrometers
cells(i).internalSolution='K';
cells(i).A1=n;
cells(i).CF=12100; %Hz, 
cells(i).L=31.1;
cells(i).D=61.8;
cells(i).SD1=.2992;
cells(i).SD2=.0093;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='speech'; % amp=60, N, very responsive
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau(1)=nan;
cells(i).filenum(2,:)='004';
cells(i).description{2}='5-10'; %very responsive, sound driven, good quality
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=.490;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau1(2)=685;
cells(i).tau2(2)=189;
cells(i).u1(2)=2.6;
cells(i).u2(2)=37.1;
cells(i).filenum(3,:)='008';
cells(i).description{3}='TC'; %well tuned
cells(i).mode{3}='i=0';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;
cells(i).filenum(4,:)='009';
cells(i).description{4}='14-19'; %good quality, sound driven
cells(i).mode{4}='i=0';
cells(i).use{4}='y';
cells(i).R(4)=.630;
cells(i).E(4)=nan;
cells(i).I(4)=nan;
cells(i).tau1(4)=718;
cells(i).tau2(4)=182;
cells(i).u1(4)=3.3;
cells(i).u2(4)=9.7;
cells(i).filenum(5,:)='010';
cells(i).description{5}='9-11;11.1-13;13.1-15'; %bad quality, rhythmic waves, -60Vm???
cells(i).mode{5}='i=0';
cells(i).use{5}='n';
cells(i).R(5)=nan;
cells(i).E(5)=nan;
cells(i).I(5)=nan;
cells(i).tau(5)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='051113';
cells(i).session='004';
cells(i).depth=255; %micrometers
cells(i).A1=m;
cells(i).CF=10200; %Hz, untuned
cells(i).L=24;
cells(i).D=20.7;
cells(i).SD1=.39;
cells(i).SD2=.01;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='speech'; % amp=60, N, very responsive
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau(1)=nan;
cells(i).filenum(2,:)='002';
cells(i).description{2}='TC'; %well tuned, 12
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='003';
cells(i).description{3}='9-11;11.1-13;13.1-15'; %good quality, some pattern
cells(i).mode{3}='i=0';
cells(i).use{3}='y';
cells(i).R(3)=.355;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau1(3)=1974;
cells(i).tau2(3)=222;
cells(i).u1(3)=0.9;
cells(i).u2(3)=22.3;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='051913';
cells(i).session='002';
cells(i).depth=nan; %micrometers
cells(i).A1=m;
cells(i).CF=27700; %Hz, 
cells(i).L=32.9;
cells(i).D=39.9;
cells(i).SD1=.51;
cells(i).SD2=.04;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='TC'; % 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau(1)=nan;
cells(i).filenum(2,:)='002';
cells(i).description{2}='speech'; % rhythmic spikes 
cells(i).mode{2}='i=0';
cells(i).use{2}='m';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='052313';
% cells(i).session='002';
% cells(i).depth=nan; %micrometers
% cells(i).A1=m;
% cells(i).CF=nan; %Hz, 
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV
% cells(i).filenum(1,:)='001';
% cells(i).description{1}='4-8; 8-16; 16-32'; % amp=80, not sure about the stimulus, really bad quality
% cells(i).mode{1}='vclamp';
% cells(i).use{1}='n';

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='052213';
cells(i).session='003';
cells(i).depth=nan; %micrometers
cells(i).A1=m;
cells(i).CF=nan; %Hz, 
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='4-8;8-16;16-32'; % amp=80, not sure about the stimulus, CB
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=.335;
cells(i).E(1)=.183;
cells(i).I(1)=.071;
cells(i).tauE1(1)=280;
cells(i).tauE2(1)=404;
cells(i).uE1(1)=5.5;
cells(i).uE2(1)=41.2;
cells(i).tauI1(1)=62;
cells(i).tauI2(1)=512;
cells(i).uI1(1)=5.5;
cells(i).uI2(1)=23.1;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='052213';
cells(i).session='004';
cells(i).depth=nan; %micrometers
cells(i).A1=m;
cells(i).CF=nan; %Hz, 
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='4-8;8-16;16-32'; % amp=80, not sure about the stimulus, can be useful?
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=.204;
cells(i).E(1)=.104;
cells(i).I(1)=-0.001;
cells(i).tauE1(1)=100;
cells(i).tauE2(1)=235;
cells(i).uE1(1)=0.4;
cells(i).uE2(1)=50.9;
cells(i).tauI1(1)=12;
cells(i).tauI2(1)=285;
cells(i).uI1(1)=0.5;
cells(i).uI2(1)=10;


i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='061913';
cells(i).session='002';
cells(i).depth=181; %micrometers
cells(i).A1=n;
cells(i).CF=16800; %Hz,
cells(i).L=37.4;
cells(i).D=110.9;
cells(i).SD1=.3908;
cells(i).SD2=0.0301;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='speech'; % comparing cell's responses to stimuli
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau(1)=nan;
cells(i).filenum(2,:)='002';
cells(i).description{2}='8-32'; % sound driven, -68Vm
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=.317;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau1(2)=100;
cells(i).tau2(2)=124;
cells(i).u1(2)=0;
cells(i).u2(2)=49.1;
cells(i).filenum(3,:)='003';
cells(i).description{3}='TC'; 
cells(i).mode{3}='i=0';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='062113';
cells(i).session='003';
cells(i).depth=nan; %micrometers
cells(i).A1=y;
cells(i).CF=12100; %Hz, 
cells(i).L=40.1;
cells(i).D=43.1;
cells(i).SD1=.4555;
cells(i).SD2=.0152;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='TC'; % TC for 005-001
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=.480;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau(1)=nan;
%from 005-001:
cells(i).filenum(2,:)='002';
cells(i).description{2}='9-11;11.1-13;13.1-15'; % TC is 003-001
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau1(2)=82;
cells(i).tau2(2)=360;
cells(i).u1(2)=2.6;
cells(i).u2(2)=12.6;

%the following "cell" (005-001)) is a file taken on the previous cell with
%accidentally new session. We copied the data to 003 and renamed the
%datafiles as 003-002
% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='062113';
% cells(i).session='005';
% cells(i).depth=nan; %micrometers
% cells(i).A1=y;
% cells(i).CF=12000; %Hz, 
% cells(i).Vout=nan; %mV
% cells(i).filenum(1,:)='001';
% cells(i).description{1}='9-11;11.1-13;13.1-15'; % TC is 003-001
% cells(i).mode{1}='i=0';
% cells(i).use{1}='y';

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='071113';
cells(i).session='003';
cells(i).depth=365; %micrometers
cells(i).internalSolution='Cs/QX';
cells(i).A1=m;
cells(i).CF=nan; %Hz,
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=9.4; %mV
cells(i).filenum(1,:)='002';
cells(i).description{1}='8-32'; % great On currents, fairly quiet the rest of the time
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=.25;
cells(i).E(1)=.421;
cells(i).I(1)=.153;
cells(i).tauE1(1)=22;
cells(i).tauE2(1)=132;
cells(i).uE1(1)=3.5;
cells(i).uE2(1)=64.6;
cells(i).tauI1(1)=25;
cells(i).tauI2(1)=258;
cells(i).uI1(1)=32.3;
cells(i).uI2(1)=35.5;


i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='071113';
cells(i).session='004';
cells(i).depth=220; %micrometers
cells(i).internalSolution='Cs/QX';
cells(i).A1=m;
cells(i).CF=nan; %Hz,
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=9.4; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='8-32'; % on responses, some bad quality, useful?
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=.236;
cells(i).E(1)=0.093;
cells(i).I(1)=.134;
cells(i).tauE1(1)=31;
cells(i).tauE2(1)=200;
cells(i).uE1(1)=14.8;
cells(i).uE2(1)=27.5;
cells(i).tauI1(1)=39;
cells(i).tauI2(1)=200;
cells(i).uI1(1)=16.3;
cells(i).uI2(1)=29.7;


% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='071413';
% cells(i).session='004';
% cells(i).depth=153; %micrometers
% cells(i).internalSolution='Cs/QX';
% cells(i).A1=m;
% cells(i).CF=20000; %Hz,
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=5.7; %mV
% cells(i).filenum(1,:)='001';
% cells(i).description{1}='8-32'; % quality went bad in the middle of the recordign but recovered later, probably not useful
% cells(i).mode{1}='vclamp';
% cells(i).use{1}='n';
% cells(i).filenum(2,:)='002';
% cells(i).description{2}='TC'; % 
% cells(i).mode{2}='i=0';
% cells(i).use{2}='n';

% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='081613';
% cells(i).session='001';
% cells(i).depth=327; %micrometers
% cells(i).internalSolution='nan';
% cells(i).A1=y;
% cells(i).CF=23500; %Hz, 
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV
% cells(i).filenum(1,:)='001';
% cells(i).description{1}='TC'; % 
% cells(i).mode{1}='mua';
% cells(i).use{1}='m';
% cells(i).filenum(2,:)='003';
% cells(i).description{2}='speech'; % Spanish Posdast, 80 dB, 10 sec with 5 sec isi
% cells(i).mode{2}='mua';
% cells(i).use{2}='m';

% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='081713';
% cells(i).session='001';
% cells(i).depth=281; %micrometers
% cells(i).internalSolution='nan';
% cells(i).A1=y;
% cells(i).CF=17000; %Hz, 
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV
% cells(i).filenum(1,:)='001';
% cells(i).description{1}='TC'; % 
% cells(i).mode{1}='LFP';
% cells(i).use{1}='m';
% cells(i).filenum(2,:)='002';
% cells(i).description{2}='speech'; % Spanish Posdast, 60 dB, 10 sec with 5 sec isi
% cells(i).mode{2}='mua';
% cells(i).use{2}='m';
% 
% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='081713';
% cells(i).session='001';
% cells(i).depth=262; %micrometers
% cells(i).internalSolution='nan';
% cells(i).A1=y;
% cells(i).CF=33000; %Hz,
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV
% cells(i).filenum(1,:)='004';
% cells(i).description{1}='TC'; % 
% cells(i).mode{1}='mua';
% cells(i).use{1}='m';
% cells(i).filenum(2,:)='005';
% cells(i).description{2}='speech'; % Spanish Posdast, 60 dB, 10 sec with 5 sec isi
% cells(i).mode{2}='mua';
% cells(i).use{2}='m';

% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='081713';
% cells(i).session='001';
% cells(i).depth=272; %micrometers
% cells(i).internalSolution='nan';
% cells(i).A1=y;
% cells(i).CF=9000; %Hz, 
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV
% cells(i).filenum(1,:)='007';
% cells(i).description{1}='TC'; % 
% cells(i).mode{1}='mua';
% cells(i).use{1}='m';
% cells(i).filenum(2,:)='009';
% cells(i).description{2}='speech'; % Spanish Posdast, 60 dB, 10 sec with 5 sec isi
% cells(i).mode{2}='mua';
% cells(i).use{2}='m';

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='082613';
cells(i).session='002';
cells(i).depth=586; %micrometers
cells(i).internalSolution='Cs/QX';
cells(i).A1=y;
cells(i).CF=nan; %Hz,
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='002';
cells(i).description{1}='14-19;19-25;25-33'; % very low Rs, some unstable parts, but useful data
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=.134;
cells(i).E(1)=.124;
cells(i).I(1)=.036;
cells(i).tauE1(1)=65;
cells(i).tauE2(1)=646;
cells(i).uE1(1)=6.7;
cells(i).uE2(1)=5.6;
cells(i).tauI1(1)=26;
cells(i).tauI2(1)=602;
cells(i).uI1(1)=0.5;
cells(i).uI2(1)=13.7;


i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='082613';
cells(i).session='003';
cells(i).depth=398; %micrometers
cells(i).internalSolution='Cs/QX';
cells(i).A1=y;
cells(i).CF=nan; %Hz,
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=4.6; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='14-19;19-25;25-33'; % CB only on responses, somewhat bad quality
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=0.083;
cells(i).E(1)=0.006;
cells(i).I(1)=.063;
cells(i).tauE1(1)=28;
cells(i).tauE2(1)=1289;
cells(i).uE1(1)=39.6;
cells(i).uE2(1)=4.2;
cells(i).tauI1(1)=26;
cells(i).tauI2(1)=883;
cells(i).uI1(1)=.5;
cells(i).uI2(1)=6.1;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='082713';
cells(i).session='005';
cells(i).depth=169; %micrometers
cells(i).internalSolution='Cs/QX';
cells(i).A1=m;
cells(i).CF=14300; %Hz,
cells(i).L=80.9;
cells(i).D=95;
cells(i).SD1=.2559;
cells(i).SD2=0.0319;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';
cells(i).description{1}='TC'; % 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau(1)=nan;
cells(i).filenum(2,:)='002';
cells(i).description{2}='10-13;13-16;16-20'; % some parts have bad quality
cells(i).mode{2}='vclamp';
cells(i).use{2}='y';
cells(i).R(2)=0.155;
cells(i).E(2)=0.178;
cells(i).I(2)=.054;
cells(i).tauE1(2)=17;
cells(i).tauE2(2)=457;
cells(i).uE1(2)=73.4;
cells(i).uE2(2)=38.6;
cells(i).tauI1(2)=121;
cells(i).tauI2(2)=481;
cells(i).uI1(2)=1.5;
cells(i).uI2(2)=16.4;
cells(i).filenum(3,:)='004';
cells(i).description{3}='10-13;13-16;16-20'; % increased voltage to -100 and 50, some bad parts
cells(i).mode{3}='vclamp';
cells(i).use{3}='n';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='082813';
cells(i).session='002';
cells(i).depth=152; %micrometers
cells(i).A1=y;
cells(i).CF=nan; %Hz,
cells(i).L=118.2;
cells(i).D=181.8;
cells(i).SD1=.3184;
cells(i).SD2=0.0013;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='003';
cells(i).description{1}='12-28'; % good Rs, stable, but strange outward currents, maybe useful
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=0.008;
cells(i).E(1)=0.074;
cells(i).I(1)=-0.044;
cells(i).tauE1(1)=100;
cells(i).tauE2(1)=71;
cells(i).uE1(1)=.3;
cells(i).uE2(1)=36.4;
cells(i).tauI1(1)=33;
cells(i).tauI2(1)=2136;
cells(i).uI1(1)=41.5;
cells(i).uI2(1)=3.1;
cells(i).filenum(2,:)='004';
cells(i).description{2}='TC'; % 
cells(i).mode{2}='i=0';
cells(i).use{2}='m';
cells(i).filenum(3,:)='002';
cells(i).description{3}='14-19;19-25;25-33'; % didnt finish, 12 epochs
cells(i).mode{3}='vclamp';
cells(i).use{3}='n';

% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='083013';
% cells(i).session='001';
% cells(i).depth=152; %micrometers
% cells(i).internalSolution='nan';
% cells(i).A1=y;
% cells(i).CF=16000; %Hz,
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV
% cells(i).filenum(1,:)='001';
% cells(i).description{1}='TC'; % 
% cells(i).mode{1}='mua';
% cells(i).use{1}='m';
% cells(i).filenum(2,:)='003';
% cells(i).description{2}='speech'; % Spanish Posdast, 60 dB, 10 sec with 5 sec isi, pitch-shifted one octave
% cells(i).mode{2}='mua';
% cells(i).use{2}='m';
% cells(i).filenum(3,:)='004';
% cells(i).description{3}='speech'; % Spanish Posdast, 60 dB, 10 sec with 5 sec isi, not pitch-shifted
% cells(i).mode{3}='mua';
% cells(i).use{3}='m';
% cells(i).filenum(4,:)='004';
% cells(i).description{4}='7-40'; % SPNoise protocol, 10 reps, 5 sec start, 0 isi, to compare MU responses
% cells(i).mode{4}='mua';
% cells(i).use{4}='m';

% i=i+1;
% cells(i).user='ira';
% cells(i).rig='rig1';
% cells(i).expdate='121812';
% cells(i).session='001';
% cells(i).depth=220-314; %micrometers
% cells(i).internalSolution='nan';
% cells(i).A1=y;
% cells(i).CF=nan; %Hz
% cells(i).L=nan;
% cells(i).D=nan;
% cells(i).SD1=nan;
% cells(i).SD2=nan;
% cells(i).Vout=nan; %mV 
% cells(i).filenum(1,:)='001'; % broadly tuned, lfps dont look like A1 
% cells(i).description{1}='TC';
% cells(i).mode{1}='mua'& 'lfp';
% cells(i).use{1}='m';
% cells(i).filenum(2,:)='002'; % responsive area 
% cells(i).description{2}='speech';
% cells(i).mode{2}='mua';
% cells(i).use{2}='m';
% cells(i).filenum(3,:)='003'; % broadly tuned to 14 KHz, nice LFPs, A1 region
% cells(i).description{3}='TC';
% cells(i).mode{3}='mua'& 'lfp';
% cells(i).use{3}='m';
% cells(i).filenum(4,:)='004'; % responsive area, pitch-shifted, strong on-responses
% cells(i).description{4}='speech';
% cells(i).mode{4}='mua';
% cells(i).use{4}='m';
% cells(i).filenum(5,:)='006'; % untuned
% cells(i).description{5}='TC';
% cells(i).mode{5}='mua'& 'lfp';
% cells(i).use{5}='m';
% cells(i).filenum(6,:)='007'; % not very responsive, pitch-shifted, on-responses
% cells(i).description{6}='speech';
% cells(i).mode{6}='mua';
% cells(i).use{6}='m';

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='121112';
cells(i).session='004';
cells(i).depth=148; %micrometers
cells(i).internalSolution='Cs/QX'; %
cells(i).A1=y;
cells(i).CF=14300; %Hz
cells(i).L=48.3;
cells(i).D=77.6;
cells(i).SD1=0.13;
cells(i).SD2=0.006;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='003'; %great cell, very responsive to SPNoise
cells(i).description{1}='1-64'; %CB, some bad traces on outward currents
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=0.346;
cells(i).E(1)=0.235;
cells(i).I(1)=0.083;
cells(i).tauE1(1)=14;
cells(i).tauE2(1)=992;
cells(i).uE1(1)=17.7;
cells(i).uE2(1)=31;
cells(i).tauI1(1)=17;
cells(i).tauI2(1)=182;
cells(i).uI1(1)=21.9;
cells(i).uI2(1)=29.2;
cells(i).filenum(2,:)='005';
cells(i).description{2}='4-8;8-16;16-32'; %CB, high Rs, good currents
cells(i).mode{2}='vclamp';
cells(i).use{2}='y';
cells(i).R(2)=0.381;
cells(i).E(2)=0.415;
cells(i).I(2)=0.108;
cells(i).tauE1(2)=2528;
cells(i).tauE2(2)=270;
cells(i).uE1(2)=0.4;
cells(i).uE2(2)=19.5;
cells(i).tauI1(2)=232;
cells(i).tauI2(2)=771;
cells(i).uI1(2)=.3;
cells(i).uI2(2)=58.3;
cells(i).filenum(3,:)='006'; %big Cs spikes, data not usable
cells(i).description{3}='4-8;8-16;16-32'; % CB
cells(i).mode{3}='i=0';
cells(i).use{3}='n';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;
cells(i).filenum(4,:)='008'; %%big Cs spikes, data not usable
cells(i).description{4}='1-64'; % CB
cells(i).mode{4}='i=0';
cells(i).use{4}='n';
cells(i).R(4)=nan;
cells(i).E(4)=nan;
cells(i).I(4)=nan;
cells(i).tau(4)=nan;
cells(i).filenum(5,:)='007';
cells(i).description{5}='TC'; %well-tuned CF =14.3 KHz
cells(i).mode{5}='i=0';
cells(i).use{5}='y';
cells(i).R(5)=nan;
cells(i).E(5)=nan;
cells(i).I(5)=nan;
cells(i).tau(5)=nan;
i=i+1;

cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='121812';
cells(i).session='003';
cells(i).depth=100; %micrometers
cells(i).internalSolution='Cs/QX';
cells(i).A1=y;
cells(i).CF=19900; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=20; %mV not sure about this number
cells(i).filenum(1,:)='002';%cb, great conductances, somehwat unstable, not many responses
cells(i).description{1}='1-64'; %-90 60
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=0.084;
cells(i).E(1)=0.115;
cells(i).I(1)=0.108;
cells(i).tauE1(1)=673;
cells(i).tauE2(1)=200;
cells(i).uE1(1)=1.5;
cells(i).uE2(1)=16.3;
cells(i).tauI1(1)=28;
cells(i).tauI2(1)=93;
cells(i).uI1(1)=13.9;
cells(i).uI2(1)=70.7;
cells(i).filenum(2,:)='003';
cells(i).description{2}='TC'; %not sure if i still had the cell at this time, looks like LFP
cells(i).mode{2}='lfp';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='122012';
cells(i).session='002';
cells(i).depth=413; %micrometers
cells(i).internalSolution='Cs/QX';
cells(i).A1=m;
cells(i).CF=3800; %Hz from LFPs
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=8; %mV
cells(i).filenum(1,:)='001';%CB, lost the cell in the end, not very responsive but can be useful?
cells(i).description{1}='1-64'; %-90 40
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=.339;
cells(i).E(1)=.386;
cells(i).I(1)=.239;
cells(i).tauE1(1)=27;
cells(i).tauE2(1)=229;
cells(i).uE1(1)=34.2;
cells(i).uE2(1)=61.9;
cells(i).tauI1(1)=41;
cells(i).tauI2(1)=367;
cells(i).uI1(1)=52.2;
cells(i).uI2(1)=79.6;
cells(i).filenum(2,:)='002';
cells(i).description{2}='1-64'; %CB, bad quality, lost the cell
cells(i).mode{2}='i=0';
cells(i).use{2}='n';
cells(i).R(2)=.56;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='003'; %
cells(i).description{3}='TC'; %CB, LFP
cells(i).mode{3}='lfp';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='122012';
cells(i).session='007';
cells(i).depth=393; %micrometers
cells(i).internalSolution='Cs/QX';
cells(i).A1=m;
cells(i).CF=14300; %Hz
cells(i).L=26.1;
cells(i).D=123.3;
cells(i).SD1=.4531;
cells(i).SD2=.0378;
cells(i).Vout=3.2; %mV
cells(i).filenum(1,:)='001';%CB, quality got worse, but great currents, good data
cells(i).description{1}='1-64'; %-90 40
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=.658;
cells(i).E(1)=.722;
cells(i).I(1)=.483;
cells(i).tauE1(1)=14;
cells(i).tauE2(1)=91;
cells(i).uE1(1)=17.6;
cells(i).uE2(1)=116;
cells(i).tauI1(1)=23;
cells(i).tauI2(1)=63;
cells(i).uI1(1)=28.8;
cells(i).uI2(1)=76.1;

cells(i).filenum(2,:)='003';
cells(i).description{2}='1-64'; %CB, ceasium spikes, -40Vm
cells(i).mode{2}='i=0';
cells(i).use{2}='n';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='004'; %
cells(i).description{3}='TC'; %CB, 
cells(i).mode{3}='i=0';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;
cells(i).filenum(4,:)='006';%CB, quality got worse, should not use this
cells(i).description{4}='4-8;8-16;16-32'; %-100 60
cells(i).mode{4}='vclamp';
cells(i).use{4}='n';
cells(i).R(4)=nan;
cells(i).E(4)=nan;
cells(i).I(4)=nan;
cells(i).tau(4)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='121012';
cells(i).session='002';
cells(i).depth=328; %micrometers
cells(i).A1=m; %
cells(i).internalSolution='K'; %
cells(i).CF=16800; %Hz
cells(i).L=22.9;
cells(i).D=60.1;
cells(i).SD1=.2756;
cells(i).SD2=.0129;
cells(i).Vout=-2.5; %<-not sure about this#
cells(i).filenum(1,:)='002';
cells(i).description{1}='1-64';%very responsive to SPNoise, N, -56Vm, shows pattern
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=.42;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=23;
cells(i).tau2(1)=305;
cells(i).u1(1)=28.8;
cells(i).u2(1)=40.4;
cells(i).filenum(2,:)='005';
cells(i).description{2}='TC'; %19.9 KHz, evoked spiking
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;1
cells(i).tau(3)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='121412';
cells(i).session='007';
cells(i).depth=232; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=27700; %Hz
cells(i).L=79.8; %
cells(i).D=120.20; %
cells(i).SD1=0.3177; %
cells(i).SD2=0.0118; %
cells(i).Vout=nan; %mV 18.5?
cells(i).filenum(1,:)='001'; %CB, bad quality, should not be used
cells(i).description{1}='1-64';
cells(i).mode{1}='vclamp';
cells(i).use{1}='n';
cells(i).R(1)=.32;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau(1)=nan;
cells(i).filenum(2,:)='002';
cells(i).description{2}='1-64'; %CB, Vm was around -60, quality deteriorated over time, strong ON-responses
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=.371;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau1(2)=40;
cells(i).tau2(2)=700;
cells(i).u1(2)=50.4;
cells(i).u2(2)=22.7;
cells(i).filenum(3,:)='003'; %CB
cells(i).description{3}='TC'; % well tuned
cells(i).mode{3}='i=0';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='121812';
cells(i).session='002';
cells(i).depth=111; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=27700; %Hz
cells(i).L=31.5;
cells(i).D=71.2;
cells(i).SD1=.4181;
cells(i).SD2=0.0388;
cells(i).Vout=0.8; %mV
cells(i).filenum(1,:)='003';%N
cells(i).description{1}='1-64'; %great recording, shows pattern, -60Vm
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=.385;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=11;
cells(i).tau2(1)=461;
cells(i).u1(1)=11.9;
cells(i).u2(1)=3.9;
cells(i).filenum(2,:)='004';
cells(i).description{2}='TC'; %N
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='005'; %
cells(i).description{3}='4-8;8-16;16-32'; %N %great recording, shows pattern, -60Vm
cells(i).mode{3}='i=0';
cells(i).use{3}='y';
cells(i).R(3)=.505;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau1(3)=945;
cells(i).tau2(3)=142;
cells(i).u1(3)=1;
cells(i).u2(3)=10.8;
cells(i).filenum(4,:)='006'; %
cells(i).description{4}='1-64'; %N, -90 40, bad quality, spiking
cells(i).mode{4}='vclamp';
cells(i).use{4}='n';
cells(i).R(4)=nan;
cells(i).E(4)=nan;
cells(i).I(4)=nan;
cells(i).tau(4)=nan;
cells(i).filenum(5,:)='009'; %
cells(i).description{5}='1-64'; %N, -90 60, bad quality
cells(i).mode{5}='vclamp';
cells(i).use{5}='n';
cells(i).R(5)=nan;
cells(i).E(5)=nan;
cells(i).I(5)=nan;
cells(i).tau(5)=nan;



i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='121812';
cells(i).session='004';
cells(i).depth=48; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=19900; %Hz
cells(i).L=47.8;
cells(i).D=81.9;
cells(i).SD1=.4187;
cells(i).SD2=.0144;
cells(i).Vout=33; %mV
cells(i).filenum(1,:)='002';%N well tuned
cells(i).description{1}='TC';
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau(1)=nan;
cells(i).filenum(2,:)='003';
cells(i).description{2}='1-64'; %N, it took awhile for this cell to wake up, -48Vm, on highreppper low pattern
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=.355;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau1(2)=1388;
cells(i).tau2(2)=596;
cells(i).u1(2)=1.5;
cells(i).u2(2)=14.5;
cells(i).filenum(3,:)='004'; %
cells(i).description{3}='1-64'; %N, -90 60, high Rs, no outward currents
cells(i).mode{3}='vclamp';
cells(i).use{3}='n';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;
cells(i).filenum(4,:)='005'; %
cells(i).description{4}='4-8;8-16;16-32'; %N, low responsiveness, very consistent off response?
cells(i).mode{4}='i=0';
cells(i).use{4}='y';
cells(i).R(4)=.377;
cells(i).E(4)=nan;
cells(i).I(4)=nan;
cells(i).tau1(4)=853;
cells(i).tau2(4)=132;
cells(i).u1(4)=1.8;
cells(i).u2(4)=12.5;
cells(i).filenum(5,:)='006'; %
cells(i).description{5}='1-64'; %N, more reps of 1-64, quality got worse.
cells(i).mode{5}='i=0';
cells(i).use{5}='n';
cells(i).R(5)=nan;
cells(i).E(5)=nan;
cells(i).I(5)=nan;
cells(i).tau(5)=nan;


i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='122012';
cells(i).session='003';
cells(i).depth=181; %micrometers
cells(i).internalSolution='K';
cells(i).A1=m;
cells(i).CF=nan; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';%N, shows a nice pattern. took awhile to wake up, some data can be useful?
cells(i).description{1}='1-64'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=.604;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=24;
cells(i).tau2(1)=470;
cells(i).u1(1)=30.5;
cells(i).u2(1)=70.3;
cells(i).filenum(2,:)='002'; % quality slowly got worse, use getlostat
cells(i).description{2}='4-8;8-16;16-32'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

%new data
i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='111713';
cells(i).session='004';
cells(i).depth=231; %micrometers
cells(i).internalSolution='K';
cells(i).A1=m;
cells(i).CF=nan; %untuned, the area was tuned to 17 kHz, old mouse
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='002';
cells(i).description{1}='TC'; % untuned
cells(i).mode{1}='i=0';
cells(i).use{1}='n';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).filenum(2,:)='003'; % 
cells(i).description{2}='10-13;13-16;16-20'; %rhythmic activity, stable recording
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='004'; % 
cells(i).description{3}='10-13;13-16;16-20'; %only excitatory currents are useful
cells(i).mode{3}='vclamp';
cells(i).use{3}='n';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;
cells(i).filenum(4,:)='005'; % 
cells(i).description{4}='10-13;13-16;16-20'; %tried to record only excitatory currents, somthing is off with the protocol
cells(i).mode{4}='vclamp';
cells(i).use{4}='n';
cells(i).R(4)=nan;
cells(i).E(4)=nan;
cells(i).I(4)=nan;
cells(i).tau(4)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='112013';
cells(i).session='001';
cells(i).depth=118; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=17000; %Hz, broadly tuned
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001'; %
cells(i).description{1}='TC'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % good reliability
cells(i).description{2}='14-19;19-25;25-33'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='003'; 
cells(i).description{3}='10-13;13-16;16-20'; %-90, exc currents, not finished
cells(i).mode{3}='vclamp';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;
cells(i).filenum(3,:)='004'; 
cells(i).description{3}='TC'; %LFP of the same area
cells(i).mode{3}='i=0';
cells(i).use{3}='n';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;


i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='112113';
cells(i).session='005';
cells(i).depth=118; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=14000; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001'; %well tuned
cells(i).description{1}='TC'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='005'; % good reliability, 002+004
cells(i).description{2}='10-13;13-16;16-20'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='003'; 
cells(i).description{3}='10-13;13-16;16-20'; %-90, exc currents
cells(i).mode{3}='vclamp';
cells(i).use{3}='m';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='112113';
cells(i).session='007';
cells(i).depth=322; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=14000; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001'; %well tuned
cells(i).description{1}='TC'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % good reliability
cells(i).description{2}='10-13;13-16;16-20'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='112313';
cells(i).session='002';
cells(i).depth=155; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=10000; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';%N, spiking cell
cells(i).description{1}='TC'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % good reliability, somewhat unstable recording
cells(i).description{2}='5-8;8-13;13-20'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='003'; 
cells(i).description{3}='TC'; %lfp tuning
cells(i).mode{3}='i=0';
cells(i).use{3}='n';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='112313';
cells(i).session='003';
cells(i).depth=177; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=14000; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';%N, well tuned
cells(i).description{1}='TC'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % didn't break in well somewhat unstable recording
cells(i).description{2}='10-13;13-16;16-20'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='112313';
cells(i).session='006';
cells(i).depth=155; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=14000; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';%N, well tuned
cells(i).description{1}='TC'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; %
cells(i).description{2}='10-13;13-16;16-20'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='003'; 
cells(i).description{3}='10-13;13-16;16-20'; %bad quality
cells(i).mode{3}='vclamp';
cells(i).use{3}='n';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='011714';
cells(i).session='002';
cells(i).depth=242; %micrometers
cells(i).internalSolution='Cs/QX';
cells(i).A1=y;
cells(i).CF=7300; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=4.5; %mV
cells(i).filenum(1,:)='001';%well tuned, only E currents
cells(i).description{1}='TC'; 
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % no I currents
cells(i).description{2}='1 band'; 
cells(i).mode{2}='vclamp';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='003'; 
cells(i).description{3}='TC'; %only I currents, different tuning curve
cells(i).mode{3}='vclamp';
cells(i).use{3}='m';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau1(3)=nan;
cells(i).tau2(3)=nan;
cells(i).u1(3)=nan;
cells(i).u2(3)=nan; 
cells(i).filenum(4,:)='005'; % both currents
cells(i).description{4}='1 band'; 
cells(i).mode{4}='vclamp';
cells(i).use{4}='y';
cells(i).R(4)=nan;
cells(i).E(4)=nan;
cells(i).I(4)=nan;
cells(i).tau(4)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='011714';
cells(i).session='003';
cells(i).depth=489; %micrometers
cells(i).internalSolution='Cs/QX';
cells(i).A1=y;
cells(i).CF=16800; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';%well tuned, extracellular recording
cells(i).description{1}='TC'; 
cells(i).mode{1}='lca';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % no I currents
cells(i).description{2}='3-bands'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='012014';
cells(i).session='004';
cells(i).depth=242; %micrometers
cells(i).internalSolution='Cs/QX';
cells(i).A1=y;
cells(i).CF=7300; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';%bad quality only E currents
cells(i).description{1}='TC'; 
cells(i).mode{1}='vclamp';
cells(i).use{1}='m';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % better
cells(i).description{2}='TC'; 
cells(i).mode{2}='vclamp';
cells(i).use{2}='m';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau1(2)=nan;
cells(i).tau2(2)=nan;
cells(i).u1(2)=nan;
cells(i).u2(2)=nan;
cells(i).filenum(3,:)='003'; 
cells(i).description{3}='14-33'; %only E currents
cells(i).mode{3}='vclamp';
cells(i).use{3}='m';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='012814';
cells(i).session='002';
cells(i).depth=559; %micrometers
cells(i).internalSolution='Cs/QX';
cells(i).A1=y;
cells(i).CF=8700; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=7.5; %mV
cells(i).filenum(1,:)='001';%well tuned, both currents
cells(i).description{1}='TC'; 
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='003'; % 
cells(i).description{2}='5-10'; 
cells(i).mode{2}='vlamp';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='004';%another smaller tuning curve
cells(i).description{3}='TC'; 
cells(i).mode{3}='vclamp';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau1(3)=nan;
cells(i).tau2(3)=nan;
cells(i).u1(3)=nan;
cells(i).u2(3)=nan;
cells(i).filenum(4,:)='005';%
cells(i).description{4}='5-10'; %bad quality
cells(i).mode{4}='i-0';
cells(i).use{4}='n';
cells(i).R(4)=nan;
cells(i).E(4)=nan;
cells(i).I(4)=nan;
cells(i).tau(4)=nan;
cells(i).filenum(5,:)='007';%another tuning curve more reps, 008=004+007
cells(i).description{5}='TC'; 
cells(i).mode{5}='vclamp';
cells(i).use{5}='y';
cells(i).R(5)=nan;
cells(i).E(5)=nan;
cells(i).I(5)=nan;
cells(i).tau1(5)=nan;
cells(i).tau2(5)=nan;
cells(i).u1(5)=nan;
cells(i).u2(5)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='012914';
cells(i).session='002';
cells(i).depth=479; %micrometers
cells(i).internalSolution='Cs/QX';
cells(i).A1=y;
cells(i).CF=8900; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=-9; %mV
cells(i).filenum(1,:)='002';%
cells(i).description{1}='TC'; 
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='004'; 
cells(i).description{2}='7-14'; %great big currents
cells(i).mode{2}='vclamp';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='005'; 
cells(i).description{3}='7-14'; %ok membrane potential responses, but might be incorrect
cells(i).mode{3}='i=0';
cells(i).use{3}='m';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;
cells(i).filenum(4,:)='008';
cells(i).description{4}='2-5; 15-20'; % on the side of the RF
cells(i).mode{4}='vclamp';
cells(i).use{4}='m';
cells(i).R(4)=nan;
cells(i).E(4)=nan;
cells(i).I(4)=nan;
cells(i).tau(4)=nan;
cells(i).filenum(5,:)='006';% 010=006+002
cells(i).description{5}='TC'; 
cells(i).mode{5}='vclamp';
cells(i).use{5}='y';
cells(i).R(5)=nan;
cells(i).E(5)=nan;
cells(i).I(5)=nan;
cells(i).tau1(5)=nan;
cells(i).tau2(5)=nan;
cells(i).u1(5)=nan;
cells(i).u2(5)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='021714';
cells(i).session='001';
cells(i).depth=472; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=20000; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';%well tuned, extracellular recording
cells(i).description{1}='TC'; 
cells(i).mode{1}='lfp';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='003'; % 
cells(i).description{2}='3-bands'; 
cells(i).mode{2}='lca';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='002'; % 
cells(i).description{3}='TC'; 
cells(i).mode{3}='lca';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='021714';
cells(i).session='004';
cells(i).depth=524; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=11700; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=3.2; %mV
cells(i).filenum(1,:)='001';%well tuned, was not completely blocked
cells(i).description{1}='TC'; 
cells(i).mode{1}='vclamp';
cells(i).use{1}='m';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % medium reliability
cells(i).description{2}='7-14'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='003'; % did not finish
cells(i).description{3}='7-14'; 
cells(i).mode{3}='vlamp';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='021714';
cells(i).session='002';
cells(i).depth=nan; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=12000; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=1.2; %mV
cells(i).filenum(1,:)='002';%well tuned, was not completely blocked
cells(i).description{1}='TC'; 
cells(i).mode{1}='vclamp';
cells(i).use{1}='m';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='001'; % ok reliability
cells(i).description{2}='7-14'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='003'; % did not finish
cells(i).description{3}='7-14'; 
cells(i).mode{3}='vlamp';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='021714';
cells(i).session='005';
cells(i).depth=nan; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=12000; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=-11; %mV
cells(i).filenum(1,:)='002';%well tuned
cells(i).description{1}='TC'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='001'; % 
cells(i).description{2}='7-14'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='003'; % 
cells(i).description{3}='3-bands'; 
cells(i).mode{3}='i=0';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;
cells(i).filenum(4,:)='005'; % did not finish
cells(i).description{4}='7-14'; 
cells(i).mode{4}='vlamps';
cells(i).use{4}='n';
cells(i).R(4)=nan;
cells(i).E(4)=nan;
cells(i).I(4)=nan;
cells(i).tau(4)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='021914';
cells(i).session='001';
cells(i).depth=442; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=23000; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='006';%well tuned
cells(i).description{1}='TC'; 
cells(i).mode{1}='lca';
cells(i).use{1}='m';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='007'; % a few spikes
cells(i).description{2}='14-33'; 
cells(i).mode{2}='lca';
cells(i).use{2}='m';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='021914';
cells(i).session='002';
cells(i).depth=362; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=12000; %Hz
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';%well tuned
cells(i).description{1}='TC'; 
cells(i).mode{1}='lca';
cells(i).use{1}='m';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % some pattern in spikes
cells(i).description{2}='[3-8;8-20; 20-40]'; 
cells(i).mode{2}='lca';
cells(i).use{2}='m';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='021914';
cells(i).session='003';
cells(i).depth=291; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=nan; %untuned
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='002';%not tuned
cells(i).description{1}='TC'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='m';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='004'; % no pattern
cells(i).description{2}='[3-8;8-20; 20-40]'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='m';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='021914';
cells(i).session='005';
cells(i).depth=515; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=nan; %untuned
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';%untuned
cells(i).description{1}='TC'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='n';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % no pattern, poor quality
cells(i).description{2}='[13-14]'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='n';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='022014';
cells(i).session='003';
cells(i).depth=256; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=nan; %untuned
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';%well tuned
cells(i).description{1}='TC'; 
cells(i).mode{1}='lca';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % a few spikes
cells(i).description{2}='[]'; 
cells(i).mode{2}='lca';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='031814';
cells(i).session='002';
cells(i).depth=412; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=nan; %tuned
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=11.7; %mV
cells(i).filenum(1,:)='003';%well tuned
cells(i).description{1}='VCTC'; 
cells(i).mode{1}='vclamp';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='004'; % lost the cell, only e currents
cells(i).description{2}='[]'; 
cells(i).mode{2}='vclamp';
cells(i).use{2}='m';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;


i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='031914';
cells(i).session='002';
cells(i).depth=257; %micrometers
cells(i).internalSolution='K';
cells(i).A1=m;
cells(i).CF=16800; %tuned-ish
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';%ok tuning
cells(i).description{1}='TC'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % good quality
cells(i).description{2}='[10-24]'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='004'; % 
cells(i).description{3}='[10-24]'; %only e currents, recorded at -90
cells(i).mode{3}='vclamp';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;
cells(i).filenum(4,:)='005'; % 
cells(i).description{4}='[3-8;8-20;20-40]'; 
cells(i).mode{4}='i=0';
cells(i).use{4}='y';
cells(i).R(4)=nan;
cells(i).E(4)=nan;
cells(i).I(4)=nan;
cells(i).tau(4)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='032014';
cells(i).session='002';
cells(i).depth=239; %micrometers
cells(i).internalSolution='K';
cells(i).A1=m;
cells(i).CF=12000; %tuned broadly
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';%ok tuning, good quality
cells(i).description{1}='TC'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % good quality, bad reliability
cells(i).description{2}='[3-8;8-20;20-40]'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;

i=i+1;
cells(i).user='ira';
cells(i).rig='rig1';
cells(i).expdate='032014';
cells(i).session='004';
cells(i).depth=584; %micrometers
cells(i).internalSolution='K';
cells(i).A1=y;
cells(i).CF=12000; %inverted tuning curve
cells(i).L=nan;
cells(i).D=nan;
cells(i).SD1=nan;
cells(i).SD2=nan;
cells(i).Vout=nan; %mV
cells(i).filenum(1,:)='001';%inverted tuning curve
cells(i).description{1}='TC'; 
cells(i).mode{1}='i=0';
cells(i).use{1}='y';
cells(i).R(1)=nan;
cells(i).E(1)=nan;
cells(i).I(1)=nan;
cells(i).tau1(1)=nan;
cells(i).tau2(1)=nan;
cells(i).u1(1)=nan;
cells(i).u2(1)=nan;
cells(i).filenum(2,:)='002'; % good quality
cells(i).description{2}='[3-8;8-20;20-40]'; 
cells(i).mode{2}='i=0';
cells(i).use{2}='y';
cells(i).R(2)=nan;
cells(i).E(2)=nan;
cells(i).I(2)=nan;
cells(i).tau(2)=nan;
cells(i).filenum(3,:)='003'; % 
cells(i).description{3}='[3-8;8-20;20-40]'; %escape from vclamp during i currents
cells(i).mode{3}='vclamp';
cells(i).use{3}='y';
cells(i).R(3)=nan;
cells(i).E(3)=nan;
cells(i).I(3)=nan;
cells(i).tau(3)=nan;
cells(i).filenum(4,:)='004'; % 
cells(i).description{4}='VCTC'; %great tc
cells(i).mode{4}='vclamp';
cells(i).use{4}='y';
cells(i).R(4)=nan;
cells(i).E(4)=nan;
cells(i).I(4)=nan;
cells(i).tau(4)=nan;
cells(i).filenum(5,:)='005'; % 
cells(i).description{5}='TC'; % more reps
cells(i).mode{5}='i=0';
cells(i).use{5}='y';
cells(i).R(5)=nan;
cells(i).E(5)=nan;
cells(i).I(5)=nan;
cells(i).tau(5)=nan;
cells(i).filenum(6,:)='006'; % 
cells(i).description{6}='[5-20]'; % 
cells(i).mode{6}='i=0';
cells(i).use{6}='y';
cells(i).R(6)=nan;
cells(i).E(6)=nan;
cells(i).I(6)=nan;
cells(i).tau(6)=nan;





