function PlotBinGTC(varargin)
%usage:     PlotBinGTC(expdate, session, filenum)
%           PlotBinGTC(expdate, session, filenum, [xlimits])
%           PlotBinGTC(out)
% E2 tuning curve script
%plot tuning curve of peak ge and gi for binaural stimuli
%looks for an outfile data structure generated by
%ProcessBinVCData/compute_bin_ge_gi
xl=[];


if nargin==0
    fprintf('\nno input');
    return
elseif nargin==1
    in=varargin{1};
elseif nargin==3
    expdate=varargin{1};
    session=varargin{2};
    filenum=varargin{3};
    godatadir(expdate, session, filenum)
    outfile=sprintf('out%s-%s-%s.mat', expdate, session, filenum);
    if exist(outfile)==2
        load(outfile)
        if ~isfield(out, 'GE')
            error('could not find gegi data in outfile. Please run ProcessGeGi')
        end
    else
        error('could not find outfile. Please run ProcessGeGi')
    end
    in=out;
elseif nargin==4
    expdate=varargin{1};
    session=varargin{2};
    filenum=varargin{3};
    godatadir(expdate, session, filenum)
    outfile=sprintf('out%s-%s-%s.mat', expdate, session, filenum);
    load(outfile)
    if exist(outfile)==2
        load(outfile)
        if ~isfield(out, 'GE')
            error('could not find gegi data in outfile. Please run ProcessGeGi')
        end
    else
        error('could not find outfile. Please run ProcessGeGi')
    end
    in=out;
    xl=varargin{4};
else
    error('\nPlotBinGeGi: wrong number of arguments');
end

if     strcmp(expdate,'120810') && strcmp(session,'005') && strcmp(filenum,'002')
    y1=[0.25 1.5];
    y2=[0 1.5];
elseif strcmp(expdate,'120810') && strcmp(session,'003') && strcmp(filenum,'003')
    y1=[0 4];
    y2=[0 6];    
elseif strcmp(expdate,'081210') && strcmp(session,'003') && strcmp(filenum,'001')
    y1=[0 1];
    y2=[-1 1];    
end


fs=12;

M1=in.M1;
mM1=in.mM1;
expdate=in.expdate;
session=in.session;
filenum=in.filenum;
freqs=in.freqs;
Ramps=in.Ramps;
Lamps=in.Lamps;
durs=in.durs;
potentials=in.potentials;
samprate=in.samprate;
numamps=length(Ramps);
numfreqs=length(freqs);
numpotentials=length(potentials);
numdurs=length(durs);
xlimits=out.xlimits;

%xl are the xlimits we want to use for plotting
%may or may not be same as xlimits used to create outfile

if  length(xl)~=2
    xl=xlimits;
end
fprintf('\nusing xlimits [%d %d] for analysis', xl)

%find optimal axis limits
ylimits=[0 0];
for dindex=1:numdurs
    for Raindex=1:numamps
        for Laindex=1:numamps

            for findex=1:numfreqs
                ge=squeeze(in.GE(findex, Raindex, Laindex,  dindex, :));
                gi=squeeze(in.GI(findex, Raindex, Laindex,  dindex, :));
                if min([ge; gi])<ylimits(1) ylimits(1)=min([ge; gi]);end
                if max([ge; gi])>ylimits(2) ylimits(2)=max([ge; gi]);end
            end
        end
    end
end
ylimits(2)=1.1*ylimits(2);

% %plot the peak tuning curve
% 
% for dindex=1:numdurs
%     for findex=1:numfreqs
%         figure
%         p=0;
%         subplot1( numamps, 1)
%         for Raindex=[numamps:-1:1]
%             p=p+1;
%             subplot1( p)
%             for Laindex=[1:numamps]
%                 ge=squeeze(in.GE(findex, Raindex, Laindex, dindex,  :));
%                 gi=squeeze(in.GI(findex, Raindex, Laindex, dindex,  :));
%                 getc(findex, Raindex, Laindex, dindex)=max(ge);
%                 gitc(findex, Raindex, Laindex, dindex)=max(gi);
%             end
%             r=plot(1:numamps, squeeze(getc(findex, Raindex, :, dindex)), 'go-', ...
%                 1:numamps, squeeze(gitc(findex, Raindex, :, dindex)), 'ro-');
%             set(r, 'linewidth', 2)
%             xlimits=[.9 numamps+.1];
%             xlim(xlimits);
%             ylim(ylimits)
%             set(gca, 'xtick', 1:7)
%             set(gca, 'ytick', [floor(ylimits(1)), 0,floor(ylimits(2))])
%             if Ramps(Raindex)==-1000
%                 text(xlimits(1)-.4, mean(ylimits), 'silence', 'HorizontalAlignment', 'center');
%             else
%                 text(xlimits(1)-.4, mean(ylimits), int2str(Ramps(Raindex)))
%             end
%             line(xlimits, [8 8], 'linestyle', ':')
%         end
%         Rampslab=num2cell(Ramps);
%         Rampslab{1}='silence';
%         set(gca, 'xticklabel', Rampslab)
%         subplot1(1)
%         h=title(sprintf('Binaural Peak Ge,Gi %s-%s-%s %.1f kHz dur: %d ms', expdate,session, filenum, freqs(findex)/1000, durs(dindex)));
%         set(h, 'HorizontalAlignment', 'left')
%         subplot1(round(numamps/2))
%         T=text(xlimits(1)-.6, mean(ylimits), 'Contralateral level (dB)',  'rotation', 90);
%         subplot1(numamps);
%         xlabel('Ipsilateral level (dB)')
%     end
% end

%compute some ratio tuning curves
ylimits=[0 0];
for dindex=1:numdurs
    for Raindex=1:numamps
        for Laindex=1:numamps
            for findex=1:numfreqs
%                 peakge=max(squeeze(in.GE(findex, Raindex, Laindex, dindex,  :)));
%                 peakgi=max(squeeze(in.GI(findex, Raindex, Laindex, dindex,  :)));
%                 sumge=sum(squeeze(in.GE(findex, Raindex, Laindex, dindex,  :)));
%                 sumgi=sum(squeeze(in.GI(findex, Raindex, Laindex, dindex,  :)));
%                 %                 eitc(Laindex)=peakge/peakgi;
%                 eitc(Laindex)=sumge/sumgi;
%                 if min(eitc)<ylimits(1) ylimits(1)=min(eitc);end
%                 if max(eitc)>ylimits(2) ylimits(2)=max(eitc);end
                ge=squeeze(out.GE(findex, Raindex, Laindex, dindex,  (xl(1)-xlimits(1))*samprate/1000+1:(xl(2)-xlimits(1))*samprate/1000));
                gi=squeeze(out.GI(findex, Raindex, Laindex, dindex,  (xl(1)-xlimits(1))*samprate/1000+1:(xl(2)-xlimits(1))*samprate/1000));
                sumge(Raindex, Laindex)=sum(ge);
                sumgi(Raindex, Laindex)=sum(gi);
                peakge(Raindex, Laindex)=max(ge);
                peakgi(Raindex, Laindex)=max(gi);
            end
        end
    end
end

peakEItc=peakge./peakgi;
sumEItc=sumge./sumgi;
peakIEtc=peakgi./peakge;
sumIEtc=sumgi./sumge;
peakFetc=peakge./(peakge+peakgi);
sumFetc=sumge./(sumge+sumgi);
% ylimits(2)=1.1*ylimits(2);
ylimits=[-1 5];





% % heat map: Peak Ge/Peak Gi
% figure
% set(gca, 'fontsize', fs)
% i=imagesc(peakEItc);
% set(gca, 'ydir', 'normal')
% % xtick=1:length(freqs);
% %xtick=1:3:length(freqs);
% %set(gca, 'xtick', xtick)
% %set(gca, 'xticklabel',  round(freqs(xtick)/100)/10)
% set(gca, 'xtick', 1:length(Lamps))
% set(gca, 'xticklabel',  round(Lamps))
% set(gca, 'ytick', 1:length(Ramps))
% set(gca, 'yticklabel', round(Ramps))
% silence_label(5)
% xlabel('Ipsilateral level')
% ylabel('Contralateral level')
% c=colorbar;
% clab=get(c, 'ylabel');
% set(clab, 'string','Peak Ge/Peak Gi')
% h=title(sprintf('Binaural (Peak Ge)/(Peak Gi) %s-%s-%s %.1f kHz dur: %d ms', expdate,session, filenum, freqs(findex)/1000, durs(dindex)));


%plot the peak E/I
for dindex=1:numdurs
    for findex=1:numfreqs
        figure

        p=0;
        subplot1(numamps, 1)

        for Raindex=numamps:-1:1
            p=p+1;
            subplot1( p)
      
            r=plot(1:numamps, peakEItc(Raindex,:), 'ko-');
            set(r, 'linewidth', 2)
            set(gca, 'fontsize', fs)
            xl=[.9 numamps+.1];
            xlim(xl);
%             yyy1=get(gca,'ylim')
%             ylim(y1);
            line(xl, [1 1], 'linestyle', ':')
            ylim(ylimits)
            set(gca, 'xtick', 1:7)
%            set(gca, 'ytick', [ceil(ylimits(1)), floor(ylimits(2))])

            if Ramps(Raindex)==-1000
                text(xl(1)-.4, mean(ylimits), 'silence', 'HorizontalAlignment', 'center', 'fontsize', fs);
            else
                text(xl(1)-.4, mean(ylimits), int2str(Ramps(Raindex)), 'fontsize', fs)
            end
        end
        Rampslab=num2cell(Ramps);
        Rampslab{1}='silence';
        set(gca, 'xticklabel', Rampslab)
        subplot1(1)
        h=title(sprintf('Binaural (Peak Ge)/(Peak Gi) %s-%s-%s %.1f kHz dur: %d ms', expdate,session, filenum, freqs(findex)/1000, durs(dindex)));
        %set(h, 'HorizontalAlignment', 'Left')
        subplot1(round(numamps/2))
        T=text(xl(1)-.6, mean(ylimits), 'Contralateral level (dB)',  'rotation', 90, 'fontsize', fs);
        subplot1(numamps);
        xlabel('Ipsilateral level (dB)')
    end
end

% % Binaural (Sum Ge)/(Sum Gi) heat map
% figure
% set(gca, 'fontsize', fs)
% i=imagesc(sumEItc);
% set(gca, 'ydir', 'normal')
% % xtick=1:length(freqs);
% %xtick=1:3:length(freqs);
% %set(gca, 'xtick', xtick)
% %set(gca, 'xticklabel',  round(freqs(xtick)/100)/10)
% set(gca, 'xtick', 1:length(Lamps))
% set(gca, 'xticklabel',  round(Lamps))
% set(gca, 'ytick', 1:length(Ramps))
% set(gca, 'yticklabel', round(Ramps))
% silence_label(5)
% xlabel('Ipsilateral level')
% ylabel('Contralateral level')
% c=colorbar;
% clab=get(c, 'ylabel');
% set(clab, 'string','Sum Ge/Sum Gi')
%         h=title(sprintf('Binaural (Sum Ge)/(Sum Gi) %s-%s-%s %.1f kHz dur: %d ms', expdate,session, filenum, freqs(findex)/1000, durs(dindex)));

% 
% %plot the sum E/I
% for dindex=1:numdurs
%     for findex=1:numfreqs
%         figure
% 
%         p=0;
%         subplot1( numamps, 1)
% 
%         for Raindex=[numamps:-1:1]
%             p=p+1;
%             subplot1( p)
%       
%             r=plot(1:numamps, sumEItc(Raindex,:), 'ko-');
%             set(r, 'linewidth', 2)
%             set(gca, 'fontsize', fs)
%             xl=[.9 numamps+.1];
%             xlim(xl);
% %             yyy2=get(gca,'ylim')
% %             ylim(y2);
%             line(xl, [1.5 1.5], 'linestyle', ':')
% %             ylim(ylimits)
%             set(gca, 'xtick', 1:7)
% %            set(gca, 'ytick', [ceil(ylimits(1)), floor(ylimits(2))])
% 
%             if Ramps(Raindex)==-1000
%                 text(xl(1)-.4, mean(ylimits), 'silence', 'HorizontalAlignment', 'center', 'fontsize', fs);
%             else
%                 text(xl(1)-.4, mean(ylimits), int2str(Ramps(Raindex)), 'fontsize', fs)
%             end
%         end
%         Rampslab=num2cell(Ramps);
%         Rampslab{1}='silence';
%         set(gca, 'xticklabel', Rampslab)
%         subplot1(1)
%         h=title(sprintf('Binaural (Sum Ge)/(Sum Gi) %s-%s-%s %.1f kHz dur: %d ms', expdate,session, filenum, freqs(findex)/1000, durs(dindex)));
%         %set(h, 'HorizontalAlignment', 'Ipsilateral')
%         subplot1(round(numamps/2))
%         T=text(xl(1)-.6, mean(ylimits), 'Contralateral level (dB)',  'rotation', 90, 'fontsize', fs);
%         subplot1(numamps);
%         xlabel('Ipsilateral level (dB)')
%     end
% end



% % Binaural (Peak Gi)/(Peak Ge) heat map
% figure
% set(gca, 'fontsize', fs)
% i=imagesc(peakIEtc);
% set(gca, 'ydir', 'normal')
% % xtick=1:length(freqs);
% %xtick=1:3:length(freqs);
% %set(gca, 'xtick', xtick)
% %set(gca, 'xticklabel',  round(freqs(xtick)/100)/10)
% set(gca, 'xtick', 1:length(Lamps))
% set(gca, 'xticklabel',  round(Lamps))
% set(gca, 'ytick', 1:length(Ramps))
% set(gca, 'yticklabel', round(Ramps))
% silence_label(5)
% xlabel('Ipsilateral level')
% ylabel('Contralateral level')
% c=colorbar;
% clab=get(c, 'ylabel');
% set(clab, 'string','Peak Gi/Peak Ge')
%         h=title(sprintf('Binaural (Peak Gi)/(Peak Ge) %s-%s-%s %.1f kHz dur: %d ms', expdate,session, filenum, freqs(findex)/1000, durs(dindex)));



% %plot the peak I/E
% for dindex=1:numdurs
%     for findex=1:numfreqs
%         figure
% 
%         p=0;
%         subplot1( numamps, 1)
% 
%         for Raindex=[numamps:-1:1]
%             p=p+1;
%             subplot1( p)
%       
%             r=plot(1:numamps, peakIEtc(Raindex,:), 'ko-');
%             set(r, 'linewidth', 2)
%             set(gca, 'fontsize', fs)
%             xl=[.9 numamps+.1];
%             xlim(xl);
%             meme1=get(gca,'ylim')
%             ylim(y1)
%             line(xl, [1 1], 'linestyle', ':')
% %             ylim(ylimits)
%             set(gca, 'xtick', 1:7)
% %            set(gca, 'ytick', [ceil(ylimits(1)), floor(ylimits(2))])
% 
%             if Ramps(Raindex)==-1000
%                 text(xl(1)-.4, mean(ylimits), 'silence', 'HorizontalAlignment', 'center', 'fontsize', fs);
%             else
%                 text(xl(1)-.4, mean(ylimits), int2str(Ramps(Raindex)), 'fontsize', fs)
%             end
%         end
%         Rampslab=num2cell(Ramps);
%         Rampslab{1}='silence';
%         set(gca, 'xticklabel', Rampslab)
%         subplot1(1)
%         h=title(sprintf('Binaural (Peak Gi)/(Peak Ge) %s-%s-%s %.1f kHz dur: %d ms', expdate,session, filenum, freqs(findex)/1000, durs(dindex)));
%         %set(h, 'HorizontalAlignment', 'Ipsilateral')
%         subplot1(round(numamps/2))
%         T=text(xl(1)-.6, mean(ylimits), 'Contralateral level (dB)',  'rotation', 90, 'fontsize', fs);
%         subplot1(numamps);
%         xlabel('Ipsilateral level (dB)')
%     end
% end
% 

% % Sum Ge/Sum Gi heat map
% figure
% set(gca, 'fontsize', fs)
% i=imagesc(sumIEtc);
% set(gca, 'ydir', 'normal')
% % xtick=1:length(freqs);
% %xtick=1:3:length(freqs);
% %set(gca, 'xtick', xtick)
% %set(gca, 'xticklabel',  round(freqs(xtick)/100)/10)
% set(gca, 'xtick', 1:length(Lamps))
% set(gca, 'xticklabel',  round(Lamps))
% set(gca, 'ytick', 1:length(Ramps))
% set(gca, 'yticklabel', round(Ramps))
% silence_label(5)
% xlabel('Ipsilateral level')
% ylabel('Contralateral level')
% c=colorbar;
% clab=get(c, 'ylabel');
% set(clab, 'string','Sum Ge/Sum Gi')
%         h=title(sprintf('Binaural (Sum Gi)/(Sum Ge) %s-%s-%s %.1f kHz dur: %d ms', expdate,session, filenum, freqs(findex)/1000, durs(dindex)));



% %plot the sum I/E
% for dindex=1:numdurs
%     for findex=1:numfreqs
%         figure
% 
%         p=0;
%         subplot1( numamps, 1)
% 
%         for Raindex=[numamps:-1:1]
%             p=p+1;
%             subplot1( p)
%       
%             r=plot(1:numamps, sumIEtc(Raindex,:), 'ko-');
%             set(r, 'linewidth', 2)
%             set(gca, 'fontsize', fs)
%             xl=[.9 numamps+.1];
%             xlim(xl);
%             meme2=get(gca,'ylim')
%             ylim(y2)
%             line(xl, [1 1], 'linestyle', ':')
% %             ylim(ylimits)
%             set(gca, 'xtick', 1:7)
% %            set(gca, 'ytick', [ceil(ylimits(1)), floor(ylimits(2))])
% 
%             if Ramps(Raindex)==-1000
%                 text(xl(1)-.4, mean(ylimits), 'silence', 'HorizontalAlignment', 'center', 'fontsize', fs);
%             else
%                 text(xl(1)-.4, mean(ylimits), int2str(Ramps(Raindex)), 'fontsize', fs)
%             end
%         end
%         Rampslab=num2cell(Ramps);
%         Rampslab{1}='silence';
%         set(gca, 'xticklabel', Rampslab)
%         subplot1(1)
%         h=title(sprintf('Binaural (Sum Gi)/(Sum Ge) %s-%s-%s %.1f kHz dur: %d ms', expdate,session, filenum, freqs(findex)/1000, durs(dindex)));
%         %set(h, 'HorizontalAlignment', 'Ipsilateral')
%         subplot1(round(numamps/2))
%         T=text(xl(1)-.6, mean(ylimits), 'Contralateral level (dB)',  'rotation', 90, 'fontsize', fs);
%         subplot1(numamps);
%         xlabel('Ipsilateral level (dB)')
%     end
% end


% % peak Fe heat map
% figure
% set(gca, 'fontsize', fs)
% i=imagesc(peakFetc);
% set(gca, 'ydir', 'normal')
% % xtick=1:length(freqs);
% %xtick=1:3:length(freqs);
% %set(gca, 'xtick', xtick)
% %set(gca, 'xticklabel',  round(freqs(xtick)/100)/10)
% set(gca, 'xtick', 1:length(Lamps))
% set(gca, 'xticklabel',  round(Lamps))
% set(gca, 'ytick', 1:length(Ramps))
% set(gca, 'yticklabel', round(Ramps))
% silence_label(5)
% xlabel('Ipsilateral level')
% ylabel('Contralateral level')
% c=colorbar;
% clab=get(c, 'ylabel');
% set(clab, 'string','Peak Fe')
%         h=title(sprintf('Binaural (Peak Fe) %s-%s-%s %.1f kHz dur: %d ms', expdate,session, filenum, freqs(findex)/1000, durs(dindex)));



% %plot the peakFetc
% for dindex=1:numdurs
%     for findex=1:numfreqs
%         figure
% 
%         p=0;
%         subplot1( numamps, 1)
% 
%         for Raindex=[numamps:-1:1]
%             p=p+1;
%             subplot1( p)
%       
%             r=plot(1:numamps, peakFetc(Raindex,:), 'ko-');
%             set(r, 'linewidth', 2)
%             set(gca, 'fontsize', fs)
%             xl=[.5 numamps+.5];
%             xlim(xl);
%             line(xl, [.5 .5], 'linestyle', ':')
% %             ylim(ylimits)
%             set(gca, 'xtick', 1:7)
% %            set(gca, 'ytick', [ceil(ylimits(1)), floor(ylimits(2))])
% 
%             if Ramps(Raindex)==-1000
%                 text(xl(1)-.4, mean(ylimits), 'silence', 'HorizontalAlignment', 'center', 'fontsize', fs);
%             else
%                 text(xl(1)-.4, mean(ylimits), int2str(Ramps(Raindex)), 'fontsize', fs)
%             end
%         end
%         Rampslab=num2cell(Ramps);
%         Rampslab{1}='silence';
%         set(gca, 'xticklabel', Rampslab)
%         subplot1(1)
%         h=title(sprintf('Binaural (Peak Fe) %s-%s-%s %.1f kHz dur: %d ms', expdate,session, filenum, freqs(findex)/1000, durs(dindex)));
%         %set(h, 'HorizontalAlignment', 'Ipsilateral')
%         subplot1(round(numamps/2))
%         T=text(xl(1)-.6, mean(ylimits), 'Contralateral level (dB)',  'rotation', 90, 'fontsize', fs);
%         subplot1(numamps);
%         xlabel('Ipsilateral level (dB)')
%     end
% end


% % Sum Fe heat map
% figure
% set(gca, 'fontsize', fs)
% i=imagesc(sumFetc);
% set(gca, 'ydir', 'normal')
% % xtick=1:length(freqs);
% %xtick=1:3:length(freqs);
% %set(gca, 'xtick', xtick)
% %set(gca, 'xticklabel',  round(freqs(xtick)/100)/10)
% set(gca, 'xtick', 1:length(Lamps))
% set(gca, 'xticklabel',  round(Lamps))
% set(gca, 'ytick', 1:length(Ramps))
% set(gca, 'yticklabel', round(Ramps))
% silence_label(5)
% xlabel('Ipsilateral level')
% ylabel('Contralateral level')
% c=colorbar;
% clab=get(c, 'ylabel');
% set(clab, 'string','Sum Fe')
%         h=title(sprintf('Binaural (Sum Fe) %s-%s-%s %.1f kHz dur: %d ms', expdate,session, filenum, freqs(findex)/1000, durs(dindex)));




% %plot the sumFetc
% for dindex=1:numdurs
%     for findex=1:numfreqs
%         figure
% 
%         p=0;
%         subplot1( numamps, 1)
% 
%         for Raindex=[numamps:-1:1]
%             p=p+1;
%             subplot1( p)
%       
%             r=plot(1:numamps, sumFetc(Raindex,:), 'ko-');
%             set(r, 'linewidth', 2)
%             set(gca, 'fontsize', fs)
%             xl=[.5 numamps+.5];
%             xlim(xl);
%             line(xl, [.5 .5], 'linestyle', ':')
% %             ylim(ylimits)
%             set(gca, 'xtick', 1:7)
% %            set(gca, 'ytick', [ceil(ylimits(1)), floor(ylimits(2))])
% 
%             if Ramps(Raindex)==-1000
%                 text(xl(1)-.4, mean(ylimits), 'silence', 'HorizontalAlignment', 'center', 'fontsize', fs);
%             else
%                 text(xl(1)-.4, mean(ylimits), int2str(Ramps(Raindex)), 'fontsize', fs)
%             end
%         end
%         Rampslab=num2cell(Ramps);
%         Rampslab{1}='silence';
%         set(gca, 'xticklabel', Rampslab)
%         subplot1(1)
%         h=title(sprintf('Binaural (Sum Fe) %s-%s-%s %.1f kHz dur: %d ms', expdate,session, filenum, freqs(findex)/1000, durs(dindex)));
%         %set(h, 'HorizontalAlignment', 'Ipsilateral')
%         subplot1(round(numamps/2))
%         T=text(xl(1)-.6, mean(ylimits), 'Contralateral level (dB)',  'rotation', 90, 'fontsize', fs);
%         subplot1(numamps);
%         xlabel('Ipsilateral level (dB)')
%     end
% end
fprintf('\n');

% Place relevant info into outfile
clear out
stimtypes=stimtype(expdate, session, filenum);
if sum(strcmp(stimtypes,'bintone'))==1
    outfilename2=sprintf('out%s-%scf%d.mat',expdate,session,durs);
elseif sum(strcmp(stimtypes,'binwhitenoise'))==1
    outfilename2=sprintf('out%s-%swn%d.mat',expdate,session,durs);
end
if exist(outfilename2,'file')==2
    load(outfilename2)
end
out.peakEItc=peakEItc(end:-1:1,:);
out.sumEItc=sumEItc(end:-1:1,:);
out.peakIEtc=peakIEtc(end:-1:1,:);
out.sumIEtc=sumIEtc(end:-1:1,:);
out.peakFetc=peakFetc(end:-1:1,:);
out.sumFetc=sumFetc(end:-1:1,:);
save(outfilename2,'out')

function silence_label(n)
%change '-1000' to 'silence' and re-center
%inputs:
%    n: number of blanks to insert
l=get(gca, 'xticklabel');
m=strvcat('silence', l(2:end,:));
set(gca, 'xticklabel', m)
for i=1:n
    m=[blanks(size(m, 1))' m];
end
set(gca, 'xticklabel', m)

l=get(gca, 'yticklabel');
m=strvcat('silence', l(2:end,:));
set(gca, 'yticklabel', m)
for i=1:n
    m=[blanks(size(m, 1))' m];
end
set(gca, 'yticklabel', m)



