function PlotToneTrain(expdate, session, filenum, varargin)
%usage:  PlotToneTrain(expdate, session, filenum, [xlimits], [ylimits])
%
%loads processed data from an outfile generated by ProcessToneTrain
%
% this function is meant to replace PlotToneTrain_A1 since you can now specify xlimits

if nargin==0
    fprintf('\nno input');
    return;
elseif nargin==3
    xlimits=-1; %x limits for axis
    ylimits=-1;
elseif nargin==4
    xlimits=varargin{1};
    ylimits=-1;
    if isempty(xlimits) xlimits=-1;end
elseif nargin==5
    xlimits=varargin{1};
    if isempty(xlimits) xlimits=-1;end
    ylimits=varargin{2};
    if isempty(ylimits) ylimits=-1; end
end

godatadir(expdate, session, filenum)
outfilename=sprintf('out%s-%s-%s',expdate,session, filenum);
fprintf('\ntrying to load %s...', outfilename)
load(outfilename);
fprintf('done\n');

fprintf('\ntotal number of repeats: %d', size(Mc, 3))
totalnumrepeats=size(Mc, 3);
samprate=1e4;
% repc_range=501:1100;
  %repc_range=[1:200]+300;
repc_range=1:totalnumrepeats;
mMc=mean(Mc(:,:,repc_range,:), 3);
%mMc=mean(Mc, 3);
mMcs=mean(Mcs, 3);

if xlimits==-1
    xlimits=[-.5*dur 1.5*dur]; %x limits for axis, dur is saved in outfile by ProcessToneTrain
end
if ylimits==-1
    ylimits(1)=min(min(min(min(mMc))));
    ylimits(2)=max(max(max(max(mMc))));
end

%xl=[5 20];
%yl=.03*[-1 1];
%yl=.1*[-1 1];
stim_scalefactor=.2*diff(ylimits);
stim_offset=-ylimits(1)/2;

%plot the mean tuning curve 
figure
p=0;
subplot1( numamps,numfreqs)
for aindex=[numamps:-1:1]
    for findex=1:numfreqs
        p=p+1;
        subplot1( p)
        trace1=squeeze(mMc(findex, aindex, :));
        trace1=trace1-mean(trace1(1:100));
        trace_stim=squeeze(mMcs(findex, aindex,1, :)); %mean stimulus
%        trace_stim=squeeze(Mcs(findex, aindex,10, :));
        trace_stim=trace_stim-mean(trace_stim(1:100));
        trace_stimn=trace_stim/max(trace_stim); %normalize stim
        t=1:length(trace1);
        t=t/10;
        t=t-baseline; %baseline stored in outfile
        plot(t, trace1, 'b', t, stim_scalefactor*trace_stimn-stim_offset, 'r');
        xlim(xlimits)
        ylim(ylimits)
        %        axis([0 15 -0.040    0.040])
        if findex==1
            ylabel(sprintf('%d dB',    round(amps(aindex))))
        end
        if aindex==1
            xlabel(sprintf('%d kHz', round(freqs1(findex))))
        end
        %        axis off
        %  xlabel(sprintf('%.1fkHz', freqs(findex)))
    end
end
subplot1(ceil(numfreqs/3))
title(sprintf('%s-%s-%s, ABR, mean tones %d-%d', expdate,session, filenum, repc_range(1), repc_range(end)))
shg

%  keyboard

return

%examine trial-by-trial
figure;hold on
offset=max(max(max(max(Mc))));
%findex=numfreqs;
findex=1;
aindex=1;
t=1:size(Mc, 4);t=t*1000/samprate;
for i=1:size(Mc,3)
    trace=squeeze(Mc(findex, aindex, i, :));
    plot(t, trace + offset*i)
end

figure;
hold on;
for i=1:size(Mt,1)
    plot(Mt(i,1:3800)+15*i);
    plot(Ms(i,1:3800)+15*i, 'r');
end

keyboard

