function PlotWNTrain2_lfp(expdate, session, filenum, varargin)
% usage: PlotWNTrain2(expdate, session, filenum, [ylimits])
% 
% plots an averaged tuning curve for WNTrain2 stimuli
% (these are WN trains at various isis but with fixed train duration)
% loads processed data from an outfile generated by ProcessWNTrain2_lfp

if nargin==0
    fprintf('\nnoinput\n')
    return
elseif nargin==4
    ylimits=varargin{1};
elseif nargin~=3 error('PlotWNTrain2: wrong number of arguments');
end

outfilename=sprintf('out%s-%s-%s',expdate,session, filenum);
fprintf('\ntrying to load %s...', outfilename)
try
    godatadir(expdate, session, filenum)
    load(outfilename)
catch
    fprintf('failed to load outfile')
    ProcessWNTrain2_lfp(expdate, session, filenum);
    load(outfilename);
end

fprintf('done\n');

mMt=out.mMt;
mMs=out.mMs;
numisis=out.numisis;

stim_offset=min(reshape(mMt, 1, prod(size(mMt))));
stim_mag=.05*(max(reshape(mMt, 1, prod(size(mMt))))-stim_offset);

%plot the mean traces
figure
p=0;
subplot1(numisis, 1)
for isiindex=[1:numisis]
    p=p+1;
    subplot1( p)
    trace1=squeeze(mMt(isiindex, :));
    trace1=trace1-median(trace1);
    trace_stim=squeeze(mMs(isiindex, :));
    trace_stim=trace_stim-median(trace_stim(1:100));
    trace_stim=trace_stim/max(trace_stim); %normalize stim
    t=1:length(trace1);
    t=t/10;
    plot(t, trace1, 'b', t, stim_mag*trace_stim+stim_offset, 'r');
%     title(sprintf('isi %dms, %d reps', out.isis(isiindex),out.nreps(isiindex)))
end

%make ylim uniform
if nargin~=4
    ylimits=ylim;
    for p=[1:numisis]
        subplot1( p)
        yl=ylim;
        ylimits(1)=min(ylimits(1), yl(1));
        ylimits(2)=max(ylimits(2), yl(2));
    end
end
for p=[1:numisis]
    subplot1( p)
    ylim(ylimits);
    T=text(mean(xlim), ylimits(2), sprintf('isi %dms, %d reps', out.isis(p),out.nreps(p)));
    set(T, 'HorizontalAlignment', 'center','VerticalAlignment', 'top')
end

subplot1(1)
title(sprintf('%s-%s-%s %s', expdate,session, filenum, get(get(gca, 'title'), 'string')))
set(gcf, 'pos', [618    72      520   900])
shg
refresh
orient tall

% in a separate window, zoom in on individual responses
figure
p=0;
subplot1(numisis, 1)
for isiindex=[1:numisis]
    p=p+1;
    subplot1( p)
    traceP1=squeeze(out.Mc(isiindex,1, :)); %first click
    traceP2=squeeze(out.Mc(isiindex,2, :)); %second click
    tracePN=squeeze(out.Mc(isiindex,out.nclicks(isiindex), :)); %last click
    tracePN5=squeeze(out.Mc(isiindex, out.nclicks(isiindex)-4:out.nclicks(isiindex), :));
    tracePN5=mean(tracePN5); %mean of last 5 clicks

    trace_stimP1=squeeze(out.Mcs(isiindex,1, :));
    trace_stimP1=trace_stimP1-median(trace_stimP1(1:100));
    trace_stimP1=trace_stimP1/max(trace_stimP1); %normalize stim
    t=1:length(traceP1);
    t=t/10;
    plot(t, traceP1, 'b')
    hold on
    plot(t, traceP2, 'g')
    plot(t, tracePN, 'm')
    plot(t, tracePN5, 'r')
    plot(t, stim_mag*trace_stimP1+stim_offset, 'k');
%     title(sprintf('isi %dms, %d reps', out.isis(isiindex),out.nreps(isiindex)))
end
legend('P1', 'P2', 'PN', 'PN5', 'stim')
%make ylim uniform
if nargin~=4
    ylimits=ylim;
    for p=[1:numisis]
        subplot1( p)
        yl=ylim;
        ylimits(1)=min(ylimits(1), yl(1));
        ylimits(2)=max(ylimits(2), yl(2));
    end
end
for p=[1:numisis]
    subplot1( p)
    ylim(ylimits);
    T=text(mean(xlim), ylimits(2), sprintf('isi %dms, %d reps', out.isis(p),out.nreps(p)));
     set(T, 'HorizontalAlignment', 'center','VerticalAlignment', 'top')
end
subplot1(1)
title(sprintf('%s-%s-%s %s', expdate,session, filenum, get(get(gca, 'title'), 'string')))
set(gcf, 'pos', [1147          72   520   900])
shg
refresh
orient tall