function PlotToneTrain_A1(expdate, session, filenum, varargin)
% usage: PlotToneTrain_A1(expdate, session, filenum, [xlimits])
% 
%loads processed data in an outfile generated by ProcessToneTrain_A1
%
% plots an averaged tuning curve for tonetrain stimuli
%same as PlotToneTrain but some parameters are optimized for A1 responses
%instead of ABRs (like axis limits, maybe some other stuff?)
%
% this function has been replaced by PlotToneTrain since you can now specify xlimits

if nargin~=3 error('PlotToneTrain_A1: wrong number of arguments');end
    
area='A1';
outfilename=sprintf('out%s-%s-%s',expdate,session, filenum);
fprintf('\ntrying to load %s...', outfilename)
godatadir(expdate, session, filenum)
load(outfilename);
fprintf('done\n');

samprate=1e4;
%trials=21:40;
trials=1:size(Mc, 3);
mMc=mean(Mc(:,:,trials,:), 3);
mMcs=mean(Mcs, 3);




%plot the mean tuning curves for pre and post
figure
p=0;
subplot1( numamps,numfreqs)
for aindex=[numamps:-1:1]
    for findex=1:numfreqs
        p=p+1;
        subplot1( p)
        trace1=squeeze(mMc(findex, aindex, :));
        trace1=trace1-mean(trace1(1:100));
         trace1=trace1/max(abs(trace1)); %normalize trace
        trace_stim=squeeze(mMcs(findex, aindex, :));
        trace_stim=trace_stim-mean(trace_stim(1:100));
        trace_stim=trace_stim/max(trace_stim); %normalize stim
        t=1:length(trace1);
        t=t/10;
        plot(t, trace_stim-.5, 'r', t, trace1, 'b' );
%         plot(t, trace1, 'b', t, .005*trace_stim-.03, 'r');
%         xlim([0 10])
%         axis([0 10 -0.040    0.040])
if findex==1
    ylabel(sprintf('%d dB',    round(amps(aindex))))
end
if aindex==1
    xlabel(sprintf('%d kHz', round(freqs1(findex))))
end
%        axis off
      %  xlabel(sprintf('%.1fkHz', freqs(findex)))
    end
end
subplot1(ceil(numfreqs/3))
if ~exist('isi'); isi=-666; end
title(sprintf('%s-%s-%s, %s, isi=%dms, mean of %d tones', expdate,session, filenum,area, isi,size(Mc, 3)))
shg

% keyboard

%return

%examine trial-by-trial
figure;hold on
offset=.1*max(max(max(max(Mc))));
%findex=numfreqs;
findex=1;
aindex=1;
t=1:size(Mc, 4);t=t*1000/samprate;
for i=1:size(Mc,3)
    trace=squeeze(Mc(findex, aindex, i, :));
    plot(t, trace + offset*i)
end
trace_stim=squeeze(Mcs(1,1,1,:));
trace_stim=trace_stim./max(abs(trace_stim));
plot(t, max(trace)*trace_stim, 'r')

% figure;
% hold on;
% for i=1:size(Mt,1)
%     plot(Mt(i,1:3800)+15*i);
%     plot(Ms(i,1:3800)+15*i, 'r');
% end

% keyboard

