function PlotWN2_RRTF_lfp(expdate, session, filenum)
% usage: PlotWN2_RRTF_lfp(expdate, session, filenum)
% plots repetition rate tranfer function for WNTrain2 stimuli
%(these are WN trains at various isis but with fixed train duration)
%looks for outfile generated by ProcessWNTrain2_lfp

if nargin==0 
    fprintf('\nnoinput\n')
    return
elseif nargin~=3 error('PlotWNTrain2: wrong number of arguments');
end

outfilename=sprintf('out%s-%s-%s',expdate,session, filenum);

fprintf('\ntrying to load %s...', outfilename)
try
    godatadir(expdate, session, filenum)
    load(outfilename)
catch
    fprintf('failed to load outfile')
    return
end

fprintf('done\n');

mMt=out.mMt; %mean response to the whole train
mMs=out.mMs; %same as mMt but is the stimulus
numisis=out.numisis;
isis=out.isis;
nclicks=out.nclicks;
Mc=out.Mc; %Mc is mean response to each click, numisis X nclicks X tracelength
Mcs=out.Mcs; %same as Mc but is the stimulus

stim_offset=min(reshape(mMt, 1, prod(size(mMt))));
stim_mag=.05*(max(reshape(mMt, 1, prod(size(mMt))))-stim_offset);

figure
p=0;
subplot1(numisis, 2)

%plot first and last click response
for isiindex=[1:numisis]
    p=p+1;
    subplot1( p)
    trace1=squeeze(Mc(isiindex, 1, :));
    trace1=trace1-median(trace1);
    trace_stim=squeeze(Mcs(isiindex, 1, :));
    trace_stim=trace_stim-median(trace_stim(1:100));
    trace_stim=trace_stim/max(trace_stim); %normalize stim
    t=1:length(trace1);
    t=t/10;
    plot(t, trace1, 'b', t, stim_mag*trace_stim+stim_offset, 'r');
    title(sprintf('isi %dms, first click', out.isis(isiindex)))

    p=p+1;
    subplot1( p)
    trace1=squeeze(Mc(isiindex, nclicks(isiindex), :));
    trace1=trace1-median(trace1);
    trace_stim=squeeze(Mcs(isiindex, nclicks(isiindex), :));
    trace_stim=trace_stim-median(trace_stim(1:100));
    trace_stim=trace_stim/max(trace_stim); %normalize stim
    t=1:length(trace1);
    t=t/10;
    plot(t, trace1, 'b', t, stim_mag*trace_stim+stim_offset, 'r');
    title(sprintf('isi %dms, last click', out.isis(isiindex)))
end



%make ylim uniform
ylimits=ylim;
for p=[1:2*numisis]
    subplot1( p)
    yl=ylim;
    ylimits(1)=min(ylimits(1), yl(1));
    ylimits(2)=max(ylimits(2), yl(2));
end
for p=[1:2*numisis]
    subplot1( p)
    ylim(ylimits);
end

subplot1(1)

title(sprintf('%s-%s-%s\t%s', expdate,session, filenum, get(get(gca, 'title'), 'string')))



%compute RRTF as ratio of last/first click response
for isiindex=[1:numisis]
    trace1=squeeze(Mc(isiindex, 1, :));
    trace1=trace1-median(trace1);

    tracen=squeeze(Mc(isiindex, nclicks(isiindex), :));
    tracen=tracen-median(tracen);
    
    RRTF(isiindex)=max(abs(tracen))/max(abs(trace1));
end

figure
plot(RRTF, 'o-')
set(gca, 'xtick', 1:numisis, 'xticklabel', isis)
xlabel('isi, ms')
ylabel('last/first click ratio')
set(gca, 'xdir', 'reverse')

out.RRTF=RRTF;
save(outfilename, 'out')

% %assign outputs
% out.scaledtrace=scaledtrace;
% out.M1=M1;
% out.M1stim=M1stim;
% out.mM1stim=mM1stim;
% out.mM1=mM1;
% out.username=username;
% out.expdate=expdate1;
% out.filenum=filenum1;
% out.session=session1;
% out.processed_data_dir=processed_data_dir1;
% out.processed_data_session_dir=processed_data_session_dir1;
% out.datafile=datafile1;
% out.eventsfile=eventsfile1;
% out.stimfile=stimfile1;
% out.lostat=lostat1;
% out.freqs=freqs;
% out.amps=amps;
% out.durs=durs;
% out.nreps=nreps1;
% out.numfreqs=numfreqs;
% out.numamps=numamps;
% out.numdurs=numdurs;
% out.traces_to_keep=traces_to_keep;
% out.event=event1;
% out.xlimits=xlimits;
% out.ylimits=ylimits;
% out.baseline=baseline;
% out.tracelength=tracelength;
% out.samprate=samprate;