function Stimulus_check(expdate, session, filenum, varargin)
% usage: Stimulus_check(expdate, session, filenum, [ylimits])
% 
% plots stimuli to check for soundcard triggering glitches 
% intended for WNTrain2 stimuli, in principle
% loads processed data from an outfile generated by e.g. ProcessWNTrain2_lfp
% if you detect a triggering glitch, one way you can try to fix it is by
% editing ProcessWNTrain2_lfp
% and setting use_soundcard_triggers=0;
%(be sure to change it back to use_soundcard_triggers=1 afterwards!!!!!!!!!!!!!!  
%
%
if nargin==0
    fprintf('\nnoinput\n')
    return
elseif nargin==4
    ylimits=varargin{1};
elseif nargin~=3 error('PlotWNTrain2: wrong number of arguments');
end

outfilename=sprintf('out%s-%s-%s',expdate,session, filenum);
fprintf('\ntrying to load %s...', outfilename)
try
    godatadir(expdate, session, filenum)
    load(outfilename)
catch
    fprintf('failed to load outfile')
    ProcessWNTrain2_lfp(expdate, session, filenum);
    load(outfilename);
end

fprintf('done\n');

mMt=out.mMt;
Ms=out.Ms;
numisis=out.numisis;


stim_mag=1;

%plot the mean traces
figure
p=0;
subplot1(numisis, 1)
for isiindex=[1:numisis]
    stim_offset=0;
    p=p+1;
    subplot1( p)
    for rep=1:out.nreps(isiindex)
        trace_stim=squeeze(Ms(isiindex, rep, :));
        trace_stim=trace_stim-median(trace_stim(1:100));
        trace_stim=trace_stim/max(trace_stim); %normalize stim
        t=1:length(trace_stim);
        t=t/10;
        plot(t, stim_mag*trace_stim+stim_offset, 'r');
        %     title(sprintf('isi %dms, %d reps', out.isis(isiindex),out.nreps(isiindex)))
        stim_offset=stim_offset+1.1;
    end
end

%make ylim uniform
if nargin~=4
    ylimits(1)=-stim_mag/2;
    ylimits(2)=max(out.nreps)+stim_mag/2;    
end
for p=[1:numisis]
    subplot1( p)
    ylim(ylimits);
    T=text(mean(xlim), ylimits(2), sprintf('isi %dms, %d reps', out.isis(p),out.nreps(p)));
    set(T, 'HorizontalAlignment', 'center','VerticalAlignment', 'top')
end

subplot1(1)
title(sprintf('%s-%s-%s %s', expdate,session, filenum, get(get(gca, 'title'), 'string')))
set(gcf, 'pos', [1          61        1680         916])
shg
refresh
orient tall

